src += [
S(8,'CS-C0017','official_audit_work_extract','GAO-preserved WMATA compliance-report work object','https://files.gao.gov/reports/GAO-25-107104/index.html',['bounded audit subject and findings','report issuance before relationship transition'],['normalized extract','substantial staff and statutory support'],'critical-report sections'),
S(9,'CS-C0022','official_federal_regulation','PHS Research Misconduct Policies — 42 CFR Part 93','https://ori.hhs.gov/public-health-service-phs-policies-research-misconduct-%E2%80%93-42-cfr-part-93-%E2%80%93-june-2005',['separated institutional and federal duties','formal findings and correction authority'],['architecture alone is not observed repair']),
S(10,'CS-C0022','official_federal_policy','Federal Research Misconduct Policy','https://ori.hhs.gov/federal-research-misconduct-policy',['culpability and burden standards','honest error and disagreement excluded'],['policy does not prove universal implementation']),
S(11,'CS-C0022','official_final_case_summary','Case Summary: Lin, Yibin','https://ori.hhs.gov/content/case-summary-lin-yibin',['final federal misconduct finding','identified publications retracted'],['one observed use','does not establish relationship repair']),
S(12,'CS-C0027','official_inquiry_response','Grenfell Tower Inquiry Phase 2 government response','https://www.gov.uk/government/publications/grenfell-tower-inquiry-phase-2-report-government-response/grenfell-tower-inquiry-phase-2-report-government-response-html',['residents ignored when raising safety issues','scrutiny resisted and recommendations not reliably acted upon','distributed failures preceded 72 deaths'],['distributed system','not every warning independently adjudicated','reform promises are not durable repair']),
S(13,'CS-C0027','official_inquiry_response_summary','Government response to Grenfell inquiry','https://www.gov.uk/government/news/government-responds-in-full-to-grenfell-tower-inquiry-setting-out-tough-new-reforms-to-fix-building-safety-and-strengthen-accountability',['ignored risks and failures to listen','announced accountability reforms'],['summary only','announcement does not prove implementation']))]
def P(pid,a,task,req,chron,trans,counter,fals):
 return {'packet_id':pid,'attribution_class':a,'review_authority':'mechanism_only_no_person_or_partnership_finding' if a=='system_mechanism' else 'artifact_only_no_operator_finding','task':task,'requirements':req,'bounded_chronology':chron,'observable_transition':trans,'counterevidence':counter,'falsifier':fals}
def O(cid,token,klass,label,record,ids,state,q,summary,missing,fals,packet=None):
 return {'candidate_id':cid,'blind_token':token,'denominator_class':klass,'public_label':label,'source_record_id':record,'source_ids':ids,'acquisition_state':state,'qualification':q,'artifact_summary':summary,'missing_receipts':missing,'falsifier':fals,'blind_packet':packet}
obj=[
O('CS-C0002','CS-BP0002','positive_candidate_operators','Air-and-marine safety disclosure, institutional exclusion, and settlement','K0-W01-R007',['CS-W07-S001'],'partial_original_safety_work_missing','partial_not_blind_ready','Official oversight reconstructs the dispute, exclusion, confirmed facts, and settlement, but not the original safety analysis or recipient receipt.',['original safety work','recipient-state receipt','complete merits record'],'Original bytes showing no bounded safety analysis would defeat advancement.'),
O('CS-C0007','CS-BP0007','false_positive_outsider_genius_candidates','Retaliation complaint dismissed for lack of evidence','K0-W01-R003',['CS-W07-S002'],'partial_public_closure_without_claim_file','partial_not_blind_ready','The public closure preserves non-substantiation, but not the original allegation or evidentiary file.',['original complaint','complete investigation and exhibits'],'A complete file showing corroborated retaliation or independently valid work would reverse the control.')]
