validate=r'''#!/usr/bin/env node
import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{manifest,acquisition,packets,report,html}from'./build-counter-selector-wave-07.mjs';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),J=p=>JSON.parse(fs.readFileSync(path.join(R,p),'utf8')),T=p=>fs.readFileSync(path.join(R,p),'utf8');
export function check(c,s,a,p){assert.deepEqual(a.counts,c.expected_counts);assert.equal(a.records.length,6);assert.equal(s.sources.length,13);assert.equal(new Set(s.sources.map(x=>x.source_id)).size,13);assert.equal(a.records.filter(x=>x.qualification==='qualifying_for_blind_packet').length,4);assert.equal(a.records.filter(x=>x.qualification==='partial_not_blind_ready').length,2);assert.equal(p.packets.length,4);assert.equal(p.packets.filter(x=>x.attribution_class.startsWith('person_attributable')).length,2);assert.equal(p.packets.filter(x=>x.attribution_class==='system_mechanism').length,2);for(let x of a.records){assert.equal(x.blind_packet_ready,x.qualification==='qualifying_for_blind_packet');assert.equal(x.field_test_eligible,false);assert.equal(x.operator_finding,false);assert.equal(x.promotion_generated,false);assert.equal(x.person_ranking_generated,false);assert.equal(x.public_identity_release_authorized,false);assert.equal(x.graph_effect,'none');for(let id of x.source_ids)assert.ok(s.sources.some(z=>z.source_id===id&&z.candidate_id===x.candidate_id))}for(let x of p.packets){assert.equal(x.identity_removed,true);assert.equal(x.status_cues_removed,true);assert.equal(x.source_ids_removed,true);assert.equal(x.denominator_class_removed,true);assert.equal(x.blind_review_executed,false);assert.equal(x.field_test_authorized,false);assert.equal(x.operator_finding,false);assert.equal(x.graph_effect,'none');assert.ok(x.requirements.length>=3&&x.bounded_chronology.length>=4&&x.counterevidence.length>=2)}for(let k of ['official_summary_is_original_work_object','settlement_is_final_merits','catastrophe_after_denied_evidence_is_person_operator_finding','audit_output_is_support_adjusted_surplus','policy_authority_is_observed_partnership_repair','system_correction_is_attributable_operator_capacity','identity_minimized_packet_is_blind_review_result','field_test_authorized'])assert.equal(c.boundaries[k],false);assert.equal(c.boundaries.graph_effect,'none');return true}
export function validate(){let c=J('data/project/counter-selector-wave-07-batch-02.json'),s=J('data/project/counter-selector-wave-07-source-registry.json'),a=J('data/project/counter-selector-artifact-acquisition-b02-registry.json'),p=J('data/project/counter-selector-blind-packet-b02-registry.json'),m=J('data/project/counter-selector-wave-07-release-manifest.json'),r=J('reports/core-thesis/counter-selector-wave-07/data.json'),h=T('reports/core-thesis/counter-selector-wave-07/index.html');check(c,s,a,p);assert.deepEqual(a,acquisition(c));assert.deepEqual(p,packets(c));assert.deepEqual(m,manifest());assert.deepEqual(r,report(c,s,a,p,m));assert.equal(h,html(r));assert.equal(m.entries.length,9);assert.equal(r.counts.adversarial_mutations,30);assert.ok(h.includes('4 BLIND PACKETS · 0 FIELD TESTS'));console.log('validate-wave07 PASS',m.combined_sha256)}if(process.argv[1]===fileURLToPath(import.meta.url))validate();
'''
W('tools/validate-counter-selector-wave-07.mjs',validate)
test=r'''#!/usr/bin/env node
import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{acquisition,packets}from'../tools/build-counter-selector-wave-07.mjs';import{check}from'../tools/validate-counter-selector-wave-07.mjs';const R=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),J=p=>JSON.parse(fs.readFileSync(path.join(R,p),'utf8')),Q=x=>structuredClone(x),c0=J('data/project/counter-selector-wave-07-batch-02.json'),s0=J('data/project/counter-selector-wave-07-source-registry.json');const M=[(c,s,a,p)=>a.counts.qualifying_acquisitions++,(c,s,a,p)=>a.counts.partial_acquisitions--,(c,s,a,p)=>a.records[0].blind_packet_ready=true,(c,s,a,p)=>a.records[0].field_test_eligible=true,(c,s,a,p)=>a.records[2].operator_finding=true,(c,s,a,p)=>a.records[2].promotion_generated=true,(c,s,a,p)=>a.records[2].person_ranking_generated=true,(c,s,a,p)=>a.records[2].graph_effect='edge',(c,s,a,p)=>a.records[2].public_identity_release_authorized=true,(c,s,a,p)=>a.records[2].source_ids=['bad'],(c,s,a,p)=>s.sources.push(Q(s.sources[0])),(c,s,a,p)=>s.sources.pop(),(c,s,a,p)=>p.packets.pop(),(c,s,a,p)=>p.packets[0].attribution_class='system_mechanism',(c,s,a,p)=>p.packets[2].attribution_class='person_attributable',(c,s,a,p)=>p.packets[0].identity_removed=false,(c,s,a,p)=>p.packets[0].status_cues_removed=false,(c,s,a,p)=>p.packets[0].source_ids_removed=false,(c,s,a,p)=>p.packets[0].denominator_class_removed=false,(c,s,a,p)=>p.packets[0].blind_review_executed=true,(c,s,a,p)=>p.packets[0].field_test_authorized=true,(c,s,a,p)=>p.packets[0].operator_finding=true,(c,s,a,p)=>p.packets[0].graph_effect='edge',(c,s,a,p)=>p.packets[0].requirements=[],(c,s,a,p)=>p.packets[0].bounded_chronology=[],(c,s,a,p)=>p.packets[0].counterevidence=[],(c,s,a,p)=>c.boundaries.official_summary_is_original_work_object=true,(c,s,a,p)=>c.boundaries.catastrophe_after_denied_evidence_is_person_operator_finding=true,(c,s,a,p)=>c.boundaries.policy_authority_is_observed_partnership_repair=true,(c,s,a,p)=>c.boundaries.field_test_authorized=true];let n=0;for(let f of M){let c=Q(c0),s=Q(s0),a=acquisition(c),p=packets(c);f(c,s,a,p);assert.throws(()=>check(c,s,a,p));n++}assert.equal(n,30);console.log('wave07 mutations PASS',n);
'''
W('test/counter-selector-wave-07.test.js',test)
os.system('node tools/build-counter-selector-wave-07.mjs')
