import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { b32Id, canonicalize, entityId, claimId, _internal } from '../tools/lib/axm-id.mjs';

// base32 alphabet basics (shared by both envelopes).
assert.equal(_internal.base32LowerNoPad(Buffer.from([])), '');
assert.equal(_internal.base32LowerNoPad(Buffer.from([0x00])), 'aa');
assert.equal(_internal.base32LowerNoPad(Buffer.from([0xff])), '74');
// "foobar" RFC 4648 base32 is MZXW6YTBOI (upper); lowercased here.
assert.equal(_internal.base32LowerNoPad(Buffer.from('foobar', 'utf8')), 'mzxw6ytboi');

// ── RECONCILED genesis identity (CN-P0-1, BUILD-INSTRUCTIONS.md §2.1) ───────
// Shape: versioned prefix + full 32-byte digest = exactly 52 base32 chars.
assert.match(entityId('uk-ai-policy', 'Ben Warner'), /^e1_[a-z2-7]{52}$/,
  'entity id must be e1_ + 52 base32 chars (full digest, never truncated)');

// canonicalize() parity boundaries (spec §10.1).
assert.equal(canonicalize('  Hello  World  '), 'hello world');
assert.equal(canonicalize('Tab\tand\nNewline'), 'tabandnewline',
  'tab and newline are category Cc: stripped, not whitespace');
assert.equal(canonicalize('Straße'), 'straße',
  'ASCII-only lowering: sharp s is never expanded to ss');
assert.equal(canonicalize('İstanbul'), 'İstanbul',
  'U+0130 is not ASCII I: survives unchanged');
assert.equal(canonicalize('a  b'), 'a b',
  'frozen whitespace set collapses to one ASCII space');
assert.throws(() => canonicalize('a\x00b'), /NUL/,
  'NUL is the preimage separator and is illegal in input');

// The shared reconciliation fixture — generated by the axm-genesis reference
// kernel (axm_verify.identity) and committed byte-identically to both repos
// (genesis: tests/vectors/identity-reconciliation-clifford.json). Every id
// must reproduce here; any mismatch is a reconciliation break, not a skew to
// paper over.
const fixtureBytes = readFileSync(new URL('./fixtures/axm-identity-reconciliation.json', import.meta.url));
assert.equal(createHash('sha256').update(fixtureBytes).digest('hex'),
  'b35fe3625e3dd48859f8a13d19daf8e03522ffd6dfb3d135e614ce441a79518a',
  'fixture bytes must match axm-genesis commit 74db57b32ca5c02c7d340aa6caa25df993818667');
const fixture = JSON.parse(fixtureBytes.toString('utf8'));
assert.ok(fixture.entities.length >= 14 && fixture.claims.length >= 2,
  'fixture must retain its entity and claim coverage');
for (const row of fixture.entities) {
  assert.equal(canonicalize(row.namespace), row.canonical_namespace,
    `canonicalize(namespace) drift for ${JSON.stringify(row.namespace)}`);
  assert.equal(canonicalize(row.label), row.canonical_label,
    `canonicalize(label) drift for ${JSON.stringify(row.label)}`);
  assert.equal(entityId(row.namespace, row.label), row.entity_id,
    `entity_id drift for (${row.namespace}, ${JSON.stringify(row.label)})`);
}
for (const c of fixture.claims) {
  assert.equal(claimId(c.subject_id, c.predicate, c.object, c.object_type), c.claim_id,
    `claim_id drift for ${c.predicate}`);
}

// Insensitivity + namespace separation, now under the genesis scheme.
assert.equal(entityId('uk-ai-policy', 'ben warner'), entityId('uk-ai-policy', '  Ben Warner  '),
  'entity id must be case- and whitespace-insensitive on the label');
assert.notEqual(entityId('uk-ai-policy', 'Ben Warner'), entityId('other-case', 'Ben Warner'),
  'namespace must affect the entity id');
// The 0x00 separator means (ns, label) cannot collide across the boundary.
assert.notEqual(entityId('ab', 'c'), entityId('a', 'bc'),
  'NUL separator must prevent namespace/label boundary collisions');

// ── LEGACY envelope (pre-reconciliation, in-repo history only) ──────────────
assert.match(b32Id('e', 'ben warner'), /^e_[a-z2-7]{24}$/,
  'legacy envelope stays prefix + 24 base32 chars');
assert.equal(b32Id('e', 'ben warner'), 'e_k5ki4qe57qegkr37d7fmvlm3',
  'legacy golden preserved so historical artifacts remain reproducible');

console.log('axm-id.test: OK');
