#!/usr/bin/env node
import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {acquisition,packets} from '../tools/build-counter-selector-wave-09.mjs';import {validateObject} from '../tools/validate-counter-selector-wave-09.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=r=>JSON.parse(fs.readFileSync(path.join(root,r),'utf8'));const baseC=read('data/project/counter-selector-wave-09-batch-03.json'),baseS=read('data/project/counter-selector-wave-09-source-registry.json');
const mutations=[
 c=>c.expected_counts.batch_objects=7,c=>c.expected_counts.qualifying_acquisitions=4,c=>c.expected_counts.partial_acquisitions=2,c=>c.expected_counts.blind_packets_ready=4,c=>c.expected_counts.operator_findings=1,c=>c.expected_counts.field_tests_executed=1,c=>c.expected_counts.person_rankings=1,c=>c.expected_counts.graph_effects=1,
 c=>c.records.pop(),c=>c.records[0].denominator_class=c.records[1].denominator_class,c=>c.records[0].source_packet_ids=[],c=>c.records[0].missing_receipts=[],c=>c.records[0].blind_packet_ready=false,c=>c.records[1].blind_packet_ready=true,c=>c.records[1].qualification='qualifying_for_blind_packet',c=>c.records[3].blind_packet_ready=true,c=>c.records[4].blind_packet_ready=true,
 c=>c.blind_packets.pop(),c=>c.blind_packets[0].identity_removed=false,c=>c.blind_packets[0].status_cues_removed=false,c=>c.blind_packets[0].source_ids_removed=false,c=>c.blind_packets[0].blind_review_executed=true,c=>c.blind_packets[0].field_test_authorized=true,c=>c.blind_packets[0].graph_effect='candidate_edge',
 c=>c.boundaries.catastrophe_is_operator_capacity=true,c=>c.boundaries.staff_report_is_independent_merits=true,c=>c.boundaries.policy_is_observed_use=true,c=>c.boundaries.external_correction_is_partnership_repair=true,c=>c.boundaries.field_test_authorized=true,c=>c.boundaries.graph_effect='candidate_edge'
];
let passed=0;for(const [idx,mutate] of mutations.entries()){const c=structuredClone(baseC),s=structuredClone(baseS);mutate(c);let failed=false;try{validateObject(c,s,acquisition(c,s),packets(c))}catch{failed=true}assert.equal(failed,true);passed++;}assert.equal(passed,30);console.log(`counter-selector-wave-09 adversarial mutations: PASS (${passed})`);
