#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { validateSource } from '../tools/validate-counter-selector-wave-32.mjs';

const source = JSON.parse(fs.readFileSync('data/project/counter-selector-wave-32-candidate-handoff-application.json','utf8'));
const clone = value => structuredClone(value);
const mutations = [
  ['boundary_01_retrospective_recipient_account_is_external_review', s => { s.boundaries.retrospective_recipient_account_is_external_review = true; }],
  ['boundary_02_handover_event_acknowledgment_is_complete_package_acknowledgment', s => { s.boundaries.handover_event_acknowledgment_is_complete_package_acknowledgment = true; }],
  ['boundary_03_single_file_project_scope_is_complete_state_inventory', s => { s.boundaries.single_file_project_scope_is_complete_state_inventory = true; }],
  ['boundary_04_incoming_success_is_outgoing_package_proof', s => { s.boundaries.incoming_success_is_outgoing_package_proof = true; }],
  ['boundary_05_maintainer_authority_transfer_is_credential_inventory', s => { s.boundaries.maintainer_authority_transfer_is_credential_inventory = true; }],
  ['boundary_06_successor_releases_are_complete_direct_handoff', s => { s.boundaries.successor_releases_are_complete_direct_handoff = true; }],
  ['boundary_07_founder_independent_continuation_is_founder_handoff', s => { s.boundaries.founder_independent_continuation_is_founder_handoff = true; }],
  ['boundary_08_open_code_and_team_growth_are_complete_service_state', s => { s.boundaries.open_code_and_team_growth_are_complete_service_state = true; }],
  ['boundary_09_outgoing_offer_to_help_is_recipient_acknowledgment', s => { s.boundaries.outgoing_offer_to_help_is_recipient_acknowledgment = true; }],
  ['boundary_10_institutional_continuity_is_direct_person_handoff', s => { s.boundaries.institutional_continuity_is_direct_person_handoff = true; }],
  ['boundary_11_existing_custody_refinement_is_new_support', s => { s.boundaries.existing_custody_refinement_is_new_support = true; }],
  ['boundary_12_candidate_handoff_application_is_external_review', s => { s.boundaries.candidate_handoff_application_is_external_review = true; }],
  ['boundary_13_bounded_custody_support_is_complete_operator', s => { s.boundaries.bounded_custody_support_is_complete_operator = true; }],
  ['boundary_14_support_count_is_rank', s => { s.boundaries.support_count_is_rank = true; }],
  ['boundary_15_living_person_is_contact_authorization', s => { s.boundaries.living_person_is_contact_authorization = true; }],
  ['boundary_16_field_test_authorized', s => { s.boundaries.field_test_authorized = true; }],
  ['boundary_17_promotion_authorized', s => { s.boundaries.promotion_authorized = true; }],
  ['boundary_18_person_ranking_authorized', s => { s.boundaries.person_ranking_authorized = true; }],
  ['boundary_19_public_identity_profile_authorized', s => { s.boundaries.public_identity_profile_authorized = true; }],
  ['complete_handoff_count', s => { s.counts.complete_direct_handoffs = 1; }],
  ['package_receipt_count', s => { s.counts.recipient_acknowledged_state_packages = 1; }],
  ['external_review_count', s => { s.counts.external_independent_reviews = 1; }],
  ['operator_count', s => { s.counts.complete_operator_findings = 1; }],
  ['field_test_count', s => { s.counts.field_test_eligible_candidates = 1; }],
  ['contact_count', s => { s.counts.contacts_authorized = 1; }],
  ['rank_count', s => { s.counts.person_rankings = 1; }],
  ['graph_count', s => { s.counts.graph_effects = 1; }],
  ['wrong_lane_count', s => { s.counts.candidate_lanes_audited = 5; }],
  ['wrong_source_count', s => { s.counts.public_source_records = 18; }],
  ['wrong_support_addition_count', s => { s.counts.person_custody_supports_added = 2; }],
  ['wrong_mutation_count', s => { s.counts.adversarial_mutations = 79; }],
  ['daniel_no_support', s => { s.candidate_lanes[0].adjudication.person_custody_support_added = false; }],
  ['daniel_complete_handoff', s => { s.candidate_lanes[0].adjudication.direct_state_handoff = 'established'; }],
  ['daniel_contact', s => { s.candidate_lanes[0].contact_authorized = true; }],
  ['daniel_operator', s => { s.candidate_lanes[0].adjudication.complete_operator_finding = true; }],
  ['daniel_field_test', s => { s.candidate_lanes[0].adjudication.field_test_eligible = true; }],
  ['daniel_drop_custody', s => { s.candidate_lanes[0].current_person_supports = ['model_elasticity','epistemic_restraint']; }],
  ['daniel_inflate_support', s => { s.candidate_lanes[0].current_person_supports.push('governed_capacity'); }],
  ['daniel_package_ack', s => { s.candidate_lanes[0].recipient_acknowledgment_level = 'complete_state_package_acknowledged'; }],
  ['simon_add_custody', s => { s.candidate_lanes[1].adjudication.person_custody_support_added = true; }],
  ['simon_change_vector', s => { s.candidate_lanes[1].current_person_supports.push('custody'); }],
  ['simon_complete_handoff', s => { s.candidate_lanes[1].adjudication.direct_state_handoff = 'established'; }],
  ['simon_operator', s => { s.candidate_lanes[1].adjudication.complete_operator_finding = true; }],
  ['troy_add_custody', s => { s.candidate_lanes[2].adjudication.person_custody_support_added = true; }],
  ['troy_change_vector', s => { s.candidate_lanes[2].current_person_supports.push('custody'); }],
  ['troy_complete_handoff', s => { s.candidate_lanes[2].adjudication.direct_state_handoff = 'established'; }],
  ['troy_contact', s => { s.candidate_lanes[2].contact_authorized = true; }],
  ['richardson_new_custody', s => { s.candidate_lanes[3].adjudication.person_custody_support_added = true; }],
  ['richardson_change_vector', s => { s.candidate_lanes[3].current_person_supports.push('support_adjusted_surplus'); }],
  ['richardson_complete_handoff', s => { s.candidate_lanes[3].adjudication.direct_state_handoff = 'established'; }],
  ['richardson_operator', s => { s.candidate_lanes[3].adjudication.complete_operator_finding = true; }],
  ['duplicate_lane_id', s => { s.candidate_lanes[1].lane_id = s.candidate_lanes[0].lane_id; }],
  ['wrong_identity_order', s => { [s.candidate_lanes[0],s.candidate_lanes[1]]=[s.candidate_lanes[1],s.candidate_lanes[0]]; }],
  ['remove_lane', s => { s.candidate_lanes.pop(); }],
  ['add_lane', s => { s.candidate_lanes.push(structuredClone(s.candidate_lanes[0])); }],
  ['duplicate_source_id', s => { s.candidate_lanes[1].source_records[0].source_id = s.candidate_lanes[0].source_records[0].source_id; }],
  ['remove_source', s => { s.candidate_lanes[0].source_records.pop(); s.counts.public_source_records = 16; }],
  ['wrong_schema', s => { s.schema_version = 'bad'; }],
  ['wrong_wave', s => { s.wave_id = 'CS-W32-BAD'; }],
  ['wrong_status', s => { s.status = 'complete_operator'; }],
  ['graph_effect', s => { s.graph_effect = 'candidate_edge'; }],
  ['external_claim', s => { s.review_independence.external_human_independence_claimed = true; }],
  ['different_model_claim', s => { s.review_independence.different_model_or_institution_claimed = true; }],
  ['same_system_removed', s => { s.review_independence.same_system_limitation_preserved = false; }],
  ['contract_contact', s => { s.handoff_contract.contact_required = true; }],
  ['contract_promotion', s => { s.handoff_contract.candidate_application_is_promotion = true; }],
  ['component_removed', s => { delete s.candidate_lanes[0].components.rollback_and_safe_decline_conditions; }],
  ['counterevidence_short', s => { s.candidate_lanes[0].counterevidence = ['x']; }],
  ['falsifier_short', s => { s.candidate_lanes[0].falsifiers = ['x']; }],
  ['bad_dimension', s => { s.candidate_lanes[0].current_person_supports.push('genius'); }],
  ['duplicate_dimension', s => { s.candidate_lanes[0].current_person_supports.push('custody'); }],
  ['bad_recipient_level', s => { s.candidate_lanes[0].recipient_acknowledgment_level = 'complete'; }],
  ['lane_graph', s => { s.candidate_lanes[0].graph_effect = 'edge'; }],
  ['lane_external', s => { s.candidate_lanes[0].review.external_independence_claimed = true; }],
  ['simon_classification', s => { s.candidate_lanes[1].adjudication.classification = 'person_custody'; }],
  ['troy_classification', s => { s.candidate_lanes[2].adjudication.classification = 'complete_service_handoff'; }],
  ['richardson_classification', s => { s.candidate_lanes[3].adjudication.classification = 'new_custody_support'; }],
  ['daniel_successor_missing', s => { s.candidate_lanes[0].components.successor_action = 'not_observed'; }],
  ['daniel_inventory_inflated', s => { s.candidate_lanes[0].components.open_decision_and_dependency_inventory = 'complete'; }],
  ['wrong_ack_count', s => { s.counts.recipient_handover_acknowledgment_events = 2; }],
];

assert.equal(mutations.length, 80);
for (const [name, mutate] of mutations) {
  const candidate = clone(source);
  mutate(candidate);
  assert.throws(() => validateSource(candidate), undefined, `mutation must fail: ${name}`);
}
console.log(`counter-selector-wave-32.test: ${mutations.length} adversarial mutations refused`);
