import assert from 'node:assert/strict';
import fs from 'node:fs';
import { renderEstateAperture } from '../tools/render-estate-aperture.mjs';

const first = renderEstateAperture();
const second = renderEstateAperture({ write: false });
assert.equal(second.html, first.html, 'Estate Aperture render must be deterministic');
assert.equal(first.data.estates.length, 14);
assert.equal(first.data.corridors.length, 34);
assert.match(first.html, /Estate Aperture/);
assert.match(first.html, /Four semantic levels/);
assert.match(first.html, /Closing the fan-out pass does not complete an estate/);
assert.match(first.html, /data-estate-aperture-schema="estate-aperture-data@1"/);
assert.match(first.html, /data-graph-effect="none"/);
assert.match(first.html, /estate-aperture-export@1/);
assert.match(first.html, /Shared source infrastructure/);
assert.match(first.html, /prefers-reduced-motion/);
assert.match(first.html, /forced-colors/);
assert.doesNotMatch(first.html, /<script[^>]+src=/);
assert.doesNotMatch(first.html, /<link[^>]+stylesheet/);
assert.equal(fs.readFileSync('estates/index.html', 'utf8'), first.html);
console.log('estate-aperture.test: OK');
