#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';import {validateWave08} from '../tools/validate-k0-role-neutral-wave-08.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const run=args=>{const r=spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});if(r.status!==0)throw new Error(`${args.join(' ')} failed\n${r.stdout}\n${r.stderr}`)};run(['tools/build-k0-role-neutral-wave-08.mjs']);let result=validateWave08({root});assert.equal(result.ok,true,result.failures.join('\n'));
const wave=JSON.parse(fs.readFileSync(path.join(root,'data/research/k0-role-neutral-wave-08.json'),'utf8'));const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'k0-w08-'));const wr=(n,v)=>{const f=path.join(tmp,n);fs.writeFileSync(f,JSON.stringify(v,null,2)+'\n');return path.relative(root,f).replaceAll('\\','/')};
let x=structuredClone(wave);x.query_executions[0].query_text+=' David Iglesias';result=validateWave08({root,wavePath:wr('name.json',x)});assert.equal(result.ok,false);assert.ok(result.failures.some(v=>v.includes('named target leaked')));
x=structuredClone(wave);x.records[0].included_event=true;result=validateWave08({root,wavePath:wr('event.json',x)});assert.equal(result.ok,false);assert.ok(result.failures.some(v=>v.includes('promotion')));
x=structuredClone(wave);x.records[5].selection_outcome='candidate_requires_field_audit';result=validateWave08({root,wavePath:wr('control.json',x)});assert.equal(result.ok,false);assert.ok(result.failures.some(v=>v.includes('selection outcome')));
x=structuredClone(wave);x.boundaries.investigation_rationale_proves_merits=true;result=validateWave08({root,wavePath:wr('merits.json',x)});assert.equal(result.ok,false);assert.ok(result.failures.some(v=>v.includes('boundaries')));
const report=JSON.parse(fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/k0-role-neutral-wave-08.json'),'utf8'));assert.equal(report.counts.retained_records,8);assert.equal(report.counts.candidate_requires_field_audit,4);assert.equal(report.current_result.full_frozen_search_battery_executed,true);assert.equal(report.current_result.included_events,0);const html=fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/k0-role-neutral-wave-08.html'),'utf8');assert.match(html,/WAVE 08/);assert.doesNotMatch(html,/WAVE 07/);console.log('k0-role-neutral-wave-08.test: OK');
