#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { validateWave03 } from '../tools/validate-k0-role-neutral-wave-03.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const run = args => { const result = spawnSync(process.execPath, args, { cwd: root, encoding: 'utf8' }); if (result.status !== 0) throw new Error(`${args.join(" ")} failed\n${result.stdout}\n${result.stderr}`); };
run(['tools/build-k0-role-neutral-wave-03.mjs']);
let result = validateWave03({ root }); assert.equal(result.ok, true, result.failures.join('\n'));
const wave = JSON.parse(fs.readFileSync(path.join(root, 'data/research/k0-role-neutral-wave-03.json'), 'utf8'));
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'k0-wave03-'));
const write = (name, value) => { const file = path.join(tmp, name); fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n'); return path.relative(root, file); };
const named = structuredClone(wave); named.query_executions[0].query_text += ' Challenger'; result = validateWave03({ root, wavePath: write('named.json', named) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('named target leaked')));
const graph = structuredClone(wave); graph.records[0].graph_effect = 'create_hop'; result = validateWave03({ root, wavePath: write('graph.json', graph) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('publication or graph boundary')));
const promoted = structuredClone(wave); promoted.records[0].included_event = true; promoted.records[0].ccd_chain_depth = 7; result = validateWave03({ root, wavePath: write('promoted.json', promoted) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('discovery promoted')));
const consequence = structuredClone(wave); consequence.boundaries.material_consequence_proves_reclassification = true; result = validateWave03({ root, wavePath: write('consequence.json', consequence) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('wave boundaries drift')));
const count = structuredClone(wave); count.counts.candidate_requires_field_audit = 6; result = validateWave03({ root, wavePath: write('count.json', count) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('count drift')));
const weakExclusion = structuredClone(wave); weakExclusion.excluded_results[0].reason = 'duplicate'; result = validateWave03({ root, wavePath: write('exclude.json', weakExclusion) }); assert.equal(result.ok, false); assert.ok(result.failures.some(row => row.includes('weak exclusion reason')));
console.log('k0-role-neutral-wave-03.test: OK');
