#!/usr/bin/env node
import assert from 'node:assert/strict';
import {
  loadState,
  validateState
} from '../tools/validate-lake-allocator-war-join-requirements-wave-35.mjs';

const baseline = loadState();
validateState(baseline, { skipAncestry: true });
const clone = value => structuredClone(value);
const mutations = [];
const add = (name, mutate) => mutations.push({ name, mutate });
const firstPath = state => Object.keys(state.queueRowsByPath).sort()[0];
const firstQueue = state => state.queueRowsByPath[firstPath(state)].find(row => row.row_type === 'lawful_join_requirement_queue');
const firstTask = state => state.queueRowsByPath[firstPath(state)].find(row => row.row_type === 'lawful_join_requirement_acquisition_task');
const protectedTask = state => Object.values(state.queueRowsByPath).flat().find(row => row.access_class === 'authorized_lawful_access_only');
const firstProjectedTask = state => state.projection.tasks[0];

add('policy schema drift', state => { state.policy.schema_version = 'bad'; });
add('program reference drift', state => { state.policy.program_ref = 'BAD'; });
add('wave reference drift', state => { state.policy.wave_ref = 'BAD'; });
add('source policy schema drift', state => { state.sourcePolicy.schema_version = 'bad'; });
add('source projection schema drift', state => { state.sourceProjection.schema_version = 'bad'; });
add('source join count drift', state => { state.policy.source_contract.lawful_join_contracts = 8; });
add('source requirement count drift', state => { state.policy.source_contract.missing_institutional_requirements = 30; });
add('expected task count drift', state => { state.policy.expected_counts.acquisition_tasks = 30; });
add('expected ready count drift', state => { state.policy.expected_counts.execution_ready_tasks = 27; });
add('expected access-class drift', state => { state.policy.expected_counts.access_classes.public_or_authorized_acquisition = 24; });
add('duplicate access lane reference', state => { state.policy.access_lanes[1].lane_ref = state.policy.access_lanes[0].lane_ref; });
add('duplicate access class', state => { state.policy.access_lanes[1].access_class = state.policy.access_lanes[0].access_class; });
add('protected lane made ready', state => { state.policy.access_lanes[2].execution_ready = true; });
add('protected lane unbounded', state => { state.policy.access_lanes[2].access_bounded = false; });
add('source join removed', state => { state.sourceJoinRows.pop(); });
add('source join duplicated', state => { state.sourceJoinRows[1].join_ref = state.sourceJoinRows[0].join_ref; });
add('source route duplicated', state => { state.sourceJoinRows[1].route_ref = state.sourceJoinRows[0].route_ref; });
add('source join sequence drift', state => { state.sourceJoinRows[0].join_sequence = 9; });
add('source join authorized', state => { state.sourceJoinRows[0].join_authorized = true; });
add('source joined rows inflated', state => { state.sourceJoinRows[0].joined_rows = 1; });
add('source denominator completed', state => { state.sourceJoinRows[0].complete_denominator = true; });
add('source requirement satisfied', state => { state.sourceJoinRows[0].missing_requirements[0].satisfied = true; });
add('source requirement removed', state => { state.sourceJoinRows[0].missing_requirements.pop(); });
add('source requirement duplicated', state => { state.sourceJoinRows[0].missing_requirements[1].requirement_ref = state.sourceJoinRows[0].missing_requirements[0].requirement_ref; });
add('source access class invalid', state => { state.sourceJoinRows[0].missing_requirements[0].access_class = 'unbounded'; });
add('source route class drift', state => { state.sourceJoinRows[0].route_class = 'wrong'; });
add('source owner drift', state => { state.sourceJoinRows[0].route_owner = 'wrong'; });
add('source receipt set drift', state => { state.sourceJoinRows[0].source_refs.pop(); });
add('source adapter set drift', state => { state.sourceJoinRows[0].adapter_refs.pop(); });
add('source key set drift', state => { state.sourceJoinRows[0].candidate_key_classes.pop(); });
add('source ledger raw drift', state => { state.sourceJoinRaw += ' '; });
add('source projection join removed', state => { state.sourceProjection.lawful_join_contracts.pop(); });
add('source projection graph digest drift', state => { state.sourceProjection.graph_digests.hop_edges_sha256 = '0'.repeat(64); });
add('source projection authorized joins inflated', state => { state.sourceProjection.counts.authorized_joins = 1; });
add('queue ledger path removed', state => { delete state.queueRowsByPath[firstPath(state)]; });
add('queue raw path removed', state => { delete state.queueRawByPath[firstPath(state)]; });
add('queue summary removed', state => { state.queueRowsByPath[firstPath(state)].shift(); });
add('task removed', state => { state.queueRowsByPath[firstPath(state)].pop(); });
add('duplicate task reference', state => { const rows=state.queueRowsByPath[firstPath(state)].filter(row=>row.row_type==='lawful_join_requirement_acquisition_task'); rows[1].task_ref=rows[0].task_ref; });
add('task sequence drift', state => { firstTask(state).task_sequence = 99; });
add('task queue reference drift', state => { firstTask(state).queue_ref = 'LAW35-Q999'; });
add('task join reference drift', state => { firstTask(state).source_join_ref = 'LAW34-J999'; });
add('task requirement reference drift', state => { firstTask(state).source_requirement_ref = 'LAW34-R999'; });
add('task route reference drift', state => { firstTask(state).source_route_ref = 'LAW30-R99'; });
add('task route class drift', state => { firstTask(state).source_route_class = 'wrong'; });
add('task owner drift', state => { firstTask(state).source_route_owner = 'wrong'; });
add('task access class drift', state => { firstTask(state).access_class = 'authorized_lawful_access_only'; });
add('task lane reference drift', state => { firstTask(state).execution_lane_ref = 'LAW35-L99'; });
add('task execution state drift', state => { firstTask(state).execution_state = 'wrong'; });
add('task readiness drift', state => { firstTask(state).execution_ready = false; });
add('task access-bound drift', state => { firstTask(state).access_bounded = true; });
add('task protected flag drift', state => { firstTask(state).protected_lawful_access_only = true; });
add('protected task made ready', state => { protectedTask(state).execution_ready = true; });
add('protected task made public', state => { protectedTask(state).access_bounded = false; });
add('task target row drift', state => { firstTask(state).target_row = 'wrong'; });
add('task completion test drift', state => { firstTask(state).completion_test = 'wrong'; });
add('task refused substitution drift', state => { firstTask(state).refused_substitution = 'wrong'; });
add('task source receipts drift', state => { firstTask(state).source_refs.pop(); });
add('task adapter refs drift', state => { firstTask(state).adapter_refs.pop(); });
add('task candidate keys drift', state => { firstTask(state).candidate_key_classes.pop(); });
add('task source use count drift', state => { firstTask(state).source_receipt_use_count += 1; });
add('task adapter use count drift', state => { firstTask(state).schema_adapter_use_count += 1; });
add('task key use count drift', state => { firstTask(state).candidate_key_class_use_count += 1; });
add('task source join hash drift', state => { firstTask(state).source_join_row_sha256 = '0'.repeat(64); });
add('task source requirement hash drift', state => { firstTask(state).source_requirement_sha256 = '0'.repeat(64); });
add('task state drift', state => { firstTask(state).task_state = 'complete'; });
add('same-wave acquisition result inflation', state => { firstTask(state).same_wave_acquisition_result = true; });
add('requirement satisfaction inflation', state => { firstTask(state).requirement_satisfied = true; });
add('task admission join authority inflation', state => { firstTask(state).task_admission_authorizes_join = true; });
add('join authority inflation', state => { firstTask(state).join_authorized = true; });
add('joined rows inflation', state => { firstTask(state).joined_rows = 1; });
add('complete denominator inflation', state => { firstTask(state).complete_denominator = true; });
add('evidence adjudication inflation', state => { firstTask(state).evidence_adjudicated = true; });
add('evidence row inflation', state => { firstTask(state).evidence_rows = 1; });
add('estate adoption inflation', state => { firstTask(state).estate_adopted = true; });
add('finding promotion inflation', state => { firstTask(state).finding_promoted = true; });
add('graph effect inflation', state => { firstTask(state).graph_effect = 'created'; });
add('publication inflation', state => { firstTask(state).publication_status = 'cleared'; });
add('blocked promotion removed', state => { firstTask(state).blocked_promotions.pop(); });
add('queue task count drift', state => { firstQueue(state).task_count -= 1; });
add('queue access count drift', state => { firstQueue(state).requirement_access_classes.public_or_authorized_acquisition -= 1; });
add('queue result hash drift', state => { state.projection.queues[0].result_sha256 = '0'.repeat(64); });
add('projection task count drift', state => { state.projection.counts.acquisition_tasks = 30; });
add('projection graph digest drift', state => { state.projection.graph_digests.participation_sha256 = '0'.repeat(64); });
add('projected task drift', state => { firstProjectedTask(state).target_row = 'wrong'; });
add('manual dispatch reintroduced', state => { state.projection.amortization_contract.manual_per_task_dispatch_required = true; });
add('network request inflation', state => { state.projection.execution_contract.network_requests_performed = 1; });
add('protected public execution inflation', state => { state.projection.execution_contract.protected_tasks_publicly_executable = true; });
add('task authority contract inflation', state => { state.projection.execution_contract.task_admission_authorizes_join = true; });
add('sensitive token path leakage', state => { firstTask(state).leaked = '$.token'; });
add('policy evidence boundary inflation', state => { state.policy.boundaries.requirement_task_is_evidence_row = true; });
add('policy protected substitution inflation', state => { state.policy.boundaries.public_aggregate_satisfies_protected_personnel = true; });
add('Wave 35 authoritative root removed', state => { state.lakeIndexPolicy.authoritative_roots = state.lakeIndexPolicy.authoritative_roots.filter(item => item !== state.policy.paths.projection); });
add('Wave 35 source basin path removed', state => { const basin=state.wave21Policy.basin_contract.find(row=>row.basin_id==='allocator-war-source'); basin.path_prefixes=basin.path_prefixes.filter(item=>item!==state.policy.paths.method); });
add('Wave 35 basin registry mismatch', state => { const basin=state.basinRegistry.basins.find(row=>row.basin_id==='allocator-war-reports'); basin.path_prefixes=[]; });
add('Wave 35 generated path removed', state => { state.wave21Policy.projection_contract.allowed_generated_paths=state.wave21Policy.projection_contract.allowed_generated_paths.filter(item=>item!==state.policy.paths.projection); });
add('Wave 35 boundary removed from Wave 21', state => { delete state.wave21Policy.boundaries.wave_35_requirement_task_is_evidence_row; });
add('Wave 35 lake-index boundary inflation', state => { state.lakeIndexPolicy.boundaries.allocator_war_wave_35_requirement_task_is_evidence = true; });
add('Wave 35 basin boundary inflation', state => { state.basinRegistry.boundaries.allocator_war_wave_35_task_is_join_authority = true; });
add('Wave 35 build script removed', state => { delete state.packageJson.scripts['build:lake-allocator-war-join-requirements-wave-35']; });
add('Wave 35 release ordering removed', state => { state.packageJson.scripts.check=state.packageJson.scripts.check.replace(' && npm run validate:lake-allocator-war-join-requirements-wave-35',''); });
add('Wave 35 installer registration removed', state => { state.installer=state.installer.replaceAll('lake-allocator-war-join-requirements-wave-35-policy.json','removed-policy.json'); });
add('Wave 35 Wave 21 validator registration removed', state => { state.wave21Validator=state.wave21Validator.replaceAll('allocator-war-join-requirements-wave-35.json','removed-wave35.json'); });
add('Wave 35 workflow release gate removed', state => { state.workflow=state.workflow.replace('Run complete repository release gate','Removed gate'); });
add('Wave 35 README marker removed', state => { state.readme=state.readme.replace('## Allocator-war lawful join requirement fan-out Wave 35',''); });
add('Wave 35 build marker removed', state => { state.buildInstructions=state.buildInstructions.replace('3.35 **Allocator-war lawful join requirement fan-out — Wave 35.**',''); });
add('temporary transport survives', state => { state.temporaryPathsPresent=['.github/tmp/wave35-tree-export-trigger.json']; });
add('report drift', state => { state.report += '\nmutated\n'; });

assert.ok(mutations.length >= 100, `expected at least 100 adversarial mutations, observed ${mutations.length}`);
for (const { name, mutate } of mutations) {
  const state = clone(baseline);
  mutate(state);
  assert.throws(() => validateState(state, { skipAncestry: true }), undefined, name);
}

console.log(`allocator-war lawful join requirement fan-out Wave 35 adversarial mutations passed: ${mutations.length}`);
