import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=path=>JSON.parse(fs.readFileSync(path,'utf8'));
const method=read('data/project/m04e-constitutional-awareness-methodology.json');
const wave=read('data/intake/m04e-constitutional-awareness-estate-wave-01.json');
const estate=read('data/project/m04e-constitutional-awareness-estate.json');
const report=read('reports/core-thesis/constitutional-awareness/data.json');
const byId=new Map(wave.records.map(x=>[x.record_id,x]));
assert.equal(wave.records.length,33);
assert.equal(wave.subjects.length,31);
assert.equal(wave.source_registry.length,27);
assert.equal(estate.system_chains.length,6);
assert.equal(estate.counts.represented_records_with_direct_subject_voice,0);
assert.ok(estate.counts.by_position['O3-operator-integrator']>estate.counts.by_position['K4-counter-sovereign']);
assert.ok(estate.counts.by_power['P1-voice-feedback-or-petition']>estate.counts.by_power['P4-compulsory-revision-reversal-or-termination']);
assert.ok(estate.counts.unpopulated_or_not_directly_assignable_classes.includes('C03-tacit-constitutional-carrier'));
assert.ok(estate.counts.unpopulated_or_not_directly_assignable_classes.includes('C10-aware-powerless-represented-subject'));
assert.equal(byId.get('M04E-CA-018').classification.effective_power_id,'P4-compulsory-revision-reversal-or-termination');
assert.equal(byId.get('M04E-CA-019').classification.effective_power_id,'P1-voice-feedback-or-petition');
assert.equal(byId.get('M04E-CA-020').classification.constitutional_position_ids.includes('K4-counter-sovereign'),false);
assert.deepEqual(byId.get('M04E-CA-028').classification.class_ids,['C17-constitutionally-subordinate-resource-provider']);
assert.ok(byId.get('M04E-CA-031').classification.class_ids.includes('C04-aware-accommodator'));
assert.equal(byId.get('M04E-CA-032').classification.effective_power_id,'P3-gate-veto-or-collective-leverage');
assert.equal(byId.get('M04E-CA-033').classification.material_relation_ids.includes('M11-transition-or-exit-provider'),true);
assert.equal(report.source_fingerprint.length,64);
assert.equal(method.boundaries.position_proves_awareness,false);
assert.equal(estate.boundaries.represented_status_proves_unawareness_or_consent,false);
console.log('m04e-constitutional-awareness.test: OK');
