#!/usr/bin/env node
import assert from 'node:assert/strict';import {evaluateAdoptionPackage} from '../tools/m05-adoption-conformance.mjs';
const clone=(v)=>JSON.parse(JSON.stringify(v));const H='a'.repeat(64);const receipt=(uri='urn:test:receipt')=>({observed:true,evidence_uri:uri,observed_at:'2026-07-26',scope_fingerprint:H});
const base={schema_version:'apc-adoption-package@2',package_id:'TEST-A0',reference:{version:'APC-01-S05-A0',source_uri:'urn:test:source',public_boundary_uri:'urn:test:boundary',bundle_fingerprint:H,integrity_receipts:[{path:'reference.json',sha256:H,bytes:100}]},claim:{requested_level:'A0',as_of:'2026-07-27',deployment_mode:'published_reference',scope_fingerprint:H},independence:{self_attested:false,external_attestors:[]},reviews:{legal:{status:'not_observed'},privacy:{status:'not_observed'},ethics:{status:'not_observed'},technical:{status:'not_observed'}},affected_party:{approval_status:'not_observed',selection_independent:false,institution_or_vendor_controls_majority:false,recall_and_removal_enabled:false,nonretaliation_protection:false,direct_r1_r4_waiver_allowed:false},deployment:{mode:'published_reference',real_person_data:false,adverse_action_authority:false,recommendation_authority:false,influence_allowed:false,staff_consultation_allowed:false,entry_gate:{approved:false},material_update_since_approval:false,emergency_authority:{enabled:false}},stop_authority:{independent:false},evidence:{custodian:'public_repository',custody_instrument_uri:'urn:test:custody',vendor_exclusive:false,integrity_receipts:[{path:'reference.json',sha256:H,bytes:100}]},evaluation:{preregistered:false},successor:{inheritance_required:true},registry:{expires_at:'2027-01-27',re_review_date:'2026-10-27',open_blockers:[{blocker_id:'BLK-A1',status:'open',first_affected_level:'A1',reason:'No external reproduction.'}]},observations:{}};
let r=evaluateAdoptionPackage(base);assert.equal(r.conformant,true);assert.equal(r.computed_maximum_level,'A0');assert.equal(r.blocker_cap,'A0');
const boolA1=clone(base);boolA1.package_id='BOOL';boolA1.claim.requested_level='A1';boolA1.claim.deployment_mode='independent_reproduction';boolA1.deployment.mode='independent_reproduction';boolA1.independence.external_attestors=[{attestor_id:'x',relationship_disclosure:'none',signed_at:'2026-07-26',expires_at:'2027-01-01',evidence_uri:'urn:a',scope_fingerprint:H,self:false}];boolA1.observations.independent_reproduction=true;r=evaluateAdoptionPackage(boolA1);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='MISSING-OBSERVATION-RECEIPT'));
const blocker=clone(boolA1);blocker.package_id='BLOCKER';blocker.observations.independent_reproduction=receipt();r=evaluateAdoptionPackage(blocker);assert.equal(r.unblocked_maximum_level,'A1');assert.equal(r.computed_maximum_level,'A0');assert(r.errors.some((e)=>e.code==='OPEN-CRITICAL-BLOCKER'));
const stale=clone(blocker);stale.package_id='STALE';stale.registry.open_blockers=[];stale.independence.external_attestors[0].expires_at='2026-07-26';r=evaluateAdoptionPackage(stale);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='NO-CURRENT-SCOPED-ATTESTOR'));
const mismatch=clone(base);mismatch.package_id='MODE';mismatch.deployment.mode='no_adverse_shadow';r=evaluateAdoptionPackage(mismatch);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='CLAIM-DEPLOYMENT-MODE-MISMATCH'));
const a3=clone(base);a3.package_id='A3';a3.claim.requested_level='A3';a3.claim.deployment_mode='no_adverse_shadow';a3.deployment.mode='no_adverse_shadow';a3.registry.open_blockers=[];a3.independence.external_attestors=[{attestor_id:'external',relationship_disclosure:'none',signed_at:'2026-07-26',expires_at:'2027-01-01',evidence_uri:'urn:attestor',scope_fingerprint:H,self:false}];for(const k of ['legal','privacy','ethics','technical'])a3.reviews[k]={status:'approved',authority:`${k}-authority`,reviewer_id:`${k}-reviewer`,approved_at:'2026-07-26',expires_at:'2027-01-01',evidence_uri:`urn:${k}`,independence_evidence_uri:`urn:${k}:independence`,scope_fingerprint:H};a3.affected_party={approval_status:'approved',selection_independent:true,institution_or_vendor_controls_majority:false,body_id:'body',formation_evidence_uri:'urn:formation',approval_evidence_uri:'urn:approval',conflict_register_uri:'urn:conflict',dissent_record_uri:'urn:dissent',recall_and_removal_enabled:true,nonretaliation_protection:true,direct_r1_r4_waiver_allowed:false,scope_fingerprint:H};Object.assign(a3.deployment,{real_person_data:true,entry_gate:{approved:true,authority:'entry',approved_at:'2026-07-26',expires_at:'2027-01-01',evidence_uri:'urn:entry',scope_fingerprint:H}});a3.stop_authority={independent:true,can_bind_operator:true,can_bind_institution:true,can_bind_vendor:true,can_bind_downstream_recipients:true,complete_evidence_access:true,evidence_uri:'urn:stop',approved_at:'2026-07-26',expires_at:'2027-01-01',scope_fingerprint:H};a3.evaluation={preregistered:true,metrics_frozen:true,denominators_frozen:true,stop_thresholds_frozen:true,analysis_plan_frozen:true,results_seen_before_freeze:false,preregistration_uri:'urn:pre',frozen_at:'2026-07-26',scope_fingerprint:H};for(const k of ['independent_reproduction','independent_review','lawful_shadow_period','shadow_adverse_action_boundary_preserved'])a3.observations[k]=receipt(`urn:${k}`);r=evaluateAdoptionPackage(a3);assert.equal(r.conformant,true);assert.equal(r.computed_maximum_level,'A3');assert.equal(r.truthfulness_determined,false);
const missingTechnical=clone(a3);missingTechnical.package_id='NO-TECH';missingTechnical.reviews.technical.status='not_observed';r=evaluateAdoptionPackage(missingTechnical);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='REVIEWS-NOT-CURRENT'));
const scopeMismatch=clone(a3);scopeMismatch.package_id='SCOPE';scopeMismatch.observations.independent_review.scope_fingerprint='b'.repeat(64);r=evaluateAdoptionPackage(scopeMismatch);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='MISSING-OBSERVATION-RECEIPT'));
const adverse=clone(a3);adverse.package_id='ADVERSE';adverse.deployment.staff_consultation_allowed=true;r=evaluateAdoptionPackage(adverse);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='ADVERSE-AUTHORITY-IN-NO-ADVERSE-MODE'));
const staleReview=clone(a3);staleReview.package_id='REREVIEW';staleReview.registry.re_review_date='2026-07-26';r=evaluateAdoptionPackage(staleReview);assert.equal(r.conformant,false);assert(r.errors.some((e)=>e.code==='STALE-RE-REVIEW'));
console.log('m05-adoption-conformance.test: OK');
