#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { computeReleaseManifest,releaseScope } from '../tools/build-m05-answerable-power-sprint-08.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(rel)=>JSON.parse(fs.readFileSync(path.join(root,rel),'utf8'));
const plan=read('data/project/m05-answerable-power-sprint-08-plan.json');
const constitution=read('data/project/m05-answerable-power-sprint-08-lifecycle-constitution.json');
const ledger=read('data/project/m05-answerable-power-sprint-08-support-ledger.json');
const scenarios=read('data/project/m05-answerable-power-sprint-08-scenarios.json');
const report=read('reports/core-thesis/answerable-power/sprint-08.json');
const manifest=read('data/project/m05-answerable-power-sprint-08-release-manifest.json');
assert.equal(plan.status,'protocol_complete_no_a1_entry');
assert.equal(plan.leg_registry.length,7);assert.ok(plan.leg_registry.every((r)=>r.protocol_complete&&!r.external_effect_observed));
assert.equal(constitution.roles.length,6);assert.equal(constitution.lifecycle_states.length,8);assert.equal(constitution.challenge_categories.length,10);assert.equal(constitution.automatic_support_loss_triggers.length,12);assert.equal(constitution.allowed_transitions.length,19);
assert.equal(scenarios.scenarios.length,24);assert.deepEqual(scenarios.denominator,{total:24,eligible_for_lifecycle_proposal:3,blocked:16,mandatory_pause:5});
assert.ok(Object.values(ledger.counts).every((value)=>value===0));assert.equal(ledger.verified_state.a1_observed,false);assert.equal(ledger.verified_state.maximum_verified_adoption_level,'A0');assert.equal(ledger.verified_state.real_person_pilot_authorized,false);
assert.equal(plan.current_result.a1_observed,false);assert.equal(plan.current_result.real_person_pilot_authorized,false);assert.equal(plan.current_result.project_complete,false);
assert.equal(releaseScope.length,17);assert.deepEqual(manifest,computeReleaseManifest());assert.equal(report.release_manifest.combined_sha256,manifest.combined_sha256);assert.equal(report.counts.a1_entries,0);
const before=fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/sprint-08.json'),'utf8');execFileSync(process.execPath,['tools/build-m05-answerable-power-sprint-08.mjs'],{cwd:root,stdio:'pipe'});const after=fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/sprint-08.json'),'utf8');assert.equal(after,before);
console.log('m05-answerable-power-sprint-08.test: OK');
