#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const run=(args)=>{const result=spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});if(result.status!==0){console.error(result.stdout);console.error(result.stderr);throw new Error(`${args.join(' ')} failed`)}return result.stdout};
run(['tools/build-m05-answerable-power-sprint-02-leg-03.mjs']);
run(['tools/validate-m05-answerable-power-sprint-02-leg-03.mjs']);
const report=JSON.parse(fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/sprint-02-leg-03.json'),'utf8'));
assert.equal(report.counts.sources,10);
assert.equal(report.counts.decision_stages,8);
assert.equal(report.counts.responsibility_actors,8);
assert.equal(report.counts.acceptance_objects,6);
assert.equal(report.counts.propositions,10);
assert.equal(report.disposition_counts.supported_for_human_review,3);
assert.equal(report.disposition_counts.requires_additional_acquisition,4);
assert.equal(report.disposition_counts.retained_candidate_only,1);
assert.equal(report.disposition_counts.bounded_non_link,2);
assert.equal(report.current_result.army_mission_sovereignty,'supported_for_human_review');
assert.equal(report.current_result.palantir_anduril_integration,'supported_for_human_review');
assert.equal(report.current_result.final_full_stack_acceptance,'requires_additional_acquisition');
assert.equal(report.current_result.meaningful_human_veto,'retained_candidate_only');
assert.equal(report.current_result.complete_program_foreclosure,'bounded_non_link');
assert.equal(report.current_result.common_private_governance,'bounded_non_link');
const workflow=fs.readFileSync(path.join(root,'.github/workflows/m05-answerable-power.yml'),'utf8');
assert.ok(workflow.includes('m05-answerable-power-sprint-02-leg-03.test.js'));
assert.ok(workflow.includes('build-m05-answerable-power-sprint-02-leg-03.mjs'));
assert.ok(workflow.includes('validate-m05-answerable-power-sprint-02-leg-03.mjs'));
console.log('m05-answerable-power-sprint-02-leg-03.test: OK');
