#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const run=(args)=>{const result=spawnSync(process.execPath,args,{cwd:root,encoding:'utf8'});if(result.status!==0){console.error(result.stdout);console.error(result.stderr);throw new Error(`${args.join(' ')} failed`)}return result.stdout};
run(['tools/build-m05-answerable-power-sprint-01.mjs']);
run(['tools/validate-m05-answerable-power-sprint-01.mjs']);
const report=JSON.parse(fs.readFileSync(path.join(root,'reports/core-thesis/answerable-power/sprint-01.json'),'utf8'));
assert.equal(report.counts.sources,25);
assert.equal(report.counts.triad_packets,6);
assert.equal(report.counts.standalone_packets,3);
assert.equal(report.counts.overlap_packets,3);
assert.equal(report.counts.benchmark_cases,4);
assert.ok(report.counts.benchmark_domains>=3);
assert.ok(report.counts.benchmark_jurisdictions>=2);
assert.equal(report.counts.next_sprint_lanes,7);
assert.equal(report.triad.triad_guardrail.disposition,'bounded_non_link');
assert.equal(report.benchmark.cross_domain_assessment.works_standard_met,false);
assert.equal(report.next_sprint_topology.master_issue.number,322);
assert.equal(report.next_sprint_topology.counts.live_lanes,7);
assert.equal(report.next_sprint_topology.counts.uninstantiated_lanes,0);
assert.equal(report.source_health.state_separation.execution_complete,true);
assert.equal(report.source_health.state_separation.coverage_healthy,false);
assert.equal(report.source_health.state_separation.evidence_sufficient,false);
const workflow=fs.readFileSync(path.join(root,'.github/workflows/m05-answerable-power.yml'),'utf8');
assert.ok(workflow.includes('data/intake/m05-answerable-power-*.json'));
assert.ok(workflow.includes('build-m05-answerable-power-sprint-01.mjs'));
assert.ok(workflow.includes('validate-m05-answerable-power-sprint-01.mjs'));
assert.ok(workflow.includes('m05-answerable-power-sprint-01.test.js'));
console.log('m05-answerable-power-sprint-01.test: OK');
