import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildEmbeddedNameIntake } from '../tools/lib/oge-fec-embedded-name-intake.mjs';

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'embedded-name-'));
const oge = path.join(tmp, 'interests.jsonl'), fec = path.join(tmp, 'payees.jsonl'), output = path.join(tmp, 'output');
const payee = (id, name) => ({ candidate_id: id, normalized_payee_name: name, observed_name_variants: [{ value: name, count: 1 }], observed_cycles: [2024], observed_committee_ids: ['C00000001'], source_record_count: 1, example_source_record_ids: [`source:${id}`], date_range_observed: { earliest: '2024-01-01', latest: '2024-01-01' } });
fs.writeFileSync(fec, [payee('fec:trump-plaza', 'TRUMP PLAZA LLC'), payee('fec:trump-corp', 'THE TRUMP CORPORATION'), payee('fec:acme', 'ACME LLC')].map(JSON.stringify).join('\n') + '\n');
const interest = (row, name) => ({ source_document_id: 'oge:test', source_page: 1, source_row_label: `part-6/${row}`, raw_text_sha256: String(row).padStart(64, '0'), raw_text_ref: `page#${row}`, source_sha256: 'a'.repeat(64), asset_or_entity_name_as_reported: name, person_id: 'person', interest_holder_scope: 'filer', valid_until: '2024-05-15' });
fs.writeFileSync(oge, [interest(1, 'TRUMP PLAZA LLC passive income description'), interest(2, 'TRUMP PLAZA LLC'), interest(3, 'ACME LLC passive'), interest(4, 'Underlying assets THE TRUMP CORPORATION location New York')].map(JSON.stringify).join('\n') + '\n');
const { manifest } = await buildEmbeddedNameIntake({ ogeInterestsFile: oge, fecPayeesFile: fec, outputDir: output });
assert.equal(manifest.coverage.fec_indexed_distinctive_candidates, 2);
assert.equal(manifest.coverage.fec_rejected_insufficient_distinctiveness, 1);
assert.equal(manifest.coverage.embedded_candidate_pairs_emitted, 2);
assert.equal(manifest.coverage.exact_equal_pairs_deferred, 1);
assert.equal(manifest.coverage.trump_token_candidate_pairs, 2);
const rows = fs.readFileSync(path.join(output, 'embedded-name-candidates.jsonl'), 'utf8').trim().split('\n').map(JSON.parse);
const plaza = rows.find(row => row.match.normalized_fec_payee_name === 'TRUMP PLAZA LLC');
assert.deepEqual(plaza.match.matched_tokens, ['TRUMP', 'PLAZA', 'LLC']);
assert.deepEqual(plaza.match.oge_suffix_tokens, ['PASSIVE', 'INCOME', 'DESCRIPTION']);
assert.equal(plaza.graph_effect, 'none');
assert.ok(plaza.forbidden_inferences.includes('embedded_name_resolves_identity'));
assert.ok(rows.some(row => row.match.normalized_fec_payee_name === 'THE TRUMP CORPORATION'));
fs.rmSync(tmp, { recursive: true, force: true });
console.log('oge-fec-embedded-name-intake.test.js: OK');
