import assert from 'node:assert/strict';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { compileManifest, loadPreferenceCustodyV57SourceBundle, renderMarkdown, validateBuild, validateManifest } from '../tools/lib/preference-custody-manifest-v58.mjs';
const load=p=>JSON.parse(readFileSync(p,'utf8')); if(!existsSync('build/research/preference-custody-laboratory-floor-v57.json'))execFileSync(process.execPath,['tools/compile-preference-custody-manifest-v57.mjs'],{stdio:'inherit'});if(!existsSync('build/research/preference-linkage-repository-owner-login-normalization-alias-case-location-pair-assurance.json'))execFileSync(process.execPath,['tools/compile-preference-linkage-repository-owner-login-normalization-alias-case-location-pair-assurance.mjs'],{stdio:'inherit'});
const manifest=load('data/research/preference-custody/control-manifest-v58.json'); const baseBuild=load('build/research/preference-custody-laboratory-floor-v57.json'); const targetBuild=load('build/research/preference-linkage-repository-owner-login-normalization-alias-case-location-pair-assurance.json'); const targetFixture=load(manifest.extension_control.source_fixture_path); const baseSources=loadPreferenceCustodyV57SourceBundle(load); const clone=v=>structuredClone(v);
assert.deepEqual(validateManifest(manifest),[]); const build=compileManifest(manifest,baseBuild,targetBuild,targetFixture,baseSources); assert.deepEqual(validateBuild(build,manifest,baseBuild,targetBuild,targetFixture,baseSources),[]); mkdirSync('build/research',{recursive:true});writeFileSync('build/research/preference-custody-laboratory-floor-v58.json',JSON.stringify(build,null,2)+'\n');writeFileSync('build/research/preference-custody-laboratory-floor-v58.md',renderMarkdown(build));
let refusals=0;const refuseManifest=x=>{assert.ok(validateManifest(x).length);refusals++;};const refuseInputs=(b=baseBuild,t=targetBuild,f=targetFixture,s=baseSources)=>{assert.throws(()=>compileManifest(manifest,b,t,f,s));refusals++;};const refuseBuild=x=>{assert.ok(validateBuild(x,manifest,baseBuild,targetBuild,targetFixture,baseSources).length);refusals++;};
for(const mutate of [m=>m.real_case_requirements_added.pop(),m=>m.real_case_requirements_added[1]=m.real_case_requirements_added[0],m=>m.frontier_transition.resolved_base_frontier='changed',m=>m.frontier_transition.successor_frontiers.reverse(),m=>m.preserved_account_frontier='changed',m=>m.prohibited_inferences.pop(),m=>m.extension_control.required_refusal_rules.pop(),m=>m.captured_at='2026-08-10']){const x=clone(manifest);mutate(x);refuseManifest(x);}
const b1=clone(baseBuild);b1.control_count=58;refuseInputs(b1);const b2=clone(baseBuild);b2.open_frontiers=[];refuseInputs(b2);const t1=clone(targetBuild);t1.metrics.worlds=9;refuseInputs(baseBuild,t1);const f1=clone(targetFixture);f1.worlds[1].description+=' changed';refuseInputs(baseBuild,targetBuild,f1);const s1=clone(baseSources);s1.manifest.captured_at='2026-08-10';refuseInputs(baseBuild,targetBuild,targetFixture,s1);const repeated=clone(baseSources);repeated.baseSources=repeated;refuseInputs(baseBuild,targetBuild,targetFixture,repeated);const proxy=new Proxy(clone(baseSources),{});refuseInputs(baseBuild,targetBuild,targetFixture,proxy);
for(const mutate of [b=>b.control_count=59,b=>b.controls[0]={...b.controls[0],control_id:'changed'},b=>b.open_frontiers=b.open_frontiers.filter(x=>x!==manifest.preserved_account_frontier),b=>b.promotion_boundary.promotion_requirement_count=2524,b=>b.control_integrity.base_integrity_preserved=false,b=>b.custody_chain[2].event_sha256='0'.repeat(64),b=>b.graph_effect='present']){const x=clone(build);mutate(x);refuseBuild(x);} assert.ok(refusals>=20);console.log(`preference-custody-manifest-v58.test.js: OK (${refusals} adversarial refusals)`);
