import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { compileFixture, validateBuild, validateFixture } from '../tools/lib/preference-linkage-repository-owner-login-unicode-casefold-alias-reuse-assurance.mjs';
const path='data/research/preference-custody/preference-linkage-repository-owner-login-unicode-casefold-alias-reuse-assurance.fixture.json'; const fixture=JSON.parse(readFileSync(path,'utf8'));
assert.deepEqual(validateFixture(fixture),[]); const build=compileFixture(fixture); assert.deepEqual(validateBuild(build,fixture),[]); mkdirSync('build/research',{recursive:true}); writeFileSync('build/research/preference-linkage-repository-owner-login-unicode-casefold-alias-reuse-assurance.json',JSON.stringify(build,null,2)+'\n');
const clone=v=>structuredClone(v); const rejects=[];
function bad(label,mutate) { const x=clone(fixture); mutate(x); const e=validateFixture(x); assert.ok(e.length,`${label} should be rejected`); rejects.push(label); }
bad('root key',x=>x.extra=true); bad('issue',x=>x.issue++); bad('date',x=>x.captured_at='2026-02-30'); bad('status',x=>x.status='verified'); bad('graph',x=>x.graph_effect='edge'); bad('baseline',x=>x.baseline.public_owner_login_status='verified'); bad('refusal',x=>x.required_refusal_rules.pop()); bad('world denominator',x=>x.worlds.pop()); bad('world duplicate',x=>x.worlds[1].world_id=x.worlds[0].world_id); bad('description',x=>x.worlds[0].description='changed'); bad('mechanism',x=>x.worlds[0].expected_mechanism='other'); bad('normalization boolean',x=>x.worlds[0].normalization_identity.login_utf8_bytes_bound=false); bad('normalization count',x=>x.worlds[1].normalization_identity.literal_codepoint_normalization_substitutions=99); bad('case count',x=>x.worlds[2].normalization_identity.casefold_case_history_substitutions=89); bad('confusable count',x=>x.worlds[3].confusable_collision.confusable_collision_adjudication_gaps=79); bad('alias count',x=>x.worlds[4].alias_rename.alias_rename_history_gaps=69); bad('recycle count',x=>x.worlds[5].recycling_reservation.recycled_login_tombstone_gaps=59); bad('reserve count',x=>x.worlds[5].recycling_reservation.reserved_namespace_authority_gaps=49); bad('namespace count',x=>x.worlds[6].namespace_binding.namespace_reuse_binding_mismatches=39); bad('unreconciled count',x=>x.worlds[6].lineage.unreconciled_login_identity_decisions=39); bad('stale count',x=>x.worlds[7].lineage.stale_login_identity_decisions=99); bad('unsupported total',x=>x.worlds[7].lineage.unsupported_login_identity_decisions=99); bad('flag',x=>x.worlds[0].expected_flags.complete_alias_rename=false); bad('authority',x=>x.worlds[0].lineage.binding_public_authority=true); bad('negative zero',x=>x.worlds[0].normalization_identity.literal_codepoint_normalization_substitutions=-0); bad('nonfinite',x=>x.worlds[0].normalization_identity.literal_codepoint_normalization_substitutions=Infinity); bad('custom prototype',x=>Object.setPrototypeOf(x.worlds[0].alias_rename,{})); bad('repeated identity',x=>x.worlds[1].normalization_identity=x.worlds[0].normalization_identity); bad('sparse array',x=>delete x.worlds[1]); bad('named array key',x=>x.worlds.extra='x');
function badBuild(label,mutate) { const b=clone(build); mutate(b); const e=validateBuild(b,fixture); assert.ok(e.length,`${label} build should be rejected`); }
badBuild('metric',b=>b.metrics.alias_rename_history_gaps++); badBuild('world',b=>b.worlds[0].flags.complete_alias_rename=false); badBuild('custody',b=>b.custody_chain[2].event='changed'); badBuild('fixture hash',b=>b.fixture_snapshot_sha256='0'.repeat(64)); badBuild('authority build',b=>b.graph_effect='edge');
console.log(`PC-61 fixture mutations rejected: ${rejects.length}`); console.log('preference-linkage-repository-owner-login-unicode-casefold-alias-reuse-assurance.test.js: OK');
