import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { compilePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture, preferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixtureSnapshot, validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceBuild, validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture } from '../tools/lib/preference-linkage-repository-commit-parent-merge-topology-tree-path-mode-blob-diff-identity-assurance.mjs';
const load=path=>JSON.parse(readFileSync(path,'utf8'));const clone=value=>structuredClone(value);const fixture=load('data/research/preference-custody/preference-linkage-repository-commit-parent-merge-topology-tree-path-mode-blob-diff-identity-assurance.fixture.json');const build=compilePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture(fixture);
assert.deepEqual(validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture(fixture),[]);assert.deepEqual(validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceBuild(build,fixture),[]);assert.equal(preferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixtureSnapshot(fixture),'2cd88c33b52ce9d79681915a91ae6e45a557622fd9cb11cb60238e3eea9b0555');assert.equal(build.world_count,8);assert.equal(build.complete_assurance_world_count,1);assert.equal(build.metrics.unsupported_repository_identity_decisions,700);
const mutateLeaf=value=>{if(typeof value==='boolean')return!value;if(typeof value==='number')return Number.isInteger(value)?value+1:value+0.01;if(typeof value==='string')return`${value}__mutation`;if(value===null)return'mutation';throw new Error(`unsupported leaf ${typeof value}`);};function leaves(value,path=[]){if(value===null||typeof value!=='object')return[{path,value}];const out=[];if(Array.isArray(value))value.forEach((item,index)=>out.push(...leaves(item,[...path,index])));else Object.entries(value).forEach(([key,item])=>out.push(...leaves(item,[...path,key])));return out;}function setAt(root,path,value){let target=root;for(const key of path.slice(0,-1))target=target[key];target[path.at(-1)]=value;}const fixtureRefused=(candidate,label)=>assert.ok(validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture(candidate).length>0,label);const buildRefused=(candidate,label)=>assert.ok(validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceBuild(candidate,fixture).length>0,label);
let fixtureMutationCount=0;for(const{path,value}of leaves(fixture)){const candidate=clone(fixture);setAt(candidate,path,mutateLeaf(value));fixtureRefused(candidate,`fixture leaf ${path.join('.')}`);fixtureMutationCount+=1;}assert.ok(fixtureMutationCount>=700,`expected broad fixture mutation census, observed ${fixtureMutationCount}`);
let buildMutationCount=0;const buildLeaves=leaves(build);const stride=Math.max(1,Math.ceil(buildLeaves.length/100));for(let i=0;i<buildLeaves.length;i+=stride){const{path,value}=buildLeaves[i];const candidate=clone(build);setAt(candidate,path,mutateLeaf(value));buildRefused(candidate,`build leaf ${path.join('.')}`);buildMutationCount+=1;}assert.ok(buildMutationCount>=75,`expected bounded build tamper coverage, observed ${buildMutationCount}`);
const redistributed=clone(fixture);redistributed.worlds[1].repository_identity.repository_or_commit_substitution_decisions-=1;redistributed.worlds[2].topology_tree.parent_topology_merge_base_mismatch_decisions+=1;fixtureRefused(redistributed,'aggregate-preserving burden redistribution');const partial=clone(fixture);partial.worlds[6].diff_boundary.binary_receipts_bound=true;fixtureRefused(partial,'partial state mutation preserving coarse class');
function exoticRecord(source,make){const exotic=make();Object.setPrototypeOf(exotic,Object.prototype);Object.assign(exotic,source);return exotic;}
for(const[label,make]of[['Date',()=>new Date(0)],['Map',()=>new Map()],['Set',()=>new Set()],['ArrayBuffer',()=>new ArrayBuffer(8)],['typed array',()=>new Uint8Array(0)],['AbortController',()=>new AbortController()],['URL',()=>new URL('https://example.invalid')]]){const candidate=clone(fixture);candidate.worlds[0].repository_identity=exoticRecord(candidate.worlds[0].repository_identity,make);fixtureRefused(candidate,`${label} fixture record with reset prototype`);}
for(const[label,make]of[['Date',()=>new Date(0)],['Map',()=>new Map()],['URL',()=>new URL('https://example.invalid')]]){const candidate=clone(build);candidate.worlds[0].flags=exoticRecord(candidate.worlds[0].flags,make);buildRefused(candidate,`${label} compiled record with reset prototype`);}
const namedFixture=clone(fixture);namedFixture.worlds.unapproved=true;fixtureRefused(namedFixture,'named fixture array property');const symbolFixture=clone(fixture);symbolFixture.worlds[Symbol('unapproved')]=true;fixtureRefused(symbolFixture,'symbol fixture array property');const hugeSparse=clone(fixture);hugeSparse.worlds.length=2**32-1;fixtureRefused(hugeSparse,'huge sparse fixture array');const negativeZero=clone(fixture);negativeZero.worlds[0].repository_identity.repository_or_commit_substitution_decisions=-0;fixtureRefused(negativeZero,'negative-zero fixture burden');
const alias=clone(fixture);alias.worlds[1].repository_identity=alias.worlds[0].repository_identity;fixtureRefused(alias,'repeated object identity');const cycle=clone(fixture);cycle.worlds[0].repository_identity.self=cycle.worlds[0].repository_identity;fixtureRefused(cycle,'cycle');const proxy=clone(fixture);proxy.worlds[0].repository_identity=new Proxy(proxy.worlds[0].repository_identity,{get(){throw new Error('trap');}});assert.doesNotThrow(()=>validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture(proxy));fixtureRefused(proxy,'proxy-backed fixture');
for(const malformed of[null,0,'invalid',false,[]]){assert.doesNotThrow(()=>validatePreferenceLinkageRepositoryCommitParentMergeTopologyTreePathModeBlobDiffIdentityAssuranceFixture(malformed));fixtureRefused(malformed,`malformed fixture ${String(malformed)}`);}
const temp=mkdtempSync(join(tmpdir(),'pc54-null-fixture-'));try{const nullPath=join(temp,'null.json');writeFileSync(nullPath,'null\n');const compileCli=spawnSync(process.execPath,['tools/compile-preference-linkage-repository-commit-parent-merge-topology-tree-path-mode-blob-diff-identity-assurance.mjs',nullPath,join(temp,'out.json'),join(temp,'out.md')],{encoding:'utf8'});assert.equal(compileCli.status,1);assert.match(`${compileCli.stdout}
${compileCli.stderr}`,/PC-54 fixture must be an object/);const validateCli=spawnSync(process.execPath,['tools/validate-preference-linkage-repository-commit-parent-merge-topology-tree-path-mode-blob-diff-identity-assurance.mjs',nullPath,join(temp,'missing.json')],{encoding:'utf8'});assert.equal(validateCli.status,1);assert.match(`${validateCli.stdout}
${validateCli.stderr}`,/PC-54 fixture must be an object/);assert.doesNotMatch(`${validateCli.stdout}
${validateCli.stderr}`,/ENOENT|TypeError/);}finally{rmSync(temp,{recursive:true,force:true});}
console.log(`validated PC-54 standalone fixture with ${fixtureMutationCount} fixture mutations and ${buildMutationCount} build tamper checks`);
