import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { compilePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture, preferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixtureSnapshot, validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceBuild, validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture } from '../tools/lib/preference-linkage-review-scope-source-tree-generated-input-build-recipe-assurance.mjs';
const load=path=>JSON.parse(readFileSync(path,'utf8'));const clone=value=>structuredClone(value);
const fixturePath='data/research/preference-custody/preference-linkage-review-scope-source-tree-generated-input-build-recipe-assurance.fixture.json';const fixture=load(fixturePath);const build=compilePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture(fixture);
assert.deepEqual(validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture(fixture),[]);assert.deepEqual(validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceBuild(build,fixture),[]);assert.equal(preferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixtureSnapshot(fixture),'fe6ceb706ef5a8780a6cc927fcc5a255f82d56d887f3df52685dabe3d1065325');assert.equal(build.world_count,8);assert.equal(build.public_signature_count,1);assert.equal(build.assurance_governance_signature_count,8);assert.equal(build.complete_assurance_world_count,1);assert.equal(build.metrics.unsupported_review_build_recipe_decisions,700);assert.equal(build.metrics.binding_public_authority_worlds,0);
const mutateLeaf=value=>{if(typeof value==='boolean')return!value;if(typeof value==='number')return Number.isInteger(value)?value+1:value+0.01;if(typeof value==='string')return`${value}__mutation`;if(value===null)return'mutation';throw new Error(`unsupported leaf ${typeof value}`);};function leaves(value,path=[]){if(value===null||typeof value!=='object')return[{path,value}];const out=[];if(Array.isArray(value))value.forEach((item,index)=>out.push(...leaves(item,[...path,index])));else Object.entries(value).forEach(([key,item])=>out.push(...leaves(item,[...path,key])));return out;}function setAt(root,path,value){let cursor=root;for(const key of path.slice(0,-1))cursor=cursor[key];cursor[path.at(-1)]=value;}function fixtureRefused(candidate,label){const errors=validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture(candidate);assert.ok(errors.length>0,`${label} must be refused`);}function buildRefused(candidate,label){const errors=validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceBuild(candidate,fixture);assert.ok(errors.length>0,`${label} must be refused`);}
let fixtureMutationCount=0;for(const{path,value}of leaves(fixture)){const candidate=clone(fixture);setAt(candidate,path,mutateLeaf(value));fixtureRefused(candidate,`fixture leaf ${path.join('.')}`);fixtureMutationCount+=1;}assert.ok(fixtureMutationCount>=1000,`expected broad fixture mutation census, observed ${fixtureMutationCount}`);
let buildMutationCount=0;const buildLeaves=leaves(build);const stride=Math.max(1,Math.ceil(buildLeaves.length/80));for(let i=0;i<buildLeaves.length;i+=stride){const{path,value}=buildLeaves[i];const candidate=clone(build);setAt(candidate,path,mutateLeaf(value));buildRefused(candidate,`build leaf ${path.join('.')}`);buildMutationCount+=1;}assert.ok(buildMutationCount>=60,`expected bounded build tamper coverage, observed ${buildMutationCount}`);
const redistributed=clone(fixture);redistributed.worlds[1].repository_scope.repository_parent_tree_substitution_decisions-=1;redistributed.worlds[2].repository_scope.reviewed_file_blob_diff_scope_gaps+=1;fixtureRefused(redistributed,'aggregate-preserving burden redistribution');const partial=clone(fixture);partial.worlds[3].dependency_sources.vendor_license_ledger_bound=true;fixtureRefused(partial,'partial state mutation preserving coarse class');
const namedFixtureArray=clone(fixture);namedFixtureArray.worlds.unapproved=true;fixtureRefused(namedFixtureArray,'named fixture array property');const namedRulesArray=clone(fixture);namedRulesArray.required_refusal_rules.unapproved=true;fixtureRefused(namedRulesArray,'named refusal-rule array property');const namedBuildArray=clone(build);namedBuildArray.worlds.unapproved=true;buildRefused(namedBuildArray,'named build array property');
const symbolFixture=clone(fixture);symbolFixture.worlds[Symbol('unapproved')]=true;fixtureRefused(symbolFixture,'symbol fixture array property');const negativeZeroFixture=clone(fixture);negativeZeroFixture.worlds[0].repository_scope.repository_parent_tree_substitution_decisions=-0;fixtureRefused(negativeZeroFixture,'negative-zero fixture burden');const negativeZeroBuild=clone(build);negativeZeroBuild.worlds[0].numeric_burden.repository_parent_tree_substitution_decisions=-0;buildRefused(negativeZeroBuild,'negative-zero compiled burden');const sparse=clone(fixture);delete sparse.worlds[2];fixtureRefused(sparse,'sparse world array');const hugeSparse=clone(fixture);hugeSparse.worlds.length=2**32-1;fixtureRefused(hugeSparse,'huge sparse world array');const hugeSparseBuild=clone(build);hugeSparseBuild.worlds.length=2**32-1;buildRefused(hugeSparseBuild,'huge sparse compiled-world array');const repeated=clone(fixture);repeated.worlds[1].repository_scope=repeated.worlds[0].repository_scope;fixtureRefused(repeated,'repeated object identity');const cycle=clone(fixture);cycle.self=cycle;fixtureRefused(cycle,'cyclic fixture');const proxy=new Proxy(clone(fixture),{ownKeys(){throw new Error('opaque');}});assert.doesNotThrow(()=>validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture(proxy));fixtureRefused(proxy,'proxy fixture');const custom=clone(fixture);Object.setPrototypeOf(custom.worlds[0].repository_scope,{});fixtureRefused(custom,'custom prototype');const accessor=clone(fixture);Object.defineProperty(accessor.worlds[0].repository_scope,'repository_owner_bound',{get(){return true;},enumerable:true});fixtureRefused(accessor,'accessor');const hidden=clone(fixture);Object.defineProperty(hidden.worlds[0].repository_scope,'repository_owner_bound',{value:true,enumerable:false});fixtureRefused(hidden,'non-enumerable property');const nonfinite=clone(fixture);nonfinite.worlds[1].repository_scope.repository_parent_tree_substitution_decisions=Number.NaN;fixtureRefused(nonfinite,'non-finite number');
for(const malformed of[null,0,'invalid',false,[]]){assert.doesNotThrow(()=>validatePreferenceLinkageReviewScopeSourceTreeGeneratedInputBuildRecipeAssuranceFixture(malformed));fixtureRefused(malformed,`malformed fixture ${String(malformed)}`);}
const temp=mkdtempSync(join(tmpdir(),'pc52-null-fixture-'));try{const nullPath=join(temp,'null.json');writeFileSync(nullPath,'null\n');const compileCli=spawnSync(process.execPath,['tools/compile-preference-linkage-review-scope-source-tree-generated-input-build-recipe-assurance.mjs',nullPath,join(temp,'out.json'),join(temp,'out.md')],{encoding:'utf8'});assert.equal(compileCli.status,1);assert.match(`${compileCli.stdout}\n${compileCli.stderr}`,/PC-52 fixture must be an object/);assert.doesNotMatch(`${compileCli.stdout}\n${compileCli.stderr}`,/TypeError|ENOENT/);const validateCli=spawnSync(process.execPath,['tools/validate-preference-linkage-review-scope-source-tree-generated-input-build-recipe-assurance.mjs',nullPath,join(temp,'missing.json')],{encoding:'utf8'});assert.equal(validateCli.status,1);assert.match(validateCli.stderr,/PC-52 fixture must be an object/);assert.doesNotMatch(`${validateCli.stdout}\n${validateCli.stderr}`,/TypeError|ENOENT/);}finally{rmSync(temp,{recursive:true,force:true});}
console.log(`validated PC-52 standalone fixture with ${fixtureMutationCount} fixture mutations and ${buildMutationCount} build tamper checks`);
