import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { validatePreferenceCustodyManifestV36, validatePreferenceCustodyManifestV36Build } from '../tools/lib/preference-custody-manifest-v36.mjs';
execFileSync(process.execPath,['tools/compile-preference-custody-manifest-v36.mjs'],{stdio:'pipe'});
const manifest=JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v36.json','utf8'));
const base=JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v35.json','utf8'));
const build=JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v36.json','utf8'));
const markdown=readFileSync('build/research/preference-custody-laboratory-floor-v36.md','utf8');
assert.deepEqual(validatePreferenceCustodyManifestV36(manifest),[]);assert.deepEqual(validatePreferenceCustodyManifestV36Build(build),[]);
assert.equal(build.control_count,38);assert.equal(build.composition.base_control_count,37);assert.equal(build.composition.extension_control_id,'PC-38');
assert.equal(build.composition.base_promotion_requirement_count,1341);assert.equal(build.composition.added_promotion_requirement_count,48);assert.equal(build.composition.final_promotion_requirement_count,1389);
assert.deepEqual(build.controls.slice(0,37),base.controls);assert.deepEqual(build.composition.base_open_frontiers,base.open_frontiers);
const expectedOpen=[...new Set([...base.open_frontiers.filter(x=>x!=='identity_resolution_entity_boundary_and_network_frame_assurance'),...manifest.frontier_transition.successor_frontiers])].sort();
assert.deepEqual([...build.open_frontiers].sort(),expectedOpen);
for(const frontier of ['hard_to_enumerate_subgroup_enumeration_response_propensity_and_nonresponse_mechanism_governance','inaccessible_source_suppression_proxy_external_frame_imputation_and_selection_assurance','population_entry_exit_migration_merger_split_reactivation_snapshot_alignment_and_turnover_governance','identity_collision_fragmentation_unit_boundary_duplicate_and_cross_source_linkage_assurance']) assert.ok(build.open_frontiers.includes(frontier),frontier);
const pc=build.controls.at(-1);assert.equal(pc.control_id,'PC-38');assert.equal(pc.proof_summary.world_count,8);assert.equal(pc.proof_summary.total_false_merged_entities,20);assert.equal(pc.proof_summary.total_denominator_drift,35);assert.equal(pc.proof_summary.complete_identity_boundary_assurance_supported_in_at_least_one_world,true);
for(const value of Object.values(build.control_integrity)) assert.equal(value,true);assert.equal(build.graph_effect,'none');assert.equal(build.counts_toward_thesis_evidence,false);assert.equal(build.conclusion_generated,false);assert.equal(build.promotion_boundary.laboratory_controls_are_real_world_evidence,false);
assert.equal(build.custody_chain.length,5);assert.equal(build.custody_chain.at(-1).event_sha256,build.custody_chain_head_sha256);assert.match(markdown,/Controls:\*\* 38/);assert.match(markdown,/PC-38 proof summary/);
const graph=structuredClone(manifest);graph.graph_effect='asserted';assert.ok(validatePreferenceCustodyManifestV36(graph).length);
const missing=structuredClone(build);missing.open_frontiers.pop();assert.ok(validatePreferenceCustodyManifestV36Build(missing).some(e=>/frontier/.test(e)));
const count=structuredClone(build);count.control_count=37;assert.ok(validatePreferenceCustodyManifestV36Build(count).some(e=>/thirty-eight/.test(e)));
const metric=structuredClone(build);metric.controls.at(-1).proof_summary.total_false_merged_entities=19;assert.ok(validatePreferenceCustodyManifestV36Build(metric).some(e=>/metric/.test(e)));
console.log('preference custody floor v36 adversarial tests passed');
