import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { compilePreferenceCustodyManifestV48, loadPreferenceCustodyV47SourceBundle, preferenceCustodyManifestV48Snapshot, preferenceCustodyV47SourceBundleSnapshot, validatePreferenceCustodyManifestV48, validatePreferenceCustodyManifestV48Build } from '../tools/lib/preference-custody-manifest-v48.mjs';
const load = path => JSON.parse(readFileSync(path, 'utf8')); const clone = value => structuredClone(value);
if (!existsSync('build/research/preference-custody-laboratory-floor-v47.json')) execFileSync(process.execPath, ['tools/compile-preference-custody-manifest-v47.mjs'], { stdio: 'inherit' });
if (!existsSync('build/research/preference-linkage-executable-artifact-build-dependency-environment-runtime-identity-assurance.json')) execFileSync(process.execPath, ['tools/compile-preference-linkage-executable-artifact-build-dependency-environment-runtime-identity-assurance.mjs'], { stdio: 'inherit' });
const manifest = load('data/research/preference-custody/control-manifest-v48.json'); const baseBuild = load('build/research/preference-custody-laboratory-floor-v47.json'); const targetBuild = load('build/research/preference-linkage-executable-artifact-build-dependency-environment-runtime-identity-assurance.json'); const targetFixture = load(manifest.extension_control.source_fixture_path); const baseSources = loadPreferenceCustodyV47SourceBundle(load);
const compiled = compilePreferenceCustodyManifestV48(manifest, baseBuild, targetBuild, targetFixture, baseSources); const buildPath = 'build/research/preference-custody-laboratory-floor-v48.json'; const build = existsSync(buildPath) ? load(buildPath) : compiled;
assert.deepEqual(validatePreferenceCustodyManifestV48(manifest), []); assert.deepEqual(validatePreferenceCustodyManifestV48Build(build, manifest, baseBuild, targetBuild, targetFixture, baseSources), []); assert.deepEqual(compiled, build); assert.equal(preferenceCustodyManifestV48Snapshot(manifest), 'a16f432cdd0e663cc89e4bcd04368c2daec80db171abe47d6f2b4de46c188744'); assert.match(preferenceCustodyV47SourceBundleSnapshot(baseSources), /^[0-9a-f]{64}$/);
assert.equal(build.control_count, 50); assert.equal(build.controls.at(-1).control_id, 'PC-50'); assert.equal(build.composition.base_control_count, 49); assert.equal(build.composition.base_promotion_requirement_count, 1920); assert.equal(build.composition.added_promotion_requirement_count, 50); assert.equal(build.composition.final_promotion_requirement_count, 1970); assert.equal(build.promotion_boundary.promotion_requirement_count, 1970); assert.equal(build.promotion_boundary.real_case_requires.length, 1970); assert.equal(new Set(build.promotion_boundary.real_case_requires).size, 1970); assert.deepEqual(build.controls.slice(0,49), baseBuild.controls); assert.ok(Object.values(build.control_integrity).every(Boolean));
assert.ok(!build.open_frontiers.includes("linkage_interval_executable_artifact_build_dependency_environment_and_runtime_identity_governance")); for (const frontier of ["linkage_interval_source_review_build_reproducibility_artifact_signature_provenance_and_execution_attestation_assurance","linkage_interval_dependency_supply_chain_container_environment_loaded_module_service_snapshot_and_runtime_succession_governance","linkage_interval_numerical_determinism_seed_prng_parallelism_hardware_precision_and_replay_equivalence_governance","linkage_interval_deployment_applicability_monitoring_shift_trigger_abstention_rollback_and_release_succession_governance","linkage_interval_event_state_competing_event_censoring_abstention_and_ambiguity_governance","linkage_interval_estimand_population_unit_horizon_support_tail_coverage_meaning_and_interpretation_governance","linkage_interval_dependence_resampling_effective_sample_size_multiplicity_adaptive_selection_and_simultaneous_coverage_governance","linkage_calibration_drift_subgroup_monitoring_recalibration_trigger_rollback_and_certificate_withdrawal_governance"]) assert.ok(build.open_frontiers.includes(frontier), `missing preserved frontier ${frontier}`);
const mutateLeaf = value => { if (typeof value === 'boolean') return !value; if (typeof value === 'number') return Number.isInteger(value) ? value + 1 : value + 0.01; if (typeof value === 'string') return `${value}__mutation`; if (value === null) return 'mutation'; throw new Error(`unsupported mutation leaf ${typeof value}`); };
function leaves(value,path=[]) { if (value===null || typeof value!=='object') return [{path,value}]; const out=[]; if (Array.isArray(value)) value.forEach((item,index)=>out.push(...leaves(item,[...path,index]))); else Object.entries(value).forEach(([key,item])=>out.push(...leaves(item,[...path,key]))); return out; } function setAt(root,path,value) { let cursor=root; for (const key of path.slice(0,-1)) cursor=cursor[key]; cursor[path.at(-1)]=value; }
function manifestRefused(candidate,label) { const errors=validatePreferenceCustodyManifestV48(candidate); assert.ok(errors.length>0,`${label} must be refused`); assert.throws(()=>compilePreferenceCustodyManifestV48(candidate,baseBuild,targetBuild,targetFixture,baseSources),error=>error instanceof Error && !(error instanceof TypeError),`${label} compile must refuse without a TypeError escape`); }
function inputRefused(candidateBase,candidateTarget,candidateFixture,candidateSources,label) { assert.throws(()=>compilePreferenceCustodyManifestV48(manifest,candidateBase,candidateTarget,candidateFixture,candidateSources),undefined,`${label} must be refused`); }
function buildRefused(candidate,label) { const errors=validatePreferenceCustodyManifestV48Build(candidate,manifest,baseBuild,targetBuild,targetFixture,baseSources); assert.ok(errors.length>0,`${label} must be refused`); }
console.log('v48-test phase manifest mutations'); let manifestMutationCount=0; for (const {path,value} of leaves(manifest)) { const candidate=clone(manifest); setAt(candidate,path,mutateLeaf(value)); manifestRefused(candidate,`manifest leaf ${path.join('.')}`); manifestMutationCount+=1; } assert.ok(manifestMutationCount>=110,`expected broad manifest mutation coverage, observed ${manifestMutationCount}`);
const extra=clone(manifest); extra.unapproved=true; manifestRefused(extra,'extra manifest key'); const missing=clone(manifest); delete missing.frontier_transition; manifestRefused(missing,'missing manifest field'); const reordered=clone(manifest); [reordered.real_case_requirements_added[0],reordered.real_case_requirements_added[1]]=[reordered.real_case_requirements_added[1],reordered.real_case_requirements_added[0]]; manifestRefused(reordered,'requirement reordering'); const postdated=clone(manifest); postdated.captured_at='2026-08-06'; manifestRefused(postdated,'postdated manifest'); const manifestCycle=clone(manifest); manifestCycle.self=manifestCycle; manifestRefused(manifestCycle,'cyclic manifest'); const manifestProxy=new Proxy(clone(manifest),{ownKeys(){throw new Error('opaque');}}); manifestRefused(manifestProxy,'proxy manifest');
const getTrapManifest=new Proxy(clone(manifest),{get(target,property,receiver){if(property==='base_floor') throw new Error('opaque base floor'); return Reflect.get(target,property,receiver);}}); assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(getTrapManifest),'get-trap manifest validation must not throw'); manifestRefused(getTrapManifest,'get-trap manifest');
const nestedGetTrapManifest=clone(manifest); nestedGetTrapManifest.extension_control=new Proxy(nestedGetTrapManifest.extension_control,{get(target,property,receiver){if(property==='fixture_id') throw new Error('opaque fixture id'); return Reflect.get(target,property,receiver);}}); assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(nestedGetTrapManifest),'nested get-trap manifest validation must not throw'); manifestRefused(nestedGetTrapManifest,'nested get-trap manifest');
const lengthTrapManifest=clone(manifest); lengthTrapManifest.real_case_requirements_added=new Proxy(lengthTrapManifest.real_case_requirements_added,{get(target,property,receiver){if(property==='length') throw new Error('opaque requirement length'); return Reflect.get(target,property,receiver);}}); assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(lengthTrapManifest),'array length-trap manifest validation must not throw'); manifestRefused(lengthTrapManifest,'array length-trap manifest');
for (const malformedManifest of [null,0,'invalid',false,[]]) { assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(malformedManifest),`top-level malformed manifest ${String(malformedManifest)} validation must not throw`); manifestRefused(malformedManifest,`top-level malformed manifest ${String(malformedManifest)}`); }
for (const field of ['base_floor','extension_control','identification_requirement','frontier_transition','interpretation_contract']) { for (const replacement of [null,0]) { const candidate=clone(manifest); candidate[field]=replacement; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(candidate),`${field} ${String(replacement)} validation must not throw`); manifestRefused(candidate,`${field} ${String(replacement)}`); } }
for (const field of ['real_case_requirements_added','prohibited_inferences']) { for (const replacement of [null,0]) { const candidate=clone(manifest); candidate[field]=replacement; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(candidate),`${field} ${String(replacement)} validation must not throw`); manifestRefused(candidate,`${field} ${String(replacement)}`); } }
for (const [container,field] of [['extension_control','required_refusal_rules'],['frontier_transition','successor_frontiers']]) { for (const replacement of [null,0]) { const candidate=clone(manifest); candidate[container][field]=replacement; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48(candidate),`${container}.${field} ${String(replacement)} validation must not throw`); manifestRefused(candidate,`${container}.${field} ${String(replacement)}`); } }
const nullManifestCliTemp=mkdtempSync(join(tmpdir(),'pc50-v48-null-manifest-')); try { const nullManifestPath=join(nullManifestCliTemp,'null-manifest.json'); const outputJson=join(nullManifestCliTemp,'floor.json'); const outputMarkdown=join(nullManifestCliTemp,'floor.md'); writeFileSync(nullManifestPath,'null\n'); const compileCli=spawnSync(process.execPath,['tools/compile-preference-custody-manifest-v48.mjs',nullManifestPath,outputJson,outputMarkdown],{encoding:'utf8'}); assert.equal(compileCli.status,1,'null v48 manifest compile CLI must refuse'); assert.match(`${compileCli.stdout}\n${compileCli.stderr}`,/Preference Custody v48 manifest must be an object/); assert.doesNotMatch(`${compileCli.stdout}\n${compileCli.stderr}`,/TypeError/); const validateCli=spawnSync(process.execPath,['tools/validate-preference-custody-manifest-v48.mjs',nullManifestPath,'build/research/preference-custody-laboratory-floor-v48.json'],{encoding:'utf8'}); assert.equal(validateCli.status,1,'null v48 manifest validate CLI must refuse'); assert.match(validateCli.stderr,/Preference Custody v48 manifest must be an object/); assert.doesNotMatch(`${validateCli.stdout}\n${validateCli.stderr}`,/TypeError/); } finally { rmSync(nullManifestCliTemp,{recursive:true,force:true}); }

console.log('v48-test phase input mutations'); const baseDrift=clone(baseBuild); baseDrift.control_count=48; inputRefused(baseDrift,targetBuild,targetFixture,baseSources,'base count drift'); const baseControlDrift=clone(baseBuild); baseControlDrift.controls[0].control_id='PC-X'; inputRefused(baseControlDrift,targetBuild,targetFixture,baseSources,'base control drift'); const targetDrift=clone(targetBuild); targetDrift.metrics.unsupported_executable_identity_decisions+=1; inputRefused(baseBuild,targetDrift,targetFixture,baseSources,'target build drift'); const fixtureDrift=clone(targetFixture); fixtureDrift.worlds[0].description+=' drift'; inputRefused(baseBuild,targetBuild,fixtureDrift,baseSources,'target fixture drift'); const sourceManifestDrift=clone(baseSources); sourceManifestDrift.manifest.control_issue=0; inputRefused(baseBuild,targetBuild,targetFixture,sourceManifestDrift,'v47 source manifest drift'); const nestedPostdate=clone(baseSources); nestedPostdate.targetFixture.captured_at='2026-08-06'; inputRefused(baseBuild,targetBuild,targetFixture,nestedPostdate,'postdated transitive source');
const sourceAlias=clone(baseSources); sourceAlias.targetFixture=sourceAlias.targetBuild; inputRefused(baseBuild,targetBuild,targetFixture,sourceAlias,'source bundle alias'); const rootAlias=clone(baseSources); assert.doesNotThrow(()=>compilePreferenceCustodyManifestV48(manifest,baseBuild,targetBuild,targetFixture,rootAlias),'warm valid source'); rootAlias.baseBuild=rootAlias.targetBuild; inputRefused(baseBuild,targetBuild,targetFixture,rootAlias,'mutated warm source alias'); const sourceCycle=clone(baseSources); sourceCycle.baseSources=sourceCycle; inputRefused(baseBuild,targetBuild,targetFixture,sourceCycle,'cyclic source bundle'); const nonCanonical=clone(baseSources); Object.setPrototypeOf(nonCanonical,null); inputRefused(baseBuild,targetBuild,targetFixture,nonCanonical,'non-canonical source bundle'); const proxySources=new Proxy(clone(baseSources),{ownKeys(){throw new Error('opaque');}}); inputRefused(baseBuild,targetBuild,targetFixture,proxySources,'proxy source bundle'); const getTrapSources=new Proxy(clone(baseSources),{get(target,property,receiver){if(property==='manifest') throw new Error('opaque source manifest'); return Reflect.get(target,property,receiver);}}); inputRefused(baseBuild,targetBuild,targetFixture,getTrapSources,'get-trap source bundle'); const sourceLengthTrap=clone(baseSources); sourceLengthTrap.targetFixture.worlds=new Proxy(sourceLengthTrap.targetFixture.worlds,{get(target,property,receiver){if(property==='length') throw new Error('opaque source worlds length'); return Reflect.get(target,property,receiver);}}); inputRefused(baseBuild,targetBuild,targetFixture,sourceLengthTrap,'array length-trap source bundle'); const crossRoot=clone(baseSources); assert.doesNotThrow(()=>compilePreferenceCustodyManifestV48(manifest,baseBuild,targetBuild,targetFixture,crossRoot),'warm independent roots'); inputRefused(baseBuild,targetBuild,targetFixture,targetBuild,'cross-root target/source identity');
console.log('v48-test phase build mutations'); const buildLeaves=leaves(build); const stride=Math.max(1,Math.floor(buildLeaves.length/72)); let buildMutationCount=0; for (let index=0;index<buildLeaves.length;index+=stride) { const {path,value}=buildLeaves[index]; const candidate=clone(build); setAt(candidate,path,mutateLeaf(value)); buildRefused(candidate,`build leaf ${path.join('.')}`); buildMutationCount+=1; } assert.ok(buildMutationCount>=55,`expected broad floor build tamper coverage, observed ${buildMutationCount}`); const scalarContainers=['controls','identification_requirements','refusal_rule_union','open_frontiers','custody_chain','prohibited_inferences','composition','control_integrity','frontier_transition','promotion_boundary','interpretation_contract']; for (const field of scalarContainers) { const candidate=clone(build); candidate[field]=0; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(candidate,manifest,baseBuild,targetBuild,targetFixture,baseSources),`scalar ${field} validation must not throw`); buildRefused(candidate,`scalar ${field}`); } const nullControl=clone(build); nullControl.controls[0]=null; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(nullControl,manifest,baseBuild,targetBuild,targetFixture,baseSources),'null control validation must not throw'); buildRefused(nullControl,'null control'); const nullCustodyEvent=clone(build); nullCustodyEvent.custody_chain[0]=null; assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(nullCustodyEvent,manifest,baseBuild,targetBuild,targetFixture,baseSources),'null custody event validation must not throw'); buildRefused(nullCustodyEvent,'null custody event');
for (const malformedBuild of [null, 0, 'invalid', false, []]) { assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(malformedBuild,manifest,baseBuild,targetBuild,targetFixture,baseSources),'top-level malformed floor build validation must not throw'); buildRefused(malformedBuild,`top-level malformed floor build ${String(malformedBuild)}`); }
const cliTemp=mkdtempSync(join(tmpdir(),'pc50-v48-scalar-')); try { const scalarBuild=clone(build); scalarBuild.controls=0; const scalarBuildPath=join(cliTemp,'scalar-build.json'); writeFileSync(scalarBuildPath,JSON.stringify(scalarBuild)); const cli=spawnSync(process.execPath,['tools/validate-preference-custody-manifest-v48.mjs','data/research/preference-custody/control-manifest-v48.json',scalarBuildPath],{encoding:'utf8'}); assert.equal(cli.status,1,'scalar floor build CLI must refuse'); assert.match(cli.stderr,/controls must be an array/); assert.doesNotMatch(`${cli.stdout}
${cli.stderr}`,/TypeError/); } finally { rmSync(cliTemp,{recursive:true,force:true}); }
const falseIntegrity=clone(build); falseIntegrity.control_integrity.base_integrity_preserved=false; buildRefused(falseIntegrity,'false integrity'); const droppedFrontier=clone(build); droppedFrontier.open_frontiers=droppedFrontier.open_frontiers.filter(frontier=>frontier!=='linkage_interval_numerical_determinism_seed_prng_parallelism_hardware_precision_and_replay_equivalence_governance'); buildRefused(droppedFrontier,'dropped preserved frontier'); const floorAlias=clone(build); floorAlias.controls[1]=floorAlias.controls[0]; buildRefused(floorAlias,'aliased floor controls'); const floorCycle=clone(build); floorCycle.controls[0].cycle=floorCycle; buildRefused(floorCycle,'cyclic floor build');
const buildGetTrap=new Proxy(clone(build),{get(target,property,receiver){if(property==='controls') throw new Error('opaque controls'); return Reflect.get(target,property,receiver);}}); assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(buildGetTrap,manifest,baseBuild,targetBuild,targetFixture,baseSources),'get-trap floor build validation must not throw'); buildRefused(buildGetTrap,'get-trap floor build'); const buildLengthTrap=clone(build); buildLengthTrap.controls=new Proxy(buildLengthTrap.controls,{get(target,property,receiver){if(property==='length') throw new Error('opaque controls length'); return Reflect.get(target,property,receiver);}}); assert.doesNotThrow(()=>validatePreferenceCustodyManifestV48Build(buildLengthTrap,manifest,baseBuild,targetBuild,targetFixture,baseSources),'array length-trap floor build validation must not throw'); buildRefused(buildLengthTrap,'array length-trap floor build');
console.log(`validated Preference Custody floor v48 with ${manifestMutationCount} manifest mutations and ${buildMutationCount} floor build tamper checks`);
