import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { validatePreferenceCustodyManifestV35, validatePreferenceCustodyManifestV35Build } from '../tools/lib/preference-custody-manifest-v35.mjs';
import { EXPECTED_HARD_TO_ENUMERATE_MISSINGNESS_METRICS } from '../tools/lib/preference-hard-to-enumerate-missingness-assurance.mjs';
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;const sha256=value=>createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex');
const run=(script,manifest,jsonPath,markdownPath)=>{const result=spawnSync(process.execPath,[script,manifest,jsonPath,markdownPath],{encoding:'utf8'});assert.equal(result.status,0,result.stderr||result.stdout);};
const directory=mkdtempSync(join(tmpdir(),'preference-v35-'));const baseJson=join(directory,'v34.json');const baseMarkdown=join(directory,'v34.md');const jsonPath=join(directory,'v35.json');const markdownPath=join(directory,'v35.md');run('tools/compile-preference-custody-manifest-v34.mjs','data/research/preference-custody/control-manifest-v34.json',baseJson,baseMarkdown);run('tools/compile-preference-custody-manifest-v35.mjs','data/research/preference-custody/control-manifest-v35.json',jsonPath,markdownPath);
const manifest=JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v35.json','utf8'));const base=JSON.parse(readFileSync(baseJson,'utf8'));const compiled=JSON.parse(readFileSync(jsonPath,'utf8'));const markdown=readFileSync(markdownPath,'utf8');assert.deepEqual(validatePreferenceCustodyManifestV35(manifest),[]);assert.deepEqual(validatePreferenceCustodyManifestV35Build(compiled),[]);assert.equal(compiled.control_count,37);assert.equal(compiled.composition.base_control_count,36);assert.equal(compiled.composition.base_promotion_requirement_count,1277);assert.equal(compiled.composition.added_promotion_requirement_count,64);assert.equal(compiled.composition.final_promotion_requirement_count,1341);assert.deepEqual(compiled.controls.slice(0,36),base.controls);assert.deepEqual(compiled.promotion_boundary.real_case_requires.slice(0,1277),base.promotion_boundary.real_case_requires);assert.equal(compiled.controls.at(-1).control_id,'PC-37');assert.equal(compiled.controls.at(-1).fixture_id,'same-hard-to-enumerate-missingness-verified-status-different-operational-states-v1');assert.deepEqual(Object.fromEntries(Object.keys(EXPECTED_HARD_TO_ENUMERATE_MISSINGNESS_METRICS).map(key=>[key,compiled.controls.at(-1).proof_summary[key]])),EXPECTED_HARD_TO_ENUMERATE_MISSINGNESS_METRICS);assert.ok(compiled.open_frontiers.includes('hard_to_enumerate_subgroup_enumeration_response_propensity_and_nonresponse_mechanism_governance'));assert.ok(compiled.open_frontiers.includes('inaccessible_source_suppression_proxy_external_frame_imputation_and_selection_assurance'));assert.ok(compiled.open_frontiers.includes('population_entry_exit_migration_merger_split_reactivation_snapshot_alignment_and_turnover_governance'));assert.ok(!compiled.open_frontiers.includes('hard_to_enumerate_population_nonresponse_missingness_mechanism_and_external_frame_assurance'));assert.equal(compiled.graph_effect,'none');assert.equal(compiled.real_world_evidence_state,'none');let previous=null;const seen=new Set();for(const event of compiled.custody_chain){assert.equal(event.previous_event_sha256,previous);for(const id of event.source_event_ids)assert.ok(seen.has(id));const unsigned={...event};delete unsigned.event_sha256;assert.equal(event.event_sha256,sha256(unsigned));seen.add(event.event_id);previous=event.event_sha256;}assert.equal(previous,compiled.custody_chain_head_sha256);assert.match(markdown,/floor v35/);assert.match(markdown,/PC-37/);assert.match(markdown,/total_unsupported_hard_to_enumerate_decisions: 700/);assert.doesNotMatch(markdown,/named population failed|actual discrimination|publicly authorized/i);
const manifestMutations=[c=>{c.schema_version='wrong';},c=>{c.manifest_id='wrong';},c=>{c.control_issue=1;},c=>{c.graph_effect='asserted';},c=>{c.counts_toward_thesis_evidence=true;},c=>{c.base_floor.expected_control_count=35;},c=>{c.extension_control.control_id='PC-36';},c=>{c.extension_control.fixture_id='wrong';},c=>{c.extension_control.failure_class='wrong';},c=>{c.extension_control.expected_build_schema='wrong';},c=>{c.extension_control.required_refusal_rules.pop();},c=>{c.identification_requirement.stage='wrong';},c=>{c.frontier_transition.resolved_base_frontier='wrong';},c=>{c.frontier_transition.successor_frontiers.pop();},c=>{c.real_case_requirements_added.pop();},c=>{c.real_case_requirements_added[0]='INVALID VALUE';},c=>{c.prohibited_inferences=[];},c=>{c.interpretation_contract.copy_ready_caveat='';}];for(const [index,mutate] of manifestMutations.entries()){const candidate=structuredClone(manifest);mutate(candidate);assert.ok(validatePreferenceCustodyManifestV35(candidate).length>0,`manifest mutation ${index+1}`);}
const buildMutations=[c=>{c.schema_version='wrong';},c=>{c.manifest_id='wrong';},c=>{c.control_issue=1;},c=>{c.status='draft';},c=>{c.graph_effect='asserted';},c=>{c.counts_toward_thesis_evidence=true;},c=>{c.conclusion_generated=true;},c=>{c.real_world_evidence_state='evidence';},c=>{c.control_count=36;},c=>{c.controls.pop();},c=>{c.composition.base_control_count=35;},c=>{c.composition.added_promotion_requirement_count=63;},c=>{c.controls.at(-1).proof_summary.total_nonresponse_unit_count=39;},c=>{c.controls.at(-1).proof_summary.binding_public_authority_supported=true;},c=>{c.open_frontiers=c.open_frontiers.filter(item=>item!=='hard_to_enumerate_subgroup_enumeration_response_propensity_and_nonresponse_mechanism_governance');},c=>{c.open_frontiers.push('hard_to_enumerate_population_nonresponse_missingness_mechanism_and_external_frame_assurance');},c=>{c.open_frontiers=c.open_frontiers.filter(item=>item!=='population_entry_exit_migration_merger_split_reactivation_snapshot_alignment_and_turnover_governance');},c=>{c.control_integrity.base_floor_qualified=false;},c=>{c.promotion_boundary.promotion_requirement_count=1340;},c=>{c.promotion_boundary.laboratory_controls_are_real_world_evidence=true;},c=>{c.custody_chain[2].payload.open_frontiers=[];},c=>{c.custody_chain_head_sha256='0'.repeat(64);},c=>{c.interpretation_contract.copy_ready_caveat='';}];for(const [index,mutate] of buildMutations.entries()){const candidate=structuredClone(compiled);mutate(candidate);assert.ok(validatePreferenceCustodyManifestV35Build(candidate).length>0,`build mutation ${index+1}`);}console.log(`Preference custody laboratory floor v35 integration tests: PASS (${manifestMutations.length+buildMutations.length} adversarial mutations)`);
