import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { REQUIRED_LINKAGE_PROBABILITY_REFUSAL_RULES, compilePreferenceLinkageProbabilityCalibrationAssuranceFixture } from '../tools/lib/preference-linkage-probability-calibration-assurance.mjs';
import { compilePreferenceCustodyManifestV41, validatePreferenceCustodyManifestV41, validatePreferenceCustodyManifestV41Build } from '../tools/lib/preference-custody-manifest-v41.mjs';
execFileSync(process.execPath, ['tools/compile-preference-custody-manifest-v41.mjs'], { stdio: 'pipe' });
const manifest=JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v41.json','utf8')); const base=JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v40.json','utf8')); const probabilityBuild=JSON.parse(readFileSync('build/research/preference-linkage-probability-calibration-assurance.json','utf8')); const probabilityFixture=JSON.parse(readFileSync('data/research/preference-custody/linkage-probability-calibration-assurance.fixture.json','utf8')); const build=JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v41.json','utf8')); const markdown=readFileSync('build/research/preference-custody-laboratory-floor-v41.md','utf8');
const baseSources = {
  manifest: JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v40.json', 'utf8')),
  baseBuild: JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v39.json', 'utf8')),
  scoreBuild: JSON.parse(readFileSync('build/research/preference-linkage-score-calibration-assurance.json', 'utf8')),
  scoreFixture: JSON.parse(readFileSync('data/research/preference-custody/linkage-score-calibration-assurance.fixture.json', 'utf8')),
  baseSources: {
    manifest: JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v39.json', 'utf8')),
    baseBuild: JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v38.json', 'utf8')),
    candidateBuild: JSON.parse(readFileSync('build/research/preference-candidate-pair-blocking-recall-assurance.json', 'utf8')),
    candidateFixture: JSON.parse(readFileSync('data/research/preference-custody/candidate-pair-blocking-recall-assurance.fixture.json', 'utf8')),
    baseSources: {
      manifest: JSON.parse(readFileSync('data/research/preference-custody/control-manifest-v38.json', 'utf8')),
      baseBuild: JSON.parse(readFileSync('build/research/preference-custody-laboratory-floor-v37.json', 'utf8')),
      confidenceBuild: JSON.parse(readFileSync('build/research/preference-linkage-confidence-adjudication-assurance.json', 'utf8')),
      confidenceFixture: JSON.parse(readFileSync('data/research/preference-custody/linkage-confidence-adjudication-assurance.fixture.json', 'utf8'))
    }
  }
};
assert.deepEqual(validatePreferenceCustodyManifestV41(manifest),[]); assert.deepEqual(validatePreferenceCustodyManifestV41Build(build,manifest,base,probabilityBuild,probabilityFixture,baseSources),[]); assert.equal(Object.isFrozen(REQUIRED_LINKAGE_PROBABILITY_REFUSAL_RULES),true,'floor must consume a frozen canonical ledger'); const frozenFloorLedger=[...REQUIRED_LINKAGE_PROBABILITY_REFUSAL_RULES]; assert.throws(()=>{REQUIRED_LINKAGE_PROBABILITY_REFUSAL_RULES[0]='arbitrary_unique_refusal_rule';},TypeError); assert.deepEqual(REQUIRED_LINKAGE_PROBABILITY_REFUSAL_RULES,frozenFloorLedger); assert.deepEqual(validatePreferenceCustodyManifestV41(manifest),[]);
assert.equal(build.control_count,43); assert.equal(build.composition.base_control_count,42); assert.equal(build.composition.extension_control_id,'PC-43'); assert.equal(build.composition.base_promotion_requirement_count,1581); assert.equal(build.composition.added_promotion_requirement_count,48); assert.equal(build.composition.final_promotion_requirement_count,1629); assert.deepEqual(build.controls.slice(0,42),base.controls); assert.deepEqual(build.composition.base_open_frontiers,base.open_frontiers); assert.equal(build.composition.manifest_snapshot_sha256.length,64); assert.equal(build.composition.base_floor_snapshot_sha256.length,64); assert.equal(build.composition.extension_snapshot_sha256.length,64);
assert.ok(!build.open_frontiers.includes('linkage_score_probability_calibration_validation_design_and_uncertainty_assurance')); assert.ok(build.open_frontiers.includes('linkage_probability_calibration_base_rate_shift_validation_sampling_and_out_of_sample_assurance')); assert.ok(build.open_frontiers.includes('linkage_uncertainty_interval_coverage_subgroup_drift_monitoring_and_recalibration_governance')); assert.ok(build.open_frontiers.includes('threshold_abstention_ambiguity_adjudication_error_monitoring_and_correction_governance')); assert.ok(build.open_frontiers.includes('eligible_pair_universe_source_combination_denominator_and_exclusion_assurance'));
const pc43=build.controls.at(-1); assert.equal(pc43.control_id,'PC-43'); assert.equal(pc43.proof_summary.world_count,8); assert.equal(pc43.proof_summary.distinct_probability_governance_signatures,8); assert.equal(pc43.proof_summary.total_miscalibrated_pairs,50); assert.equal(pc43.proof_summary.total_uncertainty_undercovered_pairs,50); assert.equal(pc43.proof_summary.total_unsupported_probability_decisions,700); assert.equal(pc43.proof_summary.complete_linkage_probability_assurance_supported_in_at_least_one_world,true); for(const value of Object.values(build.control_integrity)) assert.equal(value,true); assert.equal(build.graph_effect,'none'); assert.equal(build.counts_toward_thesis_evidence,false); assert.equal(build.conclusion_generated,false); assert.equal(build.promotion_boundary.laboratory_controls_are_real_world_evidence,false); assert.equal(build.custody_chain.length,5); assert.equal(build.custody_chain.at(-1).event_sha256,build.custody_chain_head_sha256); assert.match(markdown,/Controls:\*\* 43/); assert.match(markdown,/Promotion requirements:\*\* 1629/); assert.match(markdown,/PC-43 proof summary/);
const clone=value=>structuredClone(value); assert.ok(validatePreferenceCustodyManifestV41Build(build).length>0,'source artifacts required'); const revisedFixture=clone(probabilityFixture); revisedFixture.captured_at='2026-08-04'; const revisedProbabilityBuild=compilePreferenceLinkageProbabilityCalibrationAssuranceFixture(revisedFixture); assert.ok(validatePreferenceCustodyManifestV41Build(build,manifest,base,revisedProbabilityBuild,revisedFixture,baseSources).length>0,'valid revised PC-43 source paired with stale floor'); const revisedBase=clone(base); revisedBase.interpretation_contract.copy_ready_caveat+=' Revised source snapshot.'; assert.ok(validatePreferenceCustodyManifestV41Build(build,manifest,revisedBase,probabilityBuild,probabilityFixture,baseSources).length>0,'revised base paired with stale floor'); const revisedManifest=clone(manifest); revisedManifest.source_revision_receipt='SOURCE-REVISION-RECEIPT-V2'; assert.deepEqual(validatePreferenceCustodyManifestV41(revisedManifest),[]); const revisedManifestBuild=compilePreferenceCustodyManifestV41(revisedManifest,base,probabilityBuild,probabilityFixture,baseSources); assert.deepEqual(validatePreferenceCustodyManifestV41Build(revisedManifestBuild,revisedManifest,base,probabilityBuild,probabilityFixture,baseSources),[]); assert.ok(validatePreferenceCustodyManifestV41Build(build,revisedManifest,base,probabilityBuild,probabilityFixture,baseSources).length>0,'validator-permitted manifest revision paired with stale floor'); const substitutedRulesManifest=clone(manifest); substitutedRulesManifest.extension_control.required_refusal_rules[0]='arbitrary_unique_refusal_rule'; assert.ok(validatePreferenceCustodyManifestV41(substitutedRulesManifest).length>0,'substituted refusal rule rejected'); assert.throws(()=>compilePreferenceCustodyManifestV41(substitutedRulesManifest,base,probabilityBuild,probabilityFixture,baseSources),/exact PC-43 ledger/);
const manifestMutations=[['manifest schema',v=>{v.schema_version='invalid';}],['manifest id',v=>{v.manifest_id='invalid';}],['program issue',v=>{v.issue=593;}],['control issue',v=>{v.control_issue=927;}],['status',v=>{v.status='real';}],['graph effect',v=>{v.graph_effect='asserted';}],['thesis evidence',v=>{v.counts_toward_thesis_evidence=true;}],['base id',v=>{v.base_floor.manifest_id='invalid';}],['base path',v=>{v.base_floor.source_manifest_path='invalid';}],['base schema',v=>{v.base_floor.expected_build_schema='invalid';}],['base count',v=>{v.base_floor.expected_control_count=41;}],['control id',v=>{v.extension_control.control_id='PC-42';}],['fixture id',v=>{v.extension_control.fixture_id='invalid';}],['failure class',v=>{v.extension_control.failure_class='invalid';}],['build schema',v=>{v.extension_control.expected_build_schema='invalid';}],['refusal rule',v=>{v.extension_control.required_refusal_rules.pop();}],['refusal substitution',v=>{v.extension_control.required_refusal_rules[0]='arbitrary_unique_refusal_rule';}],['identification stage',v=>{v.identification_requirement.stage='invalid';}],['resolved frontier',v=>{v.frontier_transition.resolved_base_frontier='invalid';}],['successor frontier',v=>{v.frontier_transition.successor_frontiers.pop();}],['requirements',v=>{v.real_case_requirements_added.pop();}],['interpretation',v=>{v.interpretation_contract.copy_ready_caveat='';}]];
const buildMutations=[['build schema',v=>{v.schema_version='invalid';}],['build identity',v=>{v.manifest_id='invalid';}],['build status',v=>{v.status='invalid';}],['build graph effect',v=>{v.graph_effect='asserted';}],['build evidence state',v=>{v.real_world_evidence_state='claimed';}],['build thesis evidence',v=>{v.counts_toward_thesis_evidence=true;}],['build conclusion',v=>{v.conclusion_generated=true;}],['build control count',v=>{v.control_count=42;}],['build controls',v=>{v.controls.pop();}],['preserved base control',v=>{v.controls[0].failure_class='tampered';}],['preserved base requirement',v=>{v.promotion_boundary.real_case_requires[0]='tampered';}],['composition base id',v=>{v.composition.base_manifest_id='invalid';}],['composition base count',v=>{v.composition.base_control_count=41;}],['composition extension id',v=>{v.composition.extension_control_id='PC-42';}],['manifest snapshot hash',v=>{v.composition.manifest_snapshot_sha256='a'.repeat(64);}],['base snapshot hash',v=>{v.composition.base_floor_snapshot_sha256='0'.repeat(64);}],['extension snapshot hash',v=>{v.composition.extension_snapshot_sha256='f'.repeat(64);}],['base requirement count',v=>{v.composition.base_promotion_requirement_count=1580;}],['added requirement count',v=>{v.composition.added_promotion_requirement_count=47;}],['final requirement count',v=>{v.composition.final_promotion_requirement_count=1628;}],['resolved frontier retained',v=>{v.open_frontiers.push('linkage_score_probability_calibration_validation_design_and_uncertainty_assurance');}],['PC42 sibling lost',v=>{v.open_frontiers=v.open_frontiers.filter(item=>item!=='threshold_abstention_ambiguity_adjudication_error_monitoring_and_correction_governance');}],['integrity flag',v=>{v.control_integrity.base_floor_qualified=false;}],['PC43 metric',v=>{v.controls.at(-1).proof_summary.total_miscalibrated_pairs=49;}],['custody tamper',v=>{v.custody_chain[2].payload.transition.resolved_base_frontier='tampered';}]];
assert.equal(manifestMutations.length+buildMutations.length,47); for(const [label,mutate] of manifestMutations){const value=clone(manifest);mutate(value);assert.ok(validatePreferenceCustodyManifestV41(value).length>0,label);} for(const [label,mutate] of buildMutations){const value=clone(build);mutate(value);assert.ok(validatePreferenceCustodyManifestV41Build(value,manifest,base,probabilityBuild,probabilityFixture,baseSources).length>0,label);} console.log('Preference custody floor v41 adversarial tests: PASS (47 mutations plus complete-manifest and source-binding succession checks)');
