import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { compilePreferenceCustodyManifestV49, loadPreferenceCustodyV48SourceBundle, preferenceCustodyManifestV49Snapshot, validatePreferenceCustodyManifestV49, validatePreferenceCustodyManifestV49Build } from '../tools/lib/preference-custody-manifest-v49.mjs';
const load=path=>JSON.parse(readFileSync(path,'utf8'));const clone=value=>structuredClone(value);
const manifest=load('data/research/preference-custody/control-manifest-v49.json');
const baseBuildPath='build/research/preference-custody-laboratory-floor-v48.json';
const targetBuildPath='build/research/preference-linkage-source-review-reproducible-build-artifact-provenance-execution-attestation-assurance.json';
if(!existsSync(baseBuildPath))execFileSync(process.execPath,['tools/compile-preference-custody-manifest-v48.mjs'],{stdio:'inherit'});
if(!existsSync(targetBuildPath))execFileSync(process.execPath,['tools/compile-preference-linkage-source-review-reproducible-build-artifact-provenance-execution-attestation-assurance.mjs'],{stdio:'inherit'});
const baseBuild=load(baseBuildPath);const targetBuild=load(targetBuildPath);const targetFixture=load(manifest.extension_control.source_fixture_path);const baseSources=loadPreferenceCustodyV48SourceBundle(load);const compiled=compilePreferenceCustodyManifestV49(manifest,baseBuild,targetBuild,targetFixture,baseSources);const buildPath='build/research/preference-custody-laboratory-floor-v49.json';const build=existsSync(buildPath)?load(buildPath):compiled;
assert.deepEqual(validatePreferenceCustodyManifestV49(manifest),[]);assert.deepEqual(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,baseSources),[]);assert.deepEqual(compiled,build);assert.equal(preferenceCustodyManifestV49Snapshot(manifest),'654f9f1d4262fa613f28dcc4d23615773725590e2483f52cdac51b10a796f415');assert.equal(build.control_count,51);assert.equal(build.composition.base_control_count,50);assert.equal(build.composition.added_promotion_requirement_count,52);assert.equal(build.promotion_boundary.promotion_requirement_count,2022);assert.equal(build.controls.at(-1).control_id,'PC-51');assert.equal(build.controls.at(-1).complete_assurance_world_count,1);assert.equal(build.graph_effect,'none');assert.equal(build.real_world_evidence_state,'none');assert.ok(!build.open_frontiers.includes(manifest.frontier_transition.resolved_base_frontier));for(const frontier of manifest.frontier_transition.successor_frontiers)assert.ok(build.open_frontiers.includes(frontier));
const mutateLeaf=value=>{if(typeof value==='boolean')return!value;if(typeof value==='number')return Number.isInteger(value)?value+1:value+0.01;if(typeof value==='string')return`${value}__mutation`;if(value===null)return'mutation';throw new Error(`unsupported leaf ${typeof value}`);};function leaves(value,path=[]){if(value===null||typeof value!=='object')return[{path,value}];const out=[];if(Array.isArray(value))value.forEach((item,index)=>out.push(...leaves(item,[...path,index])));else Object.entries(value).forEach(([key,item])=>out.push(...leaves(item,[...path,key])));return out;}function setAt(root,path,value){let cursor=root;for(const key of path.slice(0,-1))cursor=cursor[key];cursor[path.at(-1)]=value;}function manifestRefused(candidate,label){const errors=validatePreferenceCustodyManifestV49(candidate);assert.ok(errors.length>0,`${label} must be refused`);}function buildRefused(candidate,label){const errors=validatePreferenceCustodyManifestV49Build(candidate,manifest,baseBuild,targetBuild,targetFixture,baseSources);assert.ok(errors.length>0,`${label} must be refused`);}
let manifestMutationCount=0;for(const {path,value} of leaves(manifest)){const candidate=clone(manifest);setAt(candidate,path,mutateLeaf(value));manifestRefused(candidate,`manifest leaf ${path.join('.')}`);manifestMutationCount+=1;}assert.ok(manifestMutationCount>=110,`expected broad manifest mutation census, observed ${manifestMutationCount}`);
const extra=clone(manifest);extra.unapproved=true;manifestRefused(extra,'extra manifest key');const nested=clone(manifest);nested.extension_control.unapproved=true;manifestRefused(nested,'extra extension key');const duplicate=clone(manifest);duplicate.real_case_requirements_added.push(duplicate.real_case_requirements_added[0]);manifestRefused(duplicate,'duplicate promotion requirement');
for(const malformed of [null,0,'invalid',false,[]]){assert.doesNotThrow(()=>validatePreferenceCustodyManifestV49(malformed));manifestRefused(malformed,`malformed manifest ${String(malformed)}`);}for(const field of ['base_floor','extension_control','identification_requirement','frontier_transition','interpretation_contract'])for(const replacement of [null,0]){const candidate=clone(manifest);candidate[field]=replacement;assert.doesNotThrow(()=>validatePreferenceCustodyManifestV49(candidate));manifestRefused(candidate,`${field} ${replacement}`);}
const aliasSources=clone(baseSources);aliasSources.targetFixture=targetFixture;assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,aliasSources).length>0,'cross-root alias must be refused');const deepExtra=clone(baseSources);deepExtra.baseSources.manifest.unapproved=true;assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,deepExtra).length>0,'deep source key must be refused');const postdated=clone(baseSources);postdated.manifest.captured_at='2026-08-07';assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,postdated).length>0,'postdated base source must be refused');const cycle=clone(baseSources);cycle.self=cycle;assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,cycle).length>0,'cyclic source bundle must be refused');const proxy=new Proxy(clone(baseSources),{ownKeys(){throw new Error('opaque');}});assert.doesNotThrow(()=>validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,proxy));assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,proxy).length>0,'proxy source bundle must be refused');
let buildMutationCount=0;const buildLeaves=leaves(build);const stride=Math.max(1,Math.ceil(buildLeaves.length/18));for(let i=0;i<buildLeaves.length;i+=stride){const {path,value}=buildLeaves[i];const candidate=clone(build);setAt(candidate,path,mutateLeaf(value));buildRefused(candidate,`build leaf ${path.join('.')}`);buildMutationCount+=1;}assert.ok(buildMutationCount>=15,`expected bounded full-stack build tamper coverage, observed ${buildMutationCount}`);for(const field of ['controls','identification_requirements','refusal_rule_union','open_frontiers','custody_chain','prohibited_inferences','composition','control_integrity','frontier_transition','promotion_boundary','interpretation_contract']){const candidate=clone(build);candidate[field]=0;assert.doesNotThrow(()=>validatePreferenceCustodyManifestV49Build(candidate,manifest,baseBuild,targetBuild,targetFixture,baseSources));buildRefused(candidate,`scalar ${field}`);}
const temp=mkdtempSync(join(tmpdir(),'pc51-v49-null-manifest-'));try{const nullPath=join(temp,'null.json');writeFileSync(nullPath,'null\n');const compileCli=spawnSync(process.execPath,['tools/compile-preference-custody-manifest-v49.mjs',nullPath,join(temp,'out.json'),join(temp,'out.md')],{encoding:'utf8'});assert.equal(compileCli.status,1);assert.match(`${compileCli.stdout}\n${compileCli.stderr}`,/Preference Custody v49 manifest must be an object/);assert.doesNotMatch(`${compileCli.stdout}\n${compileCli.stderr}`,/TypeError|ENOENT/);const validateCli=spawnSync(process.execPath,['tools/validate-preference-custody-manifest-v49.mjs',nullPath,join(temp,'missing.json')],{encoding:'utf8'});assert.equal(validateCli.status,1);assert.match(validateCli.stderr,/Preference Custody v49 manifest must be an object/);assert.doesNotMatch(`${validateCli.stdout}\n${validateCli.stderr}`,/TypeError|ENOENT/);}finally{rmSync(temp,{recursive:true,force:true});}
const namedManifestArray=clone(manifest); namedManifestArray.real_case_requirements_added.unapproved=true; manifestRefused(namedManifestArray,'named manifest array property');
const namedSourceArray=clone(baseSources); namedSourceArray.targetBuild.worlds.unapproved=true; assert.ok(validatePreferenceCustodyManifestV49Build(build,manifest,baseBuild,targetBuild,targetFixture,namedSourceArray).length>0,'named source-bundle array property must be refused');
const namedFloorBuildArray=clone(build); namedFloorBuildArray.controls.unapproved=true; buildRefused(namedFloorBuildArray,'named floor-build array property');
console.log(`validated Preference Custody floor v49 with ${manifestMutationCount} manifest mutations and ${buildMutationCount} build tamper checks`);
