import assert from 'node:assert/strict';
import fs from 'node:fs';
import { buildReportFrontier, REPORT_FRONTIER_SCHEMA_VERSION } from '../tools/build-report-frontier.mjs';
import { renderReportFrontier } from '../tools/render-report-frontier.mjs';
import { readJson } from '../tools/lib/ledger.mjs';

const frontier = buildReportFrontier();
const emitted = readJson('build/report-frontier.json');
assert.deepEqual(emitted, frontier, 'the report frontier must be deterministic');
assert.deepEqual(buildReportFrontier(), frontier, 'a second build must not change the frontier');
const rendered = renderReportFrontier();
assert.equal(rendered.html, fs.readFileSync(rendered.output_path, 'utf8'));
assert.deepEqual(rendered.frontier, frontier);
assert.equal(rendered.output_path, 'reports/index.html');
assert.equal(frontier.schema_version, REPORT_FRONTIER_SCHEMA_VERSION);
assert.equal(frontier.graph_effect, 'none');
assert.equal(frontier.conclusion_generated, false);
assert.deepEqual(frontier.transition_order, ['intake_or_projection','case_ledger','structured_report','independent_review','approved_publication']);
assert.equal(frontier.waterline.stage, 'structured_report');
assert.equal(frontier.waterline.next_transition, 'provisional_publication_and_adversarial_challenge');
assert.match(frontier.waterline.definition, /not a quality score or ranking/i);
assert.equal(frontier.totals.cases, frontier.cases.length);
assert.equal(frontier.totals.structured_reports, 2);
assert.equal(frontier.totals.approved_publications, 0);
assert.equal(frontier.totals.reports_open_to_independent_challenge, 2);
assert.equal(frontier.totals.reports_with_bounded_working_judgment, 2);
assert.equal(frontier.totals.provisional_publication_eligible, 2);
assert.equal(frontier.totals.case_trails, 10);
assert.equal(frontier.totals.intake_trails, 18);
assert.equal(frontier.totals.report_linked_trails, 9);
const byCase = new Map(frontier.cases.map(item => [item.case_id, item]));
for (const caseId of ['anduril-access-ownership','arcadia-field-autopsy']) {
  const item = byCase.get(caseId);
  assert.ok(item);
  assert.equal(item.case_state, 'case_ledger');
  assert.equal(item.current_stage, 'structured_report');
  assert.equal(item.next_transition, 'provisional_publication_and_adversarial_challenge');
  assert.equal(item.judgment_state, 'bounded_working_judgment');
  assert.equal(item.provisional_publication_eligible, true);
  assert.equal(item.review_dependency.required_to_decide, false);
  assert.deepEqual(item.blockers, []);
  assert.ok(item.clearance_conditions.includes('independent_reviewer_missing'));
  assert.ok(item.clearance_conditions.includes('review_date_missing'));
}
const anduril = byCase.get('anduril-access-ownership');
assert.equal(anduril.source_trails_linked_to_report, 0);
assert.ok(anduril.scope_limits.includes('9_claims_review_required'));
const arcadia = byCase.get('arcadia-field-autopsy');
assert.equal(arcadia.trails, 10);
assert.equal(arcadia.source_trails_linked_to_report, 9);
assert.ok(arcadia.scope_limits.some(reason => /qualifications_inherited_from_case_boundary/.test(reason)));
assert.ok(arcadia.scope_limits.some(reason => /unsequenced_case_claims/.test(reason)));
const swarmForge = byCase.get('field-autopsy-03');
assert.equal(swarmForge.current_stage, 'case_ledger');
assert.equal(swarmForge.next_transition, 'evidence_upgrade');
assert.ok(swarmForge.blockers.includes('no_verified_claims'));
const ukAi = byCase.get('uk-ai-policy');
assert.equal(ukAi.case_state, 'legacy_projection');
assert.equal(ukAi.current_stage, 'intake_or_projection');
assert.equal(ukAi.next_transition, 'case_ledger_migration');
assert.ok(ukAi.blockers.includes('canonical_case_ledger_missing'));
const arcadiaTrails = new Map(frontier.trail_programs.map(item => [item.program_id, item])).get('case:arcadia-field-autopsy');
assert.equal(arcadiaTrails.totals.trails, 10);
assert.equal(arcadiaTrails.totals.linked_to_report_workplan, 9);
assert.equal(arcadiaTrails.totals.non_terminal, 10);
assert.ok(arcadiaTrails.trails.find(item => item.trail_id === 'trail-transcript-recovery').linked_to_report_workplan === false);
console.log('report frontier: OK');
