import assert from 'node:assert/strict';
import {loadObjects,validateObjects} from '../tools/validate-status-sovereignty-rd-wave03-rd04-next-minimum-frontier-route-discovery-protocol.mjs';
const base=loadObjects();
const clone=value=>structuredClone(value);
let refusals=0;
const reject=mutate=>{const value=clone(base);mutate(value);assert.throws(()=>validateObjects(value));refusals+=1;};
reject(o=>o.selection.state_denominator=49);
reject(o=>o.selection.field_denominator_per_state=8);
reject(o=>o.selection.terminal_cells_before=219);
reject(o=>o.selection.open_substantive_cells_before=191);
reject(o=>o.selection.class_closed=true);
reject(o=>o.selection.outside_human_dependency=true);
reject(o=>o.predecessor.rd04_successor_overlap_count=1);
reject(o=>o.query.maximum_attempts_per_request=2);
reject(o=>o.query.result_spawned_source_fetches=1);
reject(o=>o.query.cross_host_redirects_allowed=true);
reject(o=>o.query.automatic_source_admission=true);
reject(o=>o.query.outside_human_dependency=true);
reject(o=>o.protocol.source_requests_executed=1);
reject(o=>o.protocol.source_admissions=1);
reject(o=>o.protocol.field_mutations=1);
reject(o=>o.protocol.class_closed=true);
reject(o=>o.protocol.graph_effect='candidate');
for (let index=0;index<base.protocol.obligations.length;index+=1) {
  reject(o=>o.protocol.obligations.splice(index,1));
  reject(o=>o.protocol.obligations[index].automatic_source_admission=true);
  reject(o=>o.protocol.obligations[index].automatic_field_classification=true);
  reject(o=>o.protocol.obligations[index].terminalizes_field=true);
  reject(o=>o.protocol.obligations[index].maximum_candidate_urls=13);
  reject(o=>o.protocol.obligations[index].maximum_discovery_requests=7);
  reject(o=>o.protocol.obligations[index].official_roots[0]='https://example.com/');
}
console.log(`rd04_next_frontier_protocol_adversarial_refusals=${refusals}`);
