#!/usr/bin/env node
import assert from 'node:assert/strict';
import { buildExpectedBundle, checkCommittedBundle } from '../tools/build-status-sovereignty-rd-wave03-rd01-methodology-correction.mjs';
import { validateBundleShape, validateRd01Wave03 } from '../tools/validate-status-sovereignty-rd-wave03-rd01-methodology-correction.mjs';

validateRd01Wave03();
checkCommittedBundle();
const clone = () => structuredClone(buildExpectedBundle());
const cases = [
  ['capture schema', b => { b.capture.schema_version = 'bad'; }],
  ['capture head', b => { b.capture.target_head = '0'.repeat(40); }],
  ['protocol routes', b => { b.capture.fixed_protocol.fixed_routes = 29; }],
  ['protocol recursion', b => { b.capture.fixed_protocol.result_spawned_requests = 1; }],
  ['fixed run', b => { b.capture.fixed_route_capture.workflow_run = 1; }],
  ['fixed artifact', b => { b.capture.fixed_route_capture.artifact_id = 1; }],
  ['fixed archive', b => { b.capture.fixed_route_capture.artifact_zip_sha256 = '0'.repeat(64); }],
  ['fixed manifest', b => { b.capture.fixed_route_capture.manifest_combined_sha256 = '0'.repeat(64); }],
  ['fixed attempts', b => { b.capture.fixed_route_capture.route_attempts = 29; }],
  ['fixed HTTP', b => { b.capture.fixed_route_capture.http_success_routes = 29; }],
  ['candidate count', b => { b.capture.fixed_route_capture.candidate_rows = 268; }],
  ['candidate admitted', b => { b.capture.fixed_route_capture.admitted_candidate_sources = 1; }],
  ['PDF run', b => { b.capture.report_pdf_capture.workflow_run = 1; }],
  ['PDF artifact', b => { b.capture.report_pdf_capture.artifact_id = 1; }],
  ['PDF archive', b => { b.capture.report_pdf_capture.artifact_zip_sha256 = '0'.repeat(64); }],
  ['PDF manifest', b => { b.capture.report_pdf_capture.manifest_combined_sha256 = '0'.repeat(64); }],
  ['PDF denominator', b => { b.capture.report_pdf_capture.pdfs_observed = 2; }],
  ['edition source removed', b => { b.capture.edition_sources.pop(); }],
  ['edition source reordered', b => { b.capture.edition_sources.reverse(); }],
  ['direct body digest', b => { b.capture.edition_sources[0].direct_html.sha256 = '0'.repeat(64); }],
  ['PDF body digest', b => { b.capture.edition_sources[1].report_pdf.sha256 = '0'.repeat(64); }],
  ['query denominator', b => { b.capture.edition_sources[2].fixed_candidate_query_route_ids.pop(); }],
  ['OCR invented', b => { b.capture.inspection.ocr_used = true; }],
  ['external review', b => { b.capture.inspection.external_review = true; }],
  ['capture outside human', b => { b.capture.authority.outside_human_dependency = true; }],
  ['capture superiority', b => { b.capture.authority.technical_superiority_finding = true; }],
  ['matrix schema', b => { b.matrix.schema_version = 'bad'; }],
  ['matrix label', b => { b.matrix.class_label = 'corrections'; }],
  ['required field removed', b => { b.matrix.required_fields.pop(); }],
  ['row removed', b => { b.matrix.rows.pop(); }],
  ['row reordered', b => { b.matrix.rows.reverse(); }],
  ['duplicate unit', b => { b.matrix.rows[1].unit_id = b.matrix.rows[0].unit_id; }],
  ['field removed', b => { delete b.matrix.rows[0].fields.published_appeal_or_challenge_route; }],
  ['field reopened', b => { b.matrix.rows[0].fields.published_correction_or_errata_record.state = 'unclassified'; }],
  ['field protocol incomplete', b => { b.matrix.rows[0].fields.published_correction_or_errata_record.fixed_protocol_complete = false; }],
  ['field not terminal', b => { b.matrix.rows[0].fields.published_correction_or_errata_record.terminal_for_class_closure = false; }],
  ['unavailable value invented', b => { b.matrix.rows[0].fields.published_correction_or_errata_record.value = { correction: false }; }],
  ['field sources removed', b => { b.matrix.rows[1].fields.published_appeal_or_challenge_route.source_ids = []; }],
  ['row reopened', b => { b.matrix.rows[1].row_result.row_closed = false; }],
  ['row terminal count', b => { b.matrix.rows[1].row_result.terminal_fields = 7; }],
  ['2024 version erased', b => { b.matrix.rows[0].fields.version_exception_and_override_custody_where_public.value.headcount_growth_scoring_sensitivity_increased = false; }],
  ['2025 SpaceX erased', b => { b.matrix.rows[1].fields.version_exception_and_override_custody_where_public.value.spacex_isolated_in_some_analysis = false; }],
  ['2026 contracting erased', b => { b.matrix.rows[2].fields.methodology_identity_and_published_input_description.value.published_inputs.shift(); }],
  ['prospective converted complete', b => { b.matrix.rows[2].fields.published_re_evaluation_reranking_or_reconsideration_record.value.completed_2026_reranking_or_changed_disposition = true; }],
  ['prospective scope changed', b => { b.matrix.rows[2].fields.published_re_evaluation_reranking_or_reconsideration_record.value.statement_scope = '2026 reranking'; }],
  ['matrix required count', b => { b.matrix.counts.required_fields = 23; }],
  ['matrix observed count', b => { b.matrix.counts.observed_fields = 15; }],
  ['matrix unavailable count', b => { b.matrix.counts.not_publicly_recovered_fields = 7; }],
  ['correction invented', b => { b.matrix.counts.completed_correction_or_errata_records = 1; }],
  ['appeal invented', b => { b.matrix.counts.published_formal_appeal_routes = 1; }],
  ['reranking invented', b => { b.matrix.counts.completed_reranking_or_changed_disposition_records = 1; }],
  ['matrix reopened', b => { b.matrix.current_result.class_closed = false; }],
  ['prospective boundary cleared', b => { b.matrix.current_result.prospective_future_re_evaluation_preserved_without_completion_claim = false; }],
  ['source absence collapse', b => { b.matrix.boundaries.source_unavailability_is_event_absence = true; }],
  ['method change collapse', b => { b.matrix.boundaries.methodology_change_is_correction = true; }],
  ['future statement collapse', b => { b.matrix.boundaries.future_re_evaluation_statement_is_completed_re_evaluation = true; }],
  ['matrix graph', b => { b.matrix.authority.graph_effect = 'changed'; }],
  ['matrix coordination', b => { b.matrix.authority.coordination_finding = true; }],
  ['summary count drift', b => { b.summary.counts.terminal_fields = 23; }],
  ['summary reopened', b => { b.summary.class_closed = false; }],
  ['summary authority', b => { b.summary.authority.external_reviews = 1; }],
  ['receipt source PR', b => { b.classReceipt.source_pr = 999; }],
  ['receipt label', b => { b.classReceipt.class_label = 'partial'; }],
  ['receipt reopened', b => { b.classReceipt.class_closed = false; }],
  ['receipt basis removed', b => { b.classReceipt.closure_basis.pop(); }],
  ['receipt capture digest', b => { b.classReceipt.source_custody.capture_receipt_sha256 = '0'.repeat(64); }],
  ['receipt extra pass', b => { b.classReceipt.unresolved_limit.automatic_additional_search_pass_authorized = true; }],
  ['receipt event absence', b => { b.classReceipt.unresolved_limit.missing_records_are_not_event_absence = false; }],
  ['receipt authority', b => { b.classReceipt.authority.selector_accuracy_finding = true; }],
  ['manifest entry removed', b => { b.manifest.entries.pop(); }],
  ['manifest order', b => { b.manifest.entries.reverse(); }],
  ['manifest digest', b => { b.manifest.combined_sha256 = '0'.repeat(64); }],
  ['closure class', b => { b.closure.class_id = 'RD-01-C05'; }],
  ['closure reopened', b => { b.closure.class_closed = false; }],
  ['closure manifest', b => { b.closure.product.manifest_combined_sha256 = '0'.repeat(64); }],
  ['closure atlas open', b => { b.closure.residual_atlas_effect_if_promoted_after_wave02_six_closures.open_after = 34; }],
  ['closure wave complete', b => { b.closure.residual_atlas_effect_if_promoted_after_wave02_six_closures.wave_complete = true; }],
  ['schema root opened', b => { b.schema.additionalProperties = true; }],
  ['schema class', b => { b.schema.properties.class_id.const = 'RD-01-C05'; }],
  ['schema count', b => { b.schema.properties.counts.properties.required_fields.const = 23; }]
];
for (const [name, mutate] of cases) {
  const bundle = clone(); mutate(bundle);
  assert.throws(() => validateBundleShape(bundle), undefined, name);
}
console.log(`RD-01 Wave-03 terminal adversarial suite: ${cases.length} mutations refused`);
