#!/usr/bin/env node
import assert from 'node:assert/strict';
import { loadContext,validateContext } from '../tools/validate-status-sovereignty-rd04-snap-source-availability-a02.mjs';
const clean=loadContext();assert.deepEqual(validateContext(clean),[],'clean acquisition must validate');
const clone=()=>structuredClone(clean);const state=(c,code)=>c.states.find(r=>r.state===code);const source=(c,id)=>c.sources.find(r=>r.source_id===id);
const mutations=[
 ['state removed',c=>c.states.pop(),'Exact fifty-state universe'],['DC added',c=>state(c,'AL').state='DC','District of Columbia'],['state duplicate',c=>state(c,'AK').state='AL','State identity uniqueness'],
 ['declared search slot omitted',c=>state(c,'AL').fixed_search_slots_declared=3,'declared search slots'],['search receipt invented',c=>state(c,'AL').search_execution_receipts_preserved=1,'const changed'],['search custody laundered',c=>state(c,'AL').search_execution_custody='complete','const changed'],['catalogue score laundered',c=>state(c,'AL').source_catalogue_scoring_status='complete_search','const changed'],['search absence laundered',c=>state(c,'AL').search_absence_semantics='record_absent','const changed'],
 ['protocol receipt invented',c=>c.core.selection_contract.per_search_execution_receipts_preserved=true,'const changed'],['query logs invented',c=>c.core.selection_contract.per_state_query_result_logs_preserved=true,'const changed'],['search reproduction invented',c=>c.core.selection_contract.independent_fixed_search_reproduction_complete=true,'const changed'],['selection gate promoted',c=>c.selection.selection_gate_complete=true,'const changed'],['final state invented',c=>c.selection.final_selected_state='CA','type mismatch null'],
 ['California weight',c=>c.core.selection_contract.california_incumbency_weight=1,'California incumbency weight'],['tie breaker',c=>c.core.selection_contract.substantive_tiebreaker='generosity','Substantive tiebreaker'],
 ['score inflated',c=>state(c,'AL').dimension_scores.D4=3,'score outside 0..2'],['total drift',c=>state(c,'CA').total_score=13,'total score'],['positive without evidence',c=>state(c,'CA').dimension_evidence.D1=[],'positive score lacks evidence'],
 ['zero with evidence',c=>state(c,'AL').dimension_evidence.D4=['NV-RESTORE'],'zero score carries evidence'],['unknown source',c=>state(c,'CA').dimension_evidence.D1=['UNKNOWN'],'unknown source'],
 ['source scope',c=>{state(c,'AL').dimension_scores.D4=2;state(c,'AL').dimension_evidence.D4=['NV-RESTORE'];state(c,'AL').total_score=6;},'source scope mismatch'],
 ['source dimension',c=>state(c,'CA').dimension_evidence.D1=['FNS-HOUSEHOLDS'],'source dimension mismatch'],['non HTTPS',c=>source(c,'FNS-OPTIONS').url='http://www.fns.usda.gov/x','source URL must be HTTPS'],
 ['non official host',c=>source(c,'FNS-OPTIONS').url='https://example.com/x','non-official host'],['Nevada count removed',c=>{state(c,'NV').dimension_scores.D4=0;state(c,'NV').dimension_evidence.D4=[];state(c,'NV').total_score=4;},'Observed sanction/restoration count custody'],
 ['invented California count',c=>{state(c,'CA').dimension_scores.D4=2;state(c,'CA').dimension_evidence.D4=['NV-RESTORE'];state(c,'CA').total_score=14;},'source scope mismatch'],
 ['measured state stripped',c=>{state(c,'VT').dimension_scores.D7=0;state(c,'VT').dimension_evidence.D7=[];state(c,'VT').total_score=4;},'Measured outcome state set'],
 ['D8 level two',c=>{state(c,'AL').dimension_scores.D8=2;state(c,'AL').total_score=5;},'No state may receive D8 level two'],['top set stripped',c=>c.selection.provisional_highest_coverage_set=['CA'],'const changed'],
 ['unique California',c=>c.selection.unique_highest_state='CA','type mismatch null'],['rejected removed',c=>c.selection.rejected_shortlist.pop(),'minItems 45'],['terminal promoted',c=>c.core.current_result.terminal_state='partial_correction_control','Terminal receipt'],
 ['current gate promoted',c=>c.core.current_result.fifty_state_source_availability_selection_gate_complete=true,'Selection gate current result'],['current receipts invented',c=>c.core.current_result.search_execution_receipts_recovered=true,'Search receipt current result'],
 ['residual closure',c=>c.core.counts.residual_classes_closed=1,'Residual closure count'],['review change',c=>c.core.current_result.reviewed_disposition_changed=true,'Reviewed disposition'],
 ['graph effect',c=>c.core.current_result.graph_effect='edge','Graph effect'],['publication effect',c=>c.core.current_result.publication_effect='public','Publication effect'],
 ['policy boundary removed',c=>c.core.boundaries.retrieval_score_is_policy_quality=true,'Boundary retrieval_score_is_policy_quality'],['catalogue gate boundary removed',c=>c.core.boundaries.provisional_catalogue_frontier_is_completed_selection_gate=true,'Boundary provisional_catalogue_frontier_is_completed_selection_gate'],['parent blob drift',c=>c.core.parent_acquisition_git_blob_sha1='0'.repeat(40),'const changed'],
 ['manifest drift',c=>c.manifest.combined_sha256='f'.repeat(64),'Exact-byte release manifest'],['summary tie drift',c=>c.buildSummary.selection_result.provisional_highest_coverage_set=['CA'],'Build summary drift'],['summary gate promoted',c=>c.buildSummary.selection_result.selection_gate_complete=true,'Build summary drift'],
 ['HTML noindex removed',c=>c.html=c.html.replace('noindex,nofollow','index,follow'),'HTML noindex boundary missing'],['HTML tie removed',c=>c.html=c.html.replace('CA CT KS KY WA PROVISIONALLY TIED','CA UNIQUE'),'HTML provisional tied-set boundary missing'],['HTML gate closed',c=>c.html=c.html.replace('SELECTION GATE OPEN','SELECTION GATE COMPLETE'),'HTML selection-gate boundary missing'],['HTML query receipts invented',c=>c.html=c.html.replace('QUERY RECEIPTS: 0/200 PRESERVED','QUERY RECEIPTS: 200/200 PRESERVED'),'HTML search-custody boundary missing'],
 ['schema closure weakened',c=>c.schemas.core.properties.issue.const=667,'core.issue: const changed']
];
for(const [name,mutate,expected] of mutations){const c=clone();mutate(c);const errors=validateContext(c,{skipGenerated:name==='schema closure weakened'});assert(errors.some(e=>e.includes(expected)),`${name}: expected ${expected}; observed ${JSON.stringify(errors)}`);}
console.log(`status-sovereignty-rd04-snap-source-availability-a02.test: ${mutations.length} adversarial mutations PASS`);
