#!/usr/bin/env node
import assert from 'node:assert/strict';
import { loadWave02IntakeContext, validateWave02Intake } from '../tools/validate-status-sovereignty-wave-02-intake.mjs';
const clean=loadWave02IntakeContext();assert.deepEqual(validateWave02Intake(clean),[],'clean intake must validate');
const clone=()=>Object.fromEntries(Object.entries(clean).map(([k,v])=>[k,typeof v==='string'?v:structuredClone(v)]));
const muts=[
['identity',c=>c.intake.intake_id='OTHER','intake identity'],['status',c=>c.intake.status='canonical','intake status'],['lane',c=>c.intake.candidate_lane_ids.pop(),'lane denominator'],['source count',c=>c.intake.counts.source_records=13,'count source_records'],['review',c=>c.intake.counts.maintainer_reviewed=1,'count maintainer_reviewed'],['field',c=>c.intake.current_result.field_wave_executed=true,'field-wave state'],['publication',c=>c.intake.current_result.publication_status='public','publication state'],['graph',c=>c.intake.current_result.graph_effect='edge','graph effect'],['source remove',c=>c.sources.records.pop(),'source count'],['source duplicate',c=>c.sources.records[1].source_id=c.sources.records[0].source_id,'source IDs duplicate'],['source hash',c=>c.sources.records[0].retrieval.normalized_fact_record_sha256='f'.repeat(64),'normalized fact hash'],['source authority',c=>c.sources.records[0].authority='official_primary','source-provided authority'],['candidate remove',c=>c.intake.observations.pop(),'candidate count'],['candidate order',c=>c.intake.observations.reverse(),'candidate order'],['candidate review',c=>c.intake.observations[0].review_state='maintainer_reviewed','review state'],['candidate graph',c=>c.intake.observations[0].graph_effect='edge','graph effect'],['compact',c=>c.intake.observations[0].disposition='supported_bounded_compact','complete compact self-awarded'],['orphan',c=>c.intake.observations[0].source_ids=['SSC-W02-I-S999'],'orphan source'],['facts',c=>c.intake.observations[0].observed_facts=[],'facts incomplete'],['alternatives',c=>c.intake.observations[0].alternative_explanations=[],'alternatives incomplete'],['parent wave',c=>c.wave01.counts.observations=15,'Wave 01 observations'],['current lane rollback',c=>c.fanout.lanes.find(x=>x.lane_id==='SSC-F01').execution.started=false,'SSC-F01: current lane started'],['frozen parent rewrite',c=>c.buildReport.frozen_parent_state.previously_zero_lanes[0].parent_started=true,'SSC-F01: frozen parent started'],['obligation',c=>c.acquisition.counts.closed=1,'acquisition closed'],['manifest',c=>c.manifest.combined_sha256='f'.repeat(64),'historical intake release digest'],['report',c=>c.buildReport.counts.candidate_observations=7,'build/public report drift'],['html',c=>c.html=c.html.replace('INTAKE ONLY · UNREVIEWED 8/8 · FIELD WAVE NOT EXECUTED','CANONICAL'),'HTML authority warning missing']];
for(const[name,mutate,needle]of muts){const c=clone();mutate(c);const errors=validateWave02Intake(c);assert(errors.some(x=>x.includes(needle)),`${name}: expected ${needle}; observed ${JSON.stringify(errors)}`)}
console.log(`status-sovereignty-wave-02-intake.test: ${muts.length} adversarial mutations PASS`);
