#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import {
  ROOT,
  EXECUTION_PATH,
  SOURCE_PATH,
  REPLAY_PATH,
  SCHEMA_PATH,
  validateBundle
} from '../tools/validate-status-sovereignty-rd-wave03-rd02-leaf-replay.mjs';

const read = (relativePath) => JSON.parse(fs.readFileSync(path.join(ROOT, relativePath), 'utf8'));
const base = {
  execution: read(EXECUTION_PATH),
  source: read(SOURCE_PATH),
  replay: read(REPLAY_PATH),
  schema: read(SCHEMA_PATH)
};
const clone = () => structuredClone(base);
const mutations = [
  (x) => { x.schema.$id = 'https://example.com/wrong.json'; },
  (x) => { x.schema.additionalProperties = true; },
  (x) => { x.schema.properties.schema_version.const = 'wrong'; },
  (x) => { x.schema.properties.source_id.const = 'wrong'; },
  (x) => { x.schema.properties.unit_binding.properties.unit_ordinal.const = 14; },
  (x) => { x.schema.properties.unit_binding.properties.exact_frozen_legal_vehicle_string_present.const = true; },
  (x) => { x.schema.properties.admitted_observations.minItems = 6; },
  (x) => { x.schema.properties.admitted_observations.maxItems = 8; },
  (x) => { x.schema.properties.source_disposition.properties.admitted_source.const = false; },
  (x) => { x.schema.properties.source_disposition.properties.lifecycle_events_for_rd02_c05_observed.const = 1; },
  (x) => { x.schema.properties.source_disposition.properties.class_closed.const = true; },

  (x) => { x.execution.schema_version = 'wrong'; },
  (x) => { x.execution.class_id = 'RD-02-C04'; },
  (x) => { x.execution.canonical_protocol_merge = '0'.repeat(40); },
  (x) => { x.execution.execution.workflow_run += 1; },
  (x) => { x.execution.execution.workflow_attempt = 2; },
  (x) => { x.execution.execution.trigger_pr = 1081; },
  (x) => { x.execution.execution.trigger_head = '0'.repeat(40); },
  (x) => { x.execution.execution.synthetic_merge_head = '1'.repeat(40); },
  (x) => { x.execution.execution.artifact_id += 1; },
  (x) => { x.execution.execution.artifact_zip_bytes -= 1; },
  (x) => { x.execution.execution.artifact_zip_sha256 = '2'.repeat(64); },
  (x) => { x.execution.execution.manifest_entries = 17; },
  (x) => { x.execution.execution.manifest_combined_sha256 = '3'.repeat(64); },
  (x) => { x.execution.execution.manifest_file_sha256 = '4'.repeat(64); },
  (x) => { x.execution.counts.fixed_routes = 1; },
  (x) => { x.execution.counts.route_attempts = 1; },
  (x) => { x.execution.counts.terminal_routes = 1; },
  (x) => { x.execution.counts.http_success_pdf_captured = 2; },
  (x) => { x.execution.counts.pretransport_failures = 0; },
  (x) => { x.execution.counts.http_failures = 1; },
  (x) => { x.execution.counts.source_restrictions = 1; },
  (x) => { x.execution.counts.pdf_bodies_captured = 2; },
  (x) => { x.execution.counts.admitted_sources_in_raw_capture = 1; },
  (x) => { x.execution.counts.observations_admitted_in_raw_capture = 1; },
  (x) => { x.execution.counts.fields_closed_in_raw_capture = 1; },
  (x) => { x.execution.counts.result_spawned_requests = 1; },
  (x) => { x.execution.route_outcomes.pop(); },
  (x) => { x.execution.route_outcomes[0].route_id = 'wrong'; },
  (x) => { x.execution.route_outcomes[0].candidate_ordinal = 277; },
  (x) => { x.execution.route_outcomes[0].curl_exit = 1; },
  (x) => { x.execution.route_outcomes[0].http_status = 404; },
  (x) => { x.execution.route_outcomes[0].body_bytes = 1; },
  (x) => { x.execution.route_outcomes[0].body_sha256 = '5'.repeat(64); },
  (x) => { x.execution.route_outcomes[0].terminal_route_state = 'source_admitted'; },
  (x) => { x.execution.route_outcomes[0].admitted_source_in_raw_capture = true; },
  (x) => { x.execution.route_outcomes[0].result_spawned_requests = 1; },
  (x) => { x.execution.route_outcomes[1].route_id = 'wrong'; },
  (x) => { x.execution.route_outcomes[1].candidate_ordinal = 404; },
  (x) => { x.execution.route_outcomes[1].candidate_id = '6'.repeat(64); },
  (x) => { x.execution.route_outcomes[1].requested_url = 'https://example.com/'; },
  (x) => { x.execution.route_outcomes[1].curl_exit = 0; },
  (x) => { x.execution.route_outcomes[1].http_status = 200; },
  (x) => { x.execution.route_outcomes[1].body_bytes = 10; },
  (x) => { x.execution.route_outcomes[1].stderr = ''; },
  (x) => { x.execution.route_outcomes[1].terminal_route_state = 'http_failure'; },
  (x) => { x.execution.route_outcomes[1].http_request_sent = true; },
  (x) => { x.execution.route_outcomes[1].source_restricted = true; },
  (x) => { x.execution.route_outcomes[1].source_unavailable = true; },
  (x) => { x.execution.route_outcomes[1].replay_authorized = false; },
  (x) => { x.execution.route_outcomes[1].result_spawned_requests = 1; },
  (x) => { x.execution.inspection_custody.route_id = 'wrong'; },
  (x) => { x.execution.inspection_custody.pdf_pages = 1; },
  (x) => { x.execution.inspection_custody.embedded_text_bytes = 1; },
  (x) => { x.execution.inspection_custody.embedded_text_sha256 = '7'.repeat(64); },
  (x) => { x.execution.inspection_custody.rendered_page_sha256.pop(); },
  (x) => { x.execution.inspection_custody.rendered_page_sha256[0] = '8'.repeat(64); },
  (x) => { x.execution.inspection_custody.rendered_pages_inspected = 1; },
  (x) => { x.execution.current_result.new_admitted_sources = 0; },
  (x) => { x.execution.current_result.new_lifecycle_events_observed = 1; },
  (x) => { x.execution.current_result.field_matrix_terminal = true; },
  (x) => { x.execution.current_result.class_state = 'closed'; },
  (x) => { x.execution.current_result.class_closed = true; },
  (x) => { x.execution.authority_boundaries.outside_human_dependency = true; },
  (x) => { x.execution.authority_boundaries.external_contacts = 1; },
  (x) => { x.execution.authority_boundaries.capital_conversion_finding = true; },
  (x) => { x.execution.authority_boundaries.graph_effect = 'created'; },
  (x) => { x.execution.unapproved = true; },

  (x) => { x.source.schema_version = 'wrong'; },
  (x) => { x.source.source_id = 'wrong'; },
  (x) => { x.source.source_type = 'news_article'; },
  (x) => { x.source.publication_date = '2024-10-21'; },
  (x) => { x.source.publisher = 'Unknown'; },
  (x) => { x.source.requested_url = 'https://example.com/'; },
  (x) => { x.source.unit_binding.unit_ordinal = 14; },
  (x) => { x.source.unit_binding.unit_id = 'wrong'; },
  (x) => { x.source.unit_binding.frozen_legal_vehicle = 'Stifel'; },
  (x) => { x.source.unit_binding.public_fund_name_in_source = 'wrong'; },
  (x) => { x.source.unit_binding.exact_frozen_legal_vehicle_string_present = true; },
  (x) => { x.source.exact_custody.artifact_zip_sha256 = '9'.repeat(64); },
  (x) => { x.source.exact_custody.body_sha256 = 'a'.repeat(64); },
  (x) => { x.source.exact_custody.pdf_pages = 1; },
  (x) => { x.source.exact_custody.all_pages_rendered_and_inspected = false; },
  (x) => { x.source.admitted_observations.pop(); },
  (x) => { x.source.admitted_observations[0].observation_id = 'wrong'; },
  (x) => { x.source.admitted_observations[0].field = 'portfolio_investment'; },
  (x) => { x.source.admitted_observations[0].state = 'inferred'; },
  (x) => { x.source.admitted_observations[0].not_equivalent_to = []; },
  (x) => { x.source.admitted_observations[3].scope = 'actual draw'; },
  (x) => { x.source.admitted_observations[3].not_equivalent_to = ['nothing']; },
  (x) => { x.source.admitted_observations[5].value.named_commitment_sources.pop(); },
  (x) => { x.source.admitted_observations[5].value.amounts_publicly_stated = true; },
  (x) => { x.source.admitted_observations[5].not_equivalent_to = ['capital funded']; },
  (x) => { delete x.source.class_field_effect.publicly_identified_exits; },
  (x) => { x.source.class_field_effect.source_identities_and_exact_custody = 'no_source'; },
  (x) => { x.source.class_field_effect.field_and_row_terminal_state = 'terminal'; },
  (x) => { x.source.unresolved_limits.actual_sba_leverage_commitment_recovered = true; },
  (x) => { x.source.unresolved_limits.actual_sba_leverage_draw_recovered = true; },
  (x) => { x.source.unresolved_limits.publicly_identified_portfolio_investments_recovered = true; },
  (x) => { x.source.unresolved_limits.follow_on_investments_recovered = true; },
  (x) => { x.source.unresolved_limits.exits_recovered = true; },
  (x) => { x.source.unresolved_limits.write_offs_or_realized_losses_recovered = true; },
  (x) => { x.source.unresolved_limits.defaults_or_cures_recovered = true; },
  (x) => { x.source.unresolved_limits.realized_fund_returns_recovered = true; },
  (x) => { x.source.unresolved_limits.sba_repayment_or_loss_allocation_recovered = true; },
  (x) => { x.source.unresolved_limits.missing_records_are_event_absence = true; },
  (x) => { x.source.source_disposition.admitted_source = false; },
  (x) => { x.source.source_disposition.admitted_observations = 6; },
  (x) => { x.source.source_disposition.lifecycle_events_for_rd02_c05_observed = 1; },
  (x) => { x.source.source_disposition.fields_terminally_closed = 1; },
  (x) => { x.source.source_disposition.row_terminally_closed = true; },
  (x) => { x.source.source_disposition.class_closed = true; },
  (x) => { x.source.authority_boundaries.outside_human_dependency = true; },
  (x) => { x.source.authority_boundaries.favoritism_finding = true; },
  (x) => { x.source.authority_boundaries.publication_effect = 'published'; },
  (x) => { x.source.unapproved = true; },

  (x) => { x.replay.schema_version = 'wrong'; },
  (x) => { x.replay.source_custody.canonical_disclosure_leaf_protocol_merge = '0'.repeat(40); },
  (x) => { x.replay.source_custody.artifact_zip_sha256 = 'b'.repeat(64); },
  (x) => { x.replay.source_custody.failed_route_id = 'RD02-W03-DL001'; },
  (x) => { x.replay.source_custody.failed_route_candidate_id = 'c'.repeat(64); },
  (x) => { x.replay.source_custody.failed_route_http_status = 403; },
  (x) => { x.replay.source_custody.http_request_sent = true; },
  (x) => { x.replay.denominator.original_fixed_routes = 1; },
  (x) => { x.replay.denominator.original_terminal_routes = 1; },
  (x) => { x.replay.denominator.original_successful_pdf_routes = 0; },
  (x) => { x.replay.denominator.original_pretransport_failures = 0; },
  (x) => { x.replay.denominator.successful_routes_replayed = 1; },
  (x) => { x.replay.denominator.fixed_replay_routes = 2; },
  (x) => { x.replay.denominator.route_ledger_bytes += 1; },
  (x) => { x.replay.denominator.route_ledger_sha256 = 'd'.repeat(64); },
  (x) => { x.replay.routes.push(structuredClone(x.replay.routes[0])); },
  (x) => { x.replay.routes[0].route_id = 'wrong'; },
  (x) => { x.replay.routes[0].replays_route_id = 'RD02-W03-DL001'; },
  (x) => { x.replay.routes[0].candidate_ordinal = 404; },
  (x) => { x.replay.routes[0].candidate_id = 'e'.repeat(64); },
  (x) => { x.replay.routes[0].candidate_url = 'https://example.com/raw'; },
  (x) => { x.replay.routes[0].transport_url = x.replay.routes[0].candidate_url; },
  (x) => { x.replay.routes[0].transport_normalization = 'none'; },
  (x) => { x.replay.routes[0].route_type = 'exact_vehicle_approval_pdf_get'; },
  (x) => { x.replay.routes[0].maximum_replay_attempts = 2; },
  (x) => { x.replay.routes[0].maximum_response_body_bytes = 1; },
  (x) => { x.replay.routes[0].candidate_is_admitted_source = true; },
  (x) => { x.replay.routes[0].automatic_observation_admission = true; },
  (x) => { x.replay.routes[0].result_spawned_requests = 1; },
  (x) => { x.replay.routes[0].expected_observation_scope = []; },
  (x) => { x.replay.routes[0].forbidden_promotions = []; },
  (x) => { x.replay.execution_contract.replay_authorized_only_because_original_http_request_was_not_sent = false; },
  (x) => { x.replay.execution_contract.successful_route_replay_forbidden = false; },
  (x) => { x.replay.execution_contract.raw_candidate_identity_preserved = false; },
  (x) => { x.replay.execution_contract.transport_normalization_limited_to_percent_encoding_literal_spaces = false; },
  (x) => { x.replay.execution_contract.maximum_replay_attempts = 2; },
  (x) => { x.replay.execution_contract.maximum_parallel_workers = 2; },
  (x) => { x.replay.execution_contract.pdf_magic_required_for_success = false; },
  (x) => { x.replay.execution_contract.result_spawned_requests = 1; },
  (x) => { x.replay.execution_contract.candidate_admission_without_separate_adjudication = true; },
  (x) => { x.replay.execution_contract.automatic_observation_admission = true; },
  (x) => { x.replay.execution_contract.automatic_field_closure = true; },
  (x) => { x.replay.execution_contract.automatic_class_closure = true; },
  (x) => { x.replay.current_counts.replay_attempts = 1; },
  (x) => { x.replay.current_counts.terminal_replay_routes = 1; },
  (x) => { x.replay.current_counts.captured_pdf_bodies = 1; },
  (x) => { x.replay.current_counts.admitted_sources = 1; },
  (x) => { x.replay.current_counts.observations_admitted = 1; },
  (x) => { x.replay.current_counts.fields_closed = 1; },
  (x) => { x.replay.current_counts.class_closed = true; },
  (x) => { x.replay.authority_boundaries.outside_human_dependency = true; },
  (x) => { x.replay.authority_boundaries.coordination_finding = true; },
  (x) => { x.replay.authority_boundaries.adoption_effect = 'adopted'; },
  (x) => { x.replay.unapproved = true; }
];

let refused = 0;
for (const mutate of mutations) {
  const specimen = clone();
  mutate(specimen);
  try {
    validateBundle(specimen);
  } catch {
    refused += 1;
  }
}
if (refused !== mutations.length) throw new Error(`adversarial refusals ${refused}/${mutations.length}`);
validateBundle(base);
console.log(`RD-02 leaf replay adversarial suite: ${refused} PASS`);
