#!/usr/bin/env node
import assert from 'node:assert/strict';
import { loadSixGateFirstPassContext, validateSixGateFirstPass } from '../tools/validate-status-sovereignty-six-gate-first-pass-reconciliation.mjs';

const clean = loadSixGateFirstPassContext();
assert.deepEqual(validateSixGateFirstPass(clean), [], 'clean six-gate reconciliation must validate');
const clone = () => Object.fromEntries(Object.entries(clean).map(([key, value]) => [key, typeof value === 'string' ? value : structuredClone(value)]));
const gate = (c, index) => c.record.gate_receipts[index];
const source = (c, id) => c.laneSources[id];
const laneManifest = (c, id) => c.laneManifests[id];
const mutations = [
  ['record schema', (c) => { c.record.schema_version = 'other'; }, 'Record schema'],
  ['reconciliation identity', (c) => { c.record.reconciliation_id = 'OTHER'; }, 'Reconciliation identity'],
  ['hypothesis identity', (c) => { c.record.hypothesis_id = 'OTHER'; }, 'Hypothesis identity'],
  ['issue identity', (c) => { c.record.issue = 0; }, 'Issue identity'],
  ['reconciliation date', (c) => { c.record.as_of = '2026-07-31'; }, 'Reconciliation date'],
  ['authority inflation', (c) => { c.record.authority = 'adjudication'; }, 'Authority ceiling'],
  ['parent program', (c) => { c.record.parent_program.program_issue = 0; }, 'Parent program'],
  ['parent wave', (c) => { c.record.parent_program.wave_issue = 0; }, 'Parent program'],
  ['parent issue range', (c) => { c.record.parent_program.first_pass_issue_range = '540-544'; }, 'Parent program'],
  ['gate removed', (c) => { c.record.gate_receipts.pop(); }, 'Gate receipt count'],
  ['gate ID duplicate', (c) => { gate(c, 1).gate_id = gate(c, 0).gate_id; }, 'Gate receipt gate_id uniqueness'],
  ['issue duplicate', (c) => { gate(c, 1).issue = gate(c, 0).issue; }, 'Gate receipt issue uniqueness'],
  ['PR duplicate', (c) => { gate(c, 1).pr = gate(c, 0).pr; }, 'Gate receipt pr uniqueness'],
  ['review head duplicate', (c) => { gate(c, 1).review_head = gate(c, 0).review_head; }, 'Gate receipt review_head uniqueness'],
  ['merge commit duplicate', (c) => { gate(c, 1).merge_commit = gate(c, 0).merge_commit; }, 'Gate receipt merge_commit uniqueness'],
  ['source path duplicate', (c) => { gate(c, 1).source_path = gate(c, 0).source_path; }, 'Gate receipt source_path uniqueness'],
  ['manifest path duplicate', (c) => { gate(c, 1).release_manifest_path = gate(c, 0).release_manifest_path; }, 'Gate receipt release_manifest_path uniqueness'],
  ['release digest duplicate', (c) => { gate(c, 1).release_sha256 = gate(c, 0).release_sha256; }, 'Gate receipt release_sha256 uniqueness'],
  ['NatSec issue drift', (c) => { gate(c, 0).issue = 0; }, 'Gate 1 issue'],
  ['NatSec PR drift', (c) => { gate(c, 0).pr = 0; }, 'Gate 1 pr'],
  ['NatSec lane drift', (c) => { gate(c, 0).lane_id = 'SSC-F10'; }, 'Gate 1 lane_id'],
  ['NatSec observation drift', (c) => { gate(c, 0).observation_id = 'OTHER'; }, 'Gate 1 observation_id'],
  ['NatSec review head drift', (c) => { gate(c, 0).review_head = '0'.repeat(40); }, 'Gate 1 review_head'],
  ['NatSec merge drift', (c) => { gate(c, 0).merge_commit = '0'.repeat(40); }, 'Gate 1 merge_commit'],
  ['NatSec digest drift', (c) => { gate(c, 0).release_sha256 = '0'.repeat(64); }, 'Gate 1 release_sha256'],
  ['NatSec source count drift', (c) => { gate(c, 0).source_records = 2; }, 'Gate 1 source_records'],
  ['NatSec residual field drift', (c) => { gate(c, 0).residual_field = 'open_denominators'; }, 'Gate 1 residual_field'],
  ['NatSec residual count drift', (c) => { gate(c, 0).residual_denominator_classes = 7; }, 'Gate 1 residual_denominator_classes'],
  ['SBIC digest drift', (c) => { gate(c, 1).release_sha256 = '1'.repeat(64); }, 'Gate 2 release_sha256'],
  ['OSC source path drift', (c) => { gate(c, 2).source_path = 'data/intake/other.json'; }, 'Gate 3 source_path'],
  ['SNAP first pass drift', (c) => { gate(c, 3).first_pass_id = 'OTHER'; }, 'Gate 4 first_pass_id'],
  ['ACES allowed true field removed', (c) => { gate(c, 4).allowed_true_result_fields = []; }, 'Gate 5 allowed_true_result_fields'],
  ['DCGS control list erased', (c) => { gate(c, 5).retained_controls = []; }, 'Gate 6 retained controls missing'],
  ['NatSec observed source count', (c) => { source(c, 'SSC-F09-NATSEC100-01').sources.push({}); }, 'Gate 1 observed source count'],
  ['SBIC terminal promoted', (c) => { source(c, 'SSC-F10-SBICCT-01').current_result.terminal_state = 'complete'; }, 'Gate 2 observed terminal state'],
  ['OSC graph effect', (c) => { source(c, 'SSC-F10-OSC-01').current_result.graph_effect = 'edge'; }, 'Gate 3 observed graph effect'],
  ['SNAP publication effect', (c) => { source(c, 'SSC-F02-SNAP-01').current_result.publication_effect = 'public'; }, 'Gate 4 observed publication effect'],
  ['ACES residual removed', (c) => { source(c, 'SSC-F04-ACES-01').open_denominators.pop(); }, 'Gate 5 observed residual count'],
  ['DCGS residual removed', (c) => { source(c, 'SSC-F13-DCGSA-01').open_denominators.pop(); }, 'Gate 6 observed residual count'],
  ['NatSec manifest digest', (c) => { laneManifest(c, 'SSC-F09-NATSEC100-01').combined_sha256 = 'f'.repeat(64); }, 'Gate 1 release digest'],
  ['SBIC manifest hypothesis', (c) => { laneManifest(c, 'SSC-F10-SBICCT-01').hypothesis_id = 'OTHER'; }, 'Gate 2 manifest hypothesis'],
  ['OSC manifest first pass', (c) => { laneManifest(c, 'SSC-F10-OSC-01').first_pass_id = 'OTHER'; }, 'Gate 3 manifest first-pass identity'],
  ['NatSec invented true result', (c) => { source(c, 'SSC-F09-NATSEC100-01').current_result.reviewed_disposition_changed = true; }, 'Gate 1 allowed true result fields'],
  ['ACES true result removed', (c) => { source(c, 'SSC-F04-ACES-01').current_result.bounded_non_link_observed = false; }, 'Gate 5 allowed true result fields'],
  ['DCGS extra true result', (c) => { source(c, 'SSC-F13-DCGSA-01').current_result.foreclosure_finding = true; }, 'Gate 6 allowed true result fields'],
  ['atlas removed', (c) => { c.record.residual_denominator_atlas.pop(); }, 'Residual denominator atlas'],
  ['atlas class duplicate', (c) => { c.record.residual_denominator_atlas[1].class_id = c.record.residual_denominator_atlas[0].class_id; }, 'Residual atlas class uniqueness'],
  ['atlas gate duplicate', (c) => { c.record.residual_denominator_atlas[1].gate_id = c.record.residual_denominator_atlas[0].gate_id; }, 'Residual atlas gate uniqueness'],
  ['atlas total drift', (c) => { c.record.residual_denominator_atlas[0].count = 7; }, 'Residual denominator atlas'],
  ['completed lanes drift', (c) => { c.record.counts.first_pass_lanes_completed = 5; }, 'Reconciliation counts'],
  ['issue closures drift', (c) => { c.record.counts.first_pass_issues_closed_completed = 5; }, 'Reconciliation counts'],
  ['source total drift', (c) => { c.record.counts.source_records = 24; }, 'Reconciliation counts'],
  ['terminal count drift', (c) => { c.record.counts.terminal_requires_additional_acquisition = 5; }, 'Reconciliation counts'],
  ['residual total drift', (c) => { c.record.counts.residual_denominator_classes = 41; }, 'Reconciliation counts'],
  ['residual closure invented', (c) => { c.record.counts.residual_evidence_obligations_closed = 1; }, 'Reconciliation counts'],
  ['review change invented', (c) => { c.record.counts.reviewed_disposition_changes = 1; }, 'Reconciliation counts'],
  ['compact finding count', (c) => { c.record.counts.complete_compact_findings = 1; }, 'Reconciliation counts'],
  ['racial finding count', (c) => { c.record.counts.racial_order_findings = 1; }, 'Reconciliation counts'],
  ['coordination finding count', (c) => { c.record.counts.coordination_findings = 1; }, 'Reconciliation counts'],
  ['terminal result drift', (c) => { c.record.current_result.terminal_state = 'complete_compact'; }, 'Current result'],
  ['receipt presence erased', (c) => { c.record.current_result.all_six_first_pass_receipts_present = false; }, 'Current result'],
  ['authority sharing invented', (c) => { c.record.current_result.cross_lane_empirical_authority_shared = true; }, 'Current result'],
  ['review disposition invented', (c) => { c.record.current_result.reviewed_disposition_changed = true; }, 'Current result'],
  ['compact finding invented', (c) => { c.record.current_result.complete_compact_finding = true; }, 'Current result'],
  ['racial finding invented', (c) => { c.record.current_result.racial_order_finding = true; }, 'Current result'],
  ['prevalence finding invented', (c) => { c.record.current_result.prevalence_finding = true; }, 'Current result'],
  ['common purpose invented', (c) => { c.record.current_result.common_purpose_finding = true; }, 'Current result'],
  ['graph effect invented', (c) => { c.record.current_result.graph_effect = 'edge'; }, 'Current result'],
  ['publication effect invented', (c) => { c.record.current_result.publication_effect = 'public'; }, 'Current result'],
  ['issue completion shortcut', (c) => { c.record.boundaries.first_pass_issue_completion_is_substantive_denominator_closure = true; }, 'Boundary first_pass_issue_completion_is_substantive_denominator_closure'],
  ['roster shortcut', (c) => { c.record.boundaries.selected_roster_is_candidate_universe = true; }, 'Boundary selected_roster_is_candidate_universe'],
  ['license shortcut', (c) => { c.record.boundaries.license_is_leverage_draw = true; }, 'Boundary license_is_leverage_draw'],
  ['commitment shortcut', (c) => { c.record.boundaries.conditional_commitment_is_executed_loan = true; }, 'Boundary conditional_commitment_is_executed_loan'],
  ['loan shortcut', (c) => { c.record.boundaries.executed_loan_is_disbursement_or_repayment = true; }, 'Boundary executed_loan_is_disbursement_or_repayment'],
  ['representation shortcut', (c) => { c.record.boundaries.representation_proves_neutrality_or_tokenism = true; }, 'Boundary representation_proves_neutrality_or_tokenism'],
  ['appeal shortcut', (c) => { c.record.boundaries.formal_appeal_proves_effective_counterpower = true; }, 'Boundary formal_appeal_proves_effective_counterpower'],
  ['competition shortcut', (c) => { c.record.boundaries.competition_and_protest_prove_complete_option_set_fairness = true; }, 'Boundary competition_and_protest_prove_complete_option_set_fairness'],
  ['convergence shortcut', (c) => { c.record.boundaries.functional_convergence_proves_conscious_common_purpose = true; }, 'Boundary functional_convergence_proves_conscious_common_purpose'],
  ['schema identity', (c) => { c.schema.properties.schema_version.const = 'other'; }, 'Schema identity'],
  ['schema issue', (c) => { c.schema.properties.issue.const = 0; }, 'Schema issue'],
  ['schema gate minimum', (c) => { c.schema.properties.gate_receipts.minItems = 5; }, 'Schema gate minimum'],
  ['schema atlas minimum', (c) => { c.schema.properties.residual_denominator_atlas.minItems = 5; }, 'Schema atlas minimum'],
  ['schema residual total', (c) => { c.schema.properties.counts.properties.residual_denominator_classes.const = 41; }, 'Schema residual total'],
  ['manifest drift', (c) => { c.manifest.combined_sha256 = 'f'.repeat(64); }, 'Exact-byte reconciliation manifest'],
  ['build manifest drift', (c) => { c.buildManifest.combined_sha256 = 'e'.repeat(64); }, 'Build manifest drift'],
  ['public report drift', (c) => { c.publicReport.counts.source_records = 24; }, 'Build/public report drift'],
  ['report completed lanes', (c) => { c.buildReport.counts.first_pass_lanes_completed = 5; c.publicReport.counts.first_pass_lanes_completed = 5; }, 'Report completed lanes'],
  ['report source count', (c) => { c.buildReport.counts.source_records = 24; c.publicReport.counts.source_records = 24; }, 'Report source count'],
  ['report residual count', (c) => { c.buildReport.counts.residual_denominator_classes = 41; c.publicReport.counts.residual_denominator_classes = 41; }, 'Report residual count'],
  ['report closure count', (c) => { c.buildReport.counts.residual_evidence_obligations_closed = 1; c.publicReport.counts.residual_evidence_obligations_closed = 1; }, 'Report residual closure count'],
  ['report control count', (c) => { c.buildReport.counts.retained_control_statements = 13; c.publicReport.counts.retained_control_statements = 13; }, 'Report retained-control count'],
  ['report exact receipts', (c) => { c.buildReport.counts.exact_lane_release_receipts = 5; c.publicReport.counts.exact_lane_release_receipts = 5; }, 'Report exact lane receipt count'],
  ['HTML receipt boundary', (c) => { c.html = c.html.replace('6/6 FIRST-PASS RECEIPTS', '5/6 FIRST-PASS RECEIPTS'); }, 'HTML gate receipt boundary missing'],
  ['HTML residual boundary', (c) => { c.html = c.html.replace('42 RESIDUAL CLASSES', '41 RESIDUAL CLASSES'); }, 'HTML residual denominator boundary missing'],
  ['HTML closure boundary', (c) => { c.html = c.html.replace('0 RESIDUAL OBLIGATIONS CLOSED', '1 RESIDUAL OBLIGATION CLOSED'); }, 'HTML residual closure boundary missing'],
  ['HTML compact boundary', (c) => { c.html = c.html.replace('0 COMPLETE-COMPACT FINDINGS', '1 COMPLETE-COMPACT FINDING'); }, 'HTML compact boundary missing'],
  ['HTML digest erased', (c) => { c.html = c.html.replace(c.manifest.combined_sha256, '0'.repeat(64)); }, 'HTML release digest missing'],
  ['HTML noindex erased', (c) => { c.html = c.html.replace('noindex,nofollow', 'index,follow'); }, 'HTML noindex boundary missing']
];

for (const [name, mutate, expected] of mutations) {
  const context = clone();
  mutate(context);
  const errors = validateSixGateFirstPass(context);
  assert(errors.some((error) => error.includes(expected)), `${name}: expected ${expected}; observed ${JSON.stringify(errors)}`);
}
console.log(`status-sovereignty-six-gate-first-pass-reconciliation.test: ${mutations.length} adversarial mutations PASS`);
