import { loadProduct, validateProduct } from '../tools/validate-status-sovereignty-rd-wave03-rd04-postpromotion-nd-followup-two-route-adjudication.mjs';
function clone(value) { return structuredClone(value); }
const baseline = loadProduct();
validateProduct(baseline);
const mutations = [
  ['add execution authority', (p) => { p.capture.additional_execution_authorized = true; }],
  ['change canonical parent', (p) => { p.capture.canonical_parent = '0'.repeat(40); }],
  ['drop artifact', (p) => p.capture.artifacts.pop()],
  ['add authoritative artifact', (p) => { p.capture.artifacts[1].artifact_role='authoritative_semantic_transport_custody'; }],
  ['change authoritative requests', (p) => { p.capture.transport_ledger.authoritative_execution_physical_requests=4; }],
  ['change total requests', (p) => { p.capture.transport_ledger.physical_requests_across_all_artifacts=4; }],
  ['claim body drift', (p) => { p.capture.transport_ledger.body_changes_across_executions=1; }],
  ['change unique bodies', (p) => { p.capture.transport_ledger.unique_body_identity_count=3; }],
  ['change matrix blob', (p) => { p.capture.input_custody.current_matrix.git_blob='0'.repeat(40); }],
  ['change route body', (p) => { p.capture.route_bodies[0].body_sha256='0'.repeat(64); }],
  ['capture matrix update', (p) => { p.capture.authority_boundary.matrix_updates=1; }],
  ['duplicate substantive weight', (p) => { p.duplication.route_body_identity[0].substantive_weight_count=2; }],
  ['duplicate body change', (p) => { p.duplication.summary.body_changes=1; }],
  ['duplicate execution authority', (p) => { p.duplication.additional_execution_authorized=true; }],
  ['drop HTML receipt', (p) => p.html.receipts.pop()],
  ['unset complete review', (p) => { p.html.summary.all_visible_text_reviewed=false; }],
  ['change release text hash', (p) => { p.html.receipts[0].visible_text_sha256='0'.repeat(64); }],
  ['drop release locator', (p) => p.html.receipts[0].evidence_locators.pop()],
  ['spawn result request', (p) => { p.html.receipts[0].result_spawned_requests=1; }],
  ['drop source decision', (p) => p.source.decisions.pop()],
  ['change source admissions', (p) => { p.source.summary.narrow_source_admissions=1; }],
  ['double source weight', (p) => { p.source.decisions[0].substantive_weight_count=2; }],
  ['drop transport observation', (p) => p.source.decisions[0].transport_observations.pop()],
  ['alter observation body', (p) => { p.source.decisions[0].transport_observations[1].body_sha256='0'.repeat(64); }],
  ['add authoritative observation', (p) => { p.source.decisions[0].transport_observations[1].artifact_role='authoritative_semantic_transport_custody'; }],
  ['widen release route field', (p) => p.source.decisions[0].candidate_fields_for_offline_review.push('abawd_or_work_requirement_waiver_state_and_governing_period')],
  ['drop field decision', (p) => p.field.decisions.pop()],
  ['increase field candidates', (p) => { p.field.summary.evidence_complete_candidates=2; }],
  ['remove field hold', (p) => { p.field.summary.held_open_fields=0; }],
  ['change terminal cells', (p) => { p.field.frontier.terminal_matrix_cells_before=225; }],
  ['change open cells', (p) => { p.field.frontier.open_matrix_cells_before=225; }],
  ['change open substantive', (p) => { p.field.frontier.open_substantive_cells_before=183; }],
  ['change current release', (p) => { p.field.decisions[0].bounded_finding.current_public_release_identifier='26.6'; }],
  ['drop release sequence row', (p) => p.field.decisions[0].bounded_finding.work_registration_release_sequence.pop()],
  ['hold authority field', (p) => { p.field.decisions[0].promotion_candidate=false; p.field.decisions[0].disposition='partial_support_hold_open'; }],
  ['promote waiver field', (p) => { p.field.decisions[1].promotion_candidate=true; p.field.decisions[1].disposition='evidence_complete_bounded_finding'; }],
  ['invent current waiver', (p) => { p.field.decisions[1].bounded_finding.current_post_2025_10_31_state='no_waiver'; }],
  ['terminalize field', (p) => { p.field.decisions[0].substantive_field_terminalizations=1; }],
  ['mutate row', (p) => { p.field.decisions[0].row_state_effect='terminal'; }],
  ['widen route target', (p) => p.field.decisions[0].source_route_ids.push('RD04-W03-PPN-ND-FU-002')],
  ['alter cell hash', (p) => { p.field.frontier.target_cell_canonical_sha256.operative_state_implementation_authority_and_version='0'.repeat(64); }],
  ['candidate count drift', (p) => { p.candidate.candidate_count=2; }],
  ['candidate held drift', (p) => { p.candidate.held_cell_count=0; }],
  ['candidate field drift', (p) => { p.candidate.candidates[0].field_id='abawd_or_work_requirement_waiver_state_and_governing_period'; }],
  ['candidate hash drift', (p) => { p.candidate.candidates[0].current_cell_canonical_sha256='0'.repeat(64); }],
  ['index matrix update', (p) => { p.index.matrix_summary.matrix_updates=1; }],
  ['manifest path count', (p) => { p.manifest.permanent_path_count=13; }],
  ['manifest hash count', (p) => { p.manifest.hashed_file_count=12; }],
  ['drop manifest path', (p) => p.manifest.permanent_paths.pop()],
  ['manifest publication', (p) => { p.manifest.authority_boundary.publication_effect='published'; }],
];
let refused=0;
for (const [name, mutate] of mutations) { const value=clone(baseline); mutate(value); let rejected=false; try { validateProduct(value); } catch { rejected=true; } if (!rejected) throw new Error(`adversarial mutation admitted: ${name}`); refused += 1; }
console.log(JSON.stringify({postpromotion_nd_followup_two_route_adjudication:'pass', adversarial_refusals:refused, candidate_count:1, held_fields:1, source_admissions:2}));
