#!/usr/bin/env node
import assert from 'node:assert/strict';
import { PRODUCT_ROOT, CLASS_LABEL, TERMINAL_STATE, CLOSURE_REFERENCE_PATH, LABEL_RECONCILIATION } from '../tools/build-status-sovereignty-rd-wave02-rd03-negotiated-terms.mjs';
import { readBundle, validateProduct, validateProductShape, validateCurrentAtlasCustody } from '../tools/validate-status-sovereignty-rd-wave02-rd03-negotiated-terms.mjs';
const clone=(value)=>structuredClone(value);
validateProduct();
const bundle=readBundle();
assert.equal(validateCurrentAtlasCustody(bundle.current,bundle.manifest.combined_sha256),'post_promotion');
const post=clone(bundle.current);
const pre=clone(bundle.current);
pre.authority='four_terminal_class_receipts_promoted_without_cross_lane_empirical_authority';
pre.promoted_class_receipts=pre.promoted_class_receipts.filter((row)=>row.class_id!=='RD-03-C04');
pre.selected_classes_open.push({lane_id:'RD-03',class_id:'RD-03-C04',issue:788,constitutional_exact_label:CLASS_LABEL,state:'open',class_closed:false});
pre.counts.terminal_class_receipts=4;pre.counts.classes_closed_this_wave=4;pre.counts.closed_residual_classes=4;pre.counts.open_residual_classes=38;pre.counts.label_reconciliations=1;
pre.current_result.terminal_state='four_of_forty_two_residual_classes_closed_two_selected_attempts_open';pre.current_result.classes_closed=4;pre.current_result.classes_open=38;pre.current_result.closed_class_ids=pre.current_result.closed_class_ids.filter((id)=>id!=='RD-03-C04');pre.current_result.open_selected_class_ids=['RD-02-C04','RD-03-C04'];
assert.equal(validateCurrentAtlasCustody(pre,bundle.manifest.combined_sha256),'pre_promotion');
const mutations=[
 ['terminal schema',b=>{b.terminal.schema_version='bad';}],['terminal class',b=>{b.terminal.class_id='RD-02-C04';}],['terminal issue',b=>{b.terminal.issue=787;}],['terminal label',b=>{b.terminal.class_label='partial';}],['terminal status',b=>{b.terminal.status='open';}],
 ['source head',b=>{b.terminal.source_product.source_matrix_head='0'.repeat(40);}],['matrix sha',b=>{b.terminal.source_product.historical_field_matrix_sha256='0'.repeat(64);}],['matrix blob',b=>{b.terminal.source_product.historical_field_matrix_blob_sha='0'.repeat(40);}],['parent sha',b=>{b.terminal.source_product.parent_sha256='0'.repeat(64);}],['census digest',b=>{b.terminal.source_product.census_manifest_combined_sha256='0'.repeat(64);}],['artifact digest',b=>{b.terminal.source_product.census_artifact_sha256='0'.repeat(64);}],['seed reconciliation',b=>{b.terminal.source_product.seed_label_reconciliation='none';}],
 ['remove instrument',b=>{b.terminal.instruments.pop();}],['duplicate instrument',b=>{b.terminal.instruments[1].instrument_id=b.terminal.instruments[0].instrument_id;}],['instrument order',b=>{b.terminal.instruments.reverse();}],['remove field',b=>{delete b.terminal.instruments[0].fields.security_and_collateral;}],['field protocol false',b=>{b.terminal.instruments[0].fields.principal_or_ceiling.fixed_protocol_complete=false;}],['field terminal false',b=>{b.terminal.instruments[0].fields.principal_or_ceiling.terminal_for_class_closure=false;}],
 ['MP principal',b=>{b.terminal.instruments[0].fields.principal_or_ceiling.value.amount=151000000;}],['MP pricing',b=>{b.terminal.instruments[0].fields.pricing_and_cost_of_capital.value.annual_interest_rate_percent=0;}],['MP maturity promoted',b=>{b.terminal.instruments[0].fields.maturity_and_amortization.state='observed';}],['MP maturity changed',b=>{b.terminal.instruments[0].fields.maturity_and_amortization.value.observed_maturity_date='2038-01-01';}],['MP security promoted',b=>{b.terminal.instruments[0].fields.security_and_collateral.state='observed';}],['MP collateral invented',b=>{b.terminal.instruments[0].fields.security_and_collateral.value.complete_collateral_terms='all assets';}],
 ['Vulcan executed',b=>{b.terminal.instruments[1].fields.instrument_state_and_governing_date.state='observed';}],['Vulcan funded',b=>{b.terminal.instruments[1].fields.instrument_state_and_governing_date.value.cash_proceeds_received=true;}],['Vulcan principal executed',b=>{b.terminal.instruments[1].fields.principal_or_ceiling.value.amount_type='executed_principal';}],['ReElement amount',b=>{b.terminal.instruments[2].fields.principal_or_ceiling.value.amount=800000000;}],['Phoenix funded',b=>{b.terminal.instruments[3].fields.instrument_state_and_governing_date.value.executed_loan=true;}],['Energy tenor final',b=>{b.terminal.instruments[4].fields.maturity_and_amortization.state='observed';}],
 ['observed count',b=>{b.terminal.counts.observed_fields=9;}],['conditional count',b=>{b.terminal.counts.conditional_term_only_fields=14;}],['unavailable count',b=>{b.terminal.counts.source_unavailable_after_fixed_protocol_fields=46;}],['terminal count',b=>{b.terminal.counts.terminal_fields=69;}],['route count',b=>{b.terminal.counts.fixed_routes=29;}],['exact count',b=>{b.terminal.counts.exact_get_routes=14;}],['search count',b=>{b.terminal.counts.bing_rss_routes=14;}],['transport success',b=>{b.terminal.counts.http_success=14;}],['candidate admitted',b=>{b.terminal.counts.admitted_candidate_urls=1;}],['spawned request',b=>{b.terminal.counts.result_spawned_requests=1;}],
 ['class reopened',b=>{b.terminal.current_result.class_closed=false;}],['complete stack',b=>{b.terminal.current_result.complete_negotiated_term_stack_observed=true;}],['state distinction',b=>{b.terminal.current_result.executed_and_conditional_states_preserved=false;}],['favoritism',b=>{b.terminal.current_result.favoritism_finding=true;}],['extraction',b=>{b.terminal.current_result.extraction_finding=true;}],['public recovery',b=>{b.terminal.current_result.public_recovery_finding=true;}],['publication',b=>{b.terminal.current_result.publication_effect='published';}],
 ['conditional execution boundary',b=>{b.terminal.boundaries.conditional_commitment_is_executed_loan=true;}],['warrant boundary',b=>{b.terminal.boundaries.announced_warrant_is_issued_right=true;}],['pricing boundary',b=>{b.terminal.boundaries.published_pricing_is_complete_negotiated_agreement=true;}],['source absence boundary',b=>{b.terminal.boundaries.source_unavailability_is_term_absence=true;}],['candidate boundary',b=>{b.terminal.boundaries.search_candidate_is_admitted_source=true;}],['cohort boundary',b=>{b.terminal.boundaries.five_named_instruments_is_complete_cohort=true;}],
 ['receipt reopened',b=>{b.receipt.class_closed=false;}],['receipt state',b=>{b.receipt.terminal_state='evidence_complete';}],['receipt label',b=>{b.receipt.class_label='partial';}],['receipt reconciliation',b=>{b.receipt.label_custody.reconciliation='none';}],['receipt atlas',b=>{b.receipt.residual_atlas_effect_if_promoted_after_rd04_rd05_rd01_and_rd06.open_after=36;}],['receipt contact',b=>{b.receipt.authority.external_contacts=1;}],
 ['summary count',b=>{b.summary.counts.instruments=4;}],['summary result',b=>{b.summary.current_result.class_closed=false;}],['summary graph',b=>{b.summary.authority.graph_effect='edge';}],['manifest remove',b=>{b.manifest.entries.pop();}],['manifest path',b=>{b.manifest.entries[0].path='other.json';}],['closure issue',b=>{b.closure.child_issue=787;}],['closure PR',b=>{b.closure.source_pr=802;}],['closure state',b=>{b.closure.terminal_state='evidence_complete';}],['closure manifest',b=>{b.closure.product.manifest_combined_sha256='0'.repeat(64);}],['closure artifact',b=>{b.closure.execution.artifact_zip_sha256='0'.repeat(64);}],
 ['execution run',b=>{b.execution.workflow_run=1;}],['execution artifact',b=>{b.execution.artifact_zip_sha256='0'.repeat(64);}],['census routes',b=>{b.censusSummary.fixed_routes=29;}],['route removed',b=>{b.routeResults.routes.pop();}],['protocol instrument',b=>{b.protocol.instrument_count=4;}],['candidate admitted ledger',b=>{b.candidates.admitted_sources=1;}],['matrix class',b=>{b.matrix.class_id='RD-06-C01';}],['parent identity',b=>{b.parent.execution_id='OTHER';}],['seed label',b=>{b.seed.closure_target='other';}],['constitution label',b=>{b.constitution.lane_attempts.find((r)=>r.class_id==='RD-03-C04').exact_label='other';}],['schema open',b=>{b.schema.additionalProperties=true;}],['schema denominator',b=>{b.schema.properties.instruments.maxItems=6;}],['schema state count',b=>{b.schema.properties.counts.properties.source_unavailable_after_fixed_protocol_fields.const=46;}]
];
for(const[name,mutate]of mutations){const candidate=clone(bundle);mutate(candidate);assert.throws(()=>validateProductShape(candidate),undefined,name);}
const custodyMutations=[['pre closed count',v=>{v.counts.closed_residual_classes=5;}],['pre open count',v=>{v.counts.open_residual_classes=37;}],['pre RD03 removed',v=>{v.selected_classes_open=v.selected_classes_open.filter((r)=>r.class_id!=='RD-03-C04');}],['pre graph',v=>{v.current_result.graph_effect='edge';}],['post merge',v=>{v.promoted_class_receipts[4].merge_commit='bad';}],['post manifest',v=>{v.promoted_class_receipts[4].manifest_combined_sha256='0'.repeat(64);}],['post reconciliation',v=>{v.promoted_class_receipts[4].label_reconciliation='none';}],['post exact label flag',v=>{v.promoted_class_receipts[4].labels_exact_match=true;}],['post reopened',v=>{v.selected_classes_open.push({lane_id:'RD-03',class_id:'RD-03-C04'});}],['post state',v=>{v.promoted_class_receipts[4].terminal_state='evidence_complete';}],['post order',v=>{v.promoted_class_receipts.reverse();}],['post effect',v=>{v.counts.external_reviews=1;}]];
for(const[name,mutate]of custodyMutations){const candidate=clone(name.startsWith('post')?post:pre);mutate(candidate);assert.throws(()=>validateCurrentAtlasCustody(candidate,bundle.manifest.combined_sha256),undefined,name);}
console.log(`RD-03 terminal adversarial suite: ${mutations.length+custodyMutations.length} mutations refused`);
