import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildProduct } from '../tools/build-status-sovereignty-rd-wave03-rd04-postpromotion-next-adjudication.mjs';
import { validateProduct } from '../tools/validate-status-sovereignty-rd-wave03-rd04-postpromotion-next-adjudication.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
assert.deepEqual(validateProduct(ROOT),{ok:true,routes:5,reviewedSourceAdmissions:4,promotionCandidates:4,heldOpenCells:2,matrixUpdates:0});
const {objects,manifest}=buildProduct(ROOT);
const refusals=[]; const reject=(name,mutate,check)=>{const v=structuredClone({objects,manifest});mutate(v);assert.throws(()=>check(v),undefined,name);refusals.push(name);};
const must=(c,m)=>{if(!c)throw new Error(m);};
reject('transport is not automatic source admission',v=>v.objects['capture-custody.json'].authority_boundary.automatic_source_admissions=1,v=>must(v.objects['capture-custody.json'].authority_boundary.automatic_source_admissions===0,'automatic source admission'));
reject('five-route denominator immutable',v=>v.objects['capture-custody.json'].counts.fixed_routes=6,v=>must(v.objects['capture-custody.json'].counts.fixed_routes===5,'route count'));
reject('no spawned requests',v=>v.objects['capture-custody.json'].counts.result_spawned_requests=1,v=>must(v.objects['capture-custody.json'].counts.result_spawned_requests===0,'spawn'));
reject('artifact digest immutable',v=>v.objects['capture-custody.json'].artifact.archive_sha256='0'.repeat(64),v=>must(v.objects['capture-custody.json'].artifact.archive_sha256==='9b828cef364b156cc995409e445d5a1250c981127d21b841d56b05ef14b036e3','digest'));
reject('ND shell not admitted',v=>v.objects['source-adjudications.json'].decisions[3].source_admitted_for_narrow_scope=true,v=>must(v.objects['source-adjudications.json'].decisions[3].source_admitted_for_narrow_scope===false,'ND shell'));
reject('ND section cannot widen to authority',v=>v.objects['source-adjudications.json'].decisions[4].excluded_cross_field_ids=[],v=>must(v.objects['source-adjudications.json'].decisions[4].excluded_cross_field_ids.includes('operative_state_implementation_authority_and_version'),'cross field'));
reject('four source admissions only',v=>v.objects['source-adjudications.json'].counts.reviewed_source_admissions=5,v=>must(v.objects['source-adjudications.json'].counts.reviewed_source_admissions===4,'source count'));
reject('six field decisions',v=>v.objects['field-adjudications.json'].counts.field_decisions=5,v=>must(v.objects['field-adjudications.json'].counts.field_decisions===6,'field count'));
reject('four candidates only',v=>v.objects['field-adjudications.json'].counts.evidence_complete_candidates=5,v=>must(v.objects['field-adjudications.json'].counts.evidence_complete_candidates===4,'candidate count'));
reject('ND authority remains open',v=>v.objects['field-adjudications.json'].decisions[3].promotion_candidate=true,v=>must(v.objects['field-adjudications.json'].decisions[3].promotion_candidate===false,'ND authority'));
reject('ND waiver remains open',v=>v.objects['field-adjudications.json'].decisions[5].promotion_candidate=true,v=>must(v.objects['field-adjudications.json'].decisions[5].promotion_candidate===false,'ND waiver'));
reject('ND waiver date seam preserved',v=>v.objects['field-adjudications.json'].decisions[5].observed_support.section_effective_date='2025-10-31',v=>must(v.objects['field-adjudications.json'].decisions[5].observed_support.section_effective_date==='2025-11-01','date seam'));
reject('zero matrix updates',v=>v.objects['field-adjudications.json'].counts.matrix_updates=1,v=>must(v.objects['field-adjudications.json'].counts.matrix_updates===0,'matrix update'));
reject('zero field terminalizations',v=>v.objects['field-adjudications.json'].counts.substantive_field_terminalizations=4,v=>must(v.objects['field-adjudications.json'].counts.substantive_field_terminalizations===0,'terminalization'));
reject('zero row mutations',v=>v.objects['field-adjudications.json'].counts.row_state_mutations=1,v=>must(v.objects['field-adjudications.json'].counts.row_state_mutations===0,'row mutation'));
reject('class remains open',v=>v.objects['field-adjudications.json'].authority_boundary.class_closed=true,v=>must(v.objects['field-adjudications.json'].authority_boundary.class_closed===false,'class'));
reject('candidate-only promotion',v=>v.objects['promotion-candidate-protocol.json'].candidates[0].promotion_status='promoted',v=>must(v.objects['promotion-candidate-protocol.json'].candidates.every(x=>x.promotion_status==='candidate_only'),'promotion'));
reject('promotion has no matrix authority',v=>v.objects['promotion-candidate-protocol.json'].candidates[0].matrix_update_authority=true,v=>must(v.objects['promotion-candidate-protocol.json'].candidates.every(x=>x.matrix_update_authority===false),'authority'));
reject('terminal denominator unchanged',v=>v.objects['adjudication-summary.json'].frontier_after_adjudication.terminal_cells=226,v=>must(v.objects['adjudication-summary.json'].frontier_after_adjudication.terminal_cells===222,'terminal denominator'));
reject('open denominator unchanged',v=>v.objects['adjudication-summary.json'].frontier_after_adjudication.open_substantive_cells=184,v=>must(v.objects['adjudication-summary.json'].frontier_after_adjudication.open_substantive_cells===188,'open denominator'));
reject('outside human false',v=>v.objects['adjudication-summary.json'].authority_boundary.outside_human_dependency=true,v=>must(v.objects['adjudication-summary.json'].authority_boundary.outside_human_dependency===false,'human'));
reject('publication none',v=>v.manifest.publication_effect='some',v=>must(v.manifest.publication_effect==='none','publication'));
reject('adoption none',v=>v.manifest.adoption_effect='some',v=>must(v.manifest.adoption_effect==='none','adoption'));
reject('graph none',v=>v.manifest.graph_effect='some',v=>must(v.manifest.graph_effect==='none','graph'));
assert.equal(refusals.length,24); console.log(JSON.stringify({ok:true,adversarialRefusals:refusals.length},null,2));
