reviews += [
Rv('CS-BLIND-0012-B02','person_attributable_collective',[
 P('CS-RV-0012-B02-A','artifact_validity','coherent_collective_evidence_request_two_dimensions_provisionally_supported',['qualified technical team preserved uncertainty and requested proportionate evidence before an irreversible transition'],['catastrophic outcome alone does not prove the requested evidence would have enabled intervention']),
 P('CS-RV-0012-B02-B','adversarial_countermodel','collective_support_survives_person_and_custody_inference_fails',['the request and denial remain a bounded exception-handling and restraint trace'],['collective authorship prevents individual attribution; request custody is not an independent handoff; imagery efficacy remains counterfactual'])],
 {'support_adjusted_surplus':'not_tested_support_ledger_missing','cross_domain_transfer':'not_tested','exception_handling':'bounded_support_collective_evidence_channel_request','custody':'insufficient_request_record_preserved_no_attributable_handoff','model_elasticity':'not_tested','governed_capacity':'not_tested_requesting_team_did_not_control_gate','non_zero_sum_orientation':'not_tested','epistemic_restraint':'bounded_support_collective_uncertainty_preserved'},2,None,
 {'question':'Does preservation of the request support custody?','artifact_validity_position':'request and response are source-addressable','adversarial_position':'custody dimension requires attributable handoff or entrusted-object return','resolution':'preserve request custody as evidence context; do not advance custody dimension'},
 'retain_collective_technical_function_support_no_person_operator_or_field_test',
 {'historical_intake_class':'ordinary_specialists','analysis_class':'collective_technical_function','historical_row_rewritten':False}),
Rv('CS-BLIND-0017-B02','person_attributable_checking_function',[
 P('CS-RV-0017-B02-A','artifact_validity','coherent_checking_function_output_two_dimensions_provisionally_supported',['a formal compliance output crossed the reporting gate and remained reviewable during an unstable board relationship'],['the packet is a later official reconstruction and the complete underlying report is not separately retained']),
 P('CS-RV-0017-B02-B','adversarial_countermodel','checking_function_support_survives_surplus_and_retaliation_inference_fails',['report issuance and preservation support bounded custody and governed checking capacity'],['anticipated termination is not a formal removal order; the office had statutory authority and staff; board rationale remains incomplete'])],
 {'support_adjusted_surplus':'no_bounded_support_substantial_formal_office_support','cross_domain_transfer':'not_tested','exception_handling':'not_tested','custody':'bounded_support_checking_output_issued_and_preserved','model_elasticity':'not_tested','governed_capacity':'bounded_support_independent_checking_function_exercised','non_zero_sum_orientation':'not_tested','epistemic_restraint':'not_tested_complete_audit_and_board_record_missing'},2,None,
 {'question':'Does resignation after anticipated termination establish retaliatory removal?','artifact_validity_position':'the checking output and relationship transition are coherent','adversarial_position':'formal removal and complete board reasons are absent','resolution':'retain checking-function support; make no retaliation, surplus, or universal operator finding'},
 'retain_checking_function_support_acquire_original_report_board_record_and_handoff',None)]
