#!/usr/bin/env python3
from __future__ import annotations
import copy, hashlib, json, os, re
from pathlib import Path
ROOT=Path.cwd()
PARENT='e62de80e187f9be037cbdd3a4b942b5840d223de'; PARENT_TREE='0d1f8369e2c68d18b11a8f375903ff597ea8ccdb'; MATRIX_PATH='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation/promoted-partial-field-matrix.json'; MATRIX_BYTES=499923; MATRIX_SHA='9f9dc05a057396056771bb566c44e9c3779d8ef6b0d2c078f7ffff11d9c7e6cb'; MATRIX_BLOB='6ba11a6025021e9df8ac6535be8c42499654c233'
PRODUCT_ROOT='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1'; CUST='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/current-row-custody.json'; VAL='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/row-state-validation.json'; PROTOCOL='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/validated-row-state-protocol.json'; SUMMARY='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/summary.json'; MANIFEST='data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/product-manifest.json'; PATHS=['.github/workflows/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1.yml', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/current-row-custody.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/row-state-validation.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/validated-row-state-protocol.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/summary.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-mt-row-state-reconciliation-validation-v1/product-manifest.json', 'tools/validate-status-sovereignty-rd-wave03-rd04-mt-row-state-reconciliation-v1.py']
MT_ROW_SHA='06ab54ffbb8deaed317cfef33c44e685c43e17f2b3f6bb7f2c715f9a38ed86cc'; MT_CELL_SHA='221d9a1a9ecf55d786ab6f92faf77dd0795b3f4ef344cbccf64b4b72356ec2de'; PROPOSED_SHA='ba173d03c2f82316ca79eb8b6627057db6fdb54113340ff0f9539a85e89a1f2d'; PROJECTED_ROW_SHA='b6474320f690a653eae081cf655a090bb5d5da0f444e9a1c42077fd0b951bcbc'; PROJECTED_BYTES=502424; PROJECTED_SHA='12e52344af0c8ec3d845b6f05f8a20014fa84504d10dbc9ee0674d37715abe1d'; PROJECTED_BLOB='741bda42b609f386d71090e6368af537fd334914'; NON_TARGET_SHA='931041ee6120c5742a3fc3223220636fe127d1c1962e389787c8f0e24f135d76'
def jb(v): return (json.dumps(v,indent=2,ensure_ascii=False)+'\n').encode()
def canon(v): return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def sha(b): return hashlib.sha256(b).hexdigest()
def csha(v): return sha(canon(v))
def blob(b): return hashlib.sha1(f'blob {len(b)}\0'.encode()+b).hexdigest()
def load(p): return json.loads((ROOT/p).read_text())
def assert_boundary(x):
 assert x=={'source_requests': 0, 'route_executions': 0, 'source_admissions': 0, 'field_terminalizations': 0, 'matrix_updates': 0, 'row_state_mutations': 0, 'row_terminalizations': 0, 'class_closed': False, 'cumulative_ledger_effect': 'none', 'publication_effect': 'none', 'adoption_effect': 'none', 'graph_effect': 'none', 'outside_human_dependency': False}
def derive(matrix, proposed):
 mt=next(r for r in matrix['rows'] if r['unit_id']=='US-STATE-MT'); assert csha(mt)==MT_ROW_SHA
 cell=next(c for c in mt['cells'] if c['field_id']=='field_and_row_terminal_state'); assert csha(cell)==MT_CELL_SHA and not cell['terminal']
 evidence=[c for c in mt['cells'] if c['field_id']!='field_and_row_terminal_state']; assert len(evidence)==8 and all(c['terminal'] and c['state']=='evidence_complete' for c in evidence)
 row=copy.deepcopy(mt); row['cells'][-1]=copy.deepcopy(proposed); row['terminal_fields']=9; row['open_fields']=0; row['row_state']='terminal_fixed_public_record_obligation_complete'; assert csha(row)==PROJECTED_ROW_SHA
 out=copy.deepcopy(matrix); out['rows'][next(i for i,r in enumerate(out['rows']) if r['unit_id']=='US-STATE-MT')]=row
 for k,d in [('evidence_complete_cells',1),('terminal_cells',1),('still_open_cells',-1),('row_terminal_state_cells_terminal',1),('row_terminal_state_cells_open',-1),('terminal_units',1)]: out['counts'][k]+=d
 out['current_result']['terminal_cells']='230/450'; out['current_result']['still_open_cells']='220/450'; out['current_result']['row_terminal_state_cells_terminal']=12; out['current_result']['row_terminal_state_cells_open']=38; out['current_result']['terminal_units']=12; out['current_result']['terminal_unit_ids']=[r['unit_id'] for r in out['rows'] if r['row_state']=='terminal_fixed_public_record_obligation_complete']
 return out
def validate(custody, validation, protocol, summary, manifest, matrix):
 assert custody['canonical_parent']==PARENT and custody['canonical_parent_tree']==PARENT_TREE; assert custody['matrix']=={'path':MATRIX_PATH,'bytes':MATRIX_BYTES,'sha256':MATRIX_SHA,'git_blob_sha':MATRIX_BLOB,'counts':custody['matrix']['counts']}
 assert custody['montana']['row_sha256']==MT_ROW_SHA and custody['montana']['row_state_cell_sha256']==MT_CELL_SHA and custody['montana']['row_state']=='still_open' and custody['montana']['terminal_fields']==8 and custody['montana']['open_fields']==1 and custody['montana']['all_eight_evidence_fields_terminal'] is True and custody['montana']['remaining_open_field_id']=='field_and_row_terminal_state' and custody['montana']['terminal_evidence_state_counts']=={'evidence_complete':8,'observed':0,'not_publicly_recovered':0}; assert_boundary(custody['authority_boundary'])
 proposed=validation['proposed_row_state_cell']; assert csha(proposed)==PROPOSED_SHA and validation['proposed_row_state_cell_sha256']==PROPOSED_SHA; assert proposed['value']['predecessor_row_canonical_sha256']==MT_ROW_SHA; assert proposed['value']['terminal_evidence_state_counts']=={'evidence_complete':8,'observed':0,'not_publicly_recovered':0}; assert proposed['value']['prohibited_inferences'][-1]=='do_not_close_rd04_c02_or_wave03_from_twelve_terminal_rows'
 out=derive(matrix,proposed); data=jb(out); assert len(data)==PROJECTED_BYTES and sha(data)==PROJECTED_SHA and blob(data)==PROJECTED_BLOB
 assert validation['projected_row']['row_sha256']==PROJECTED_ROW_SHA; assert validation['projected_semantic_matrix']['sha256']==PROJECTED_SHA and validation['projected_semantic_matrix']['git_blob_sha']==PROJECTED_BLOB; assert validation['projected_semantic_matrix']['counts']['terminal_cells']==230 and validation['projected_semantic_matrix']['counts']['still_open_cells']==220 and validation['projected_semantic_matrix']['counts']['terminal_substantive_cells']==118 and validation['projected_semantic_matrix']['counts']['still_open_substantive_cells']==182 and validation['projected_semantic_matrix']['counts']['terminal_units']==12 and not validation['projected_semantic_matrix']['counts']['class_closed']; assert_boundary(validation['authority_boundary'])
 non=[r for r in matrix['rows'] if r['unit_id']!='US-STATE-MT']; assert sha(b'\n'.join(canon(r) for r in non)+b'\n')==NON_TARGET_SHA
 assert protocol['admitted_candidate']['proposed_cell_sha256']==PROPOSED_SHA and protocol['admitted_candidate']['projected_row_sha256']==PROJECTED_ROW_SHA and protocol['admitted_candidate']['projected_matrix_sha256']==PROJECTED_SHA; assert protocol['future_promotion_contract']=={'required_parent_relation':'canonical_merge_of_this_exact_validation_product','required_product_topology':'one_sole_parent_addition_only_product','maximum_substantive_field_terminalizations':0,'maximum_matrix_updates':1,'maximum_row_state_mutations':1,'maximum_row_terminalizations':1,'class_closure_authorized':False,'source_request_authorized':False,'route_execution_authorized':False,'outside_human_dependency':False}; assert_boundary(protocol['authority_boundary'])
 assert summary['projected_terminal_cells']==230 and summary['projected_still_open_cells']==220 and summary['projected_terminal_units']==12 and not summary['promotion_executed_here'] and not summary['class_closed']
 assert manifest['schema_version']=='ssc-rd04-mt-row-state-reconciliation-validation-product-manifest@1' and manifest['permanent_paths']==PATHS and manifest['permanent_path_count']==7 and manifest['hashed_file_count']==6 and len(manifest['hashed_files'])==6 and len({r['path'] for r in manifest['hashed_files']})==6; expected=sorted(p for p in PATHS if p!=MANIFEST); assert sorted(r['path'] for r in manifest['hashed_files'])==expected
 for r in manifest['hashed_files']:
  d=(ROOT/r['path']).read_bytes(); assert len(d)==r['bytes'] and sha(d)==r['sha256'] and blob(d)==r['git_blob']
 combined=''.join(sorted(f"{r['path']}\0{r['sha256']}\0{r['bytes']}\n" for r in manifest['hashed_files'])).encode(); assert sha(combined)==manifest['combined_sha256']; assert_boundary(manifest['authority_boundary'])
def adversarial(c,v,p,s,m,matrix):
 mutations=[]
 for key in ['row_state','terminal_fields','open_fields']: mutations.append(('custody_mt_'+key,lambda x,k=key: x['montana'].__setitem__(k,'drift' if k=='row_state' else 99)))
 mutations += [('custody_request',lambda x:x['authority_boundary'].__setitem__('source_requests',1)),('custody_class',lambda x:x['authority_boundary'].__setitem__('class_closed',True))]
 for key in ['state','terminal','authority_effect']: mutations.append(('candidate_'+key,lambda x,k=key:x['proposed_row_state_cell'].__setitem__(k,'drift' if k!='terminal' else False)))
 for key in ['terminal_classification','row_scope','completed_evidence_fields','predecessor_row_canonical_sha256','completion_rule','class_effect','cumulative_ledger_effect']: mutations.append(('candidate_value_'+key,lambda x,k=key:x['proposed_row_state_cell']['value'].__setitem__(k,'drift' if k!='completed_evidence_fields' else 7)))
 mutations += [('candidate_counts',lambda x:x['proposed_row_state_cell']['value']['terminal_evidence_state_counts'].__setitem__('evidence_complete',7)),('candidate_source',lambda x:x['proposed_row_state_cell'].__setitem__('evidence_source_ids',['wrong'])),('validation_matrix',lambda x:x['projected_semantic_matrix'].__setitem__('sha256','0'*64)),('validation_terminal',lambda x:x['projected_semantic_matrix']['counts'].__setitem__('terminal_cells',229)),('validation_substantive',lambda x:x['projected_semantic_matrix']['counts'].__setitem__('terminal_substantive_cells',119)),('validation_class',lambda x:x['projected_semantic_matrix']['counts'].__setitem__('class_closed',True)),('protocol_parent',lambda x:x['future_promotion_contract'].__setitem__('required_parent_relation','arbitrary')),('protocol_source',lambda x:x['future_promotion_contract'].__setitem__('source_request_authorized',True)),('summary_execution',lambda x:x.__setitem__('promotion_executed_here',True)),('manifest_path',lambda x:x['permanent_paths'].__setitem__(0,'wrong')),('manifest_digest',lambda x:x.__setitem__('combined_sha256','0'*64))]
 refused=0
 for name,mut in mutations:
  cc,vv,pp,ss,mm=copy.deepcopy(c),copy.deepcopy(v),copy.deepcopy(p),copy.deepcopy(s),copy.deepcopy(m)
  target=cc if name.startswith('custody_') else vv if name.startswith(('candidate_','validation_')) else pp if name.startswith('protocol_') else ss if name.startswith('summary_') else mm
  mut(target)
  try: validate(cc,vv,pp,ss,mm,matrix)
  except (AssertionError,KeyError,TypeError): refused+=1
  else: raise AssertionError(f'adversarial mutation accepted: {name}')
 return refused
matrix_data=(ROOT/MATRIX_PATH).read_bytes(); assert len(matrix_data)==MATRIX_BYTES and sha(matrix_data)==MATRIX_SHA and blob(matrix_data)==MATRIX_BLOB; matrix=json.loads(matrix_data)
c,v,p,s,m=load(CUST),load(VAL),load(PROTOCOL),load(SUMMARY),load(MANIFEST); validate(c,v,p,s,m,matrix); refused=adversarial(c,v,p,s,m,matrix); assert refused==26
receipt={'schema_version':'ssc-rd04-mt-row-state-reconciliation-validation-receipt@1','state':'qualified_request_free_montana_row_state_candidate','validation_head':os.environ.get('VALIDATION_HEAD'),'canonical_parent':PARENT,'matrix_sha256':MATRIX_SHA,'montana_row_sha256':MT_ROW_SHA,'montana_row_state_cell_sha256':MT_CELL_SHA,'proposed_cell_sha256':PROPOSED_SHA,'projected_row_sha256':PROJECTED_ROW_SHA,'projected_matrix_bytes':PROJECTED_BYTES,'projected_matrix_sha256':PROJECTED_SHA,'projected_matrix_git_blob':PROJECTED_BLOB,'projected_terminal_cells':230,'projected_still_open_cells':220,'projected_terminal_substantive_cells':118,'projected_still_open_substantive_cells':182,'projected_terminal_units':12,'adversarial_refusals':refused,'promotion_executed_here':False,'class_closed':False,'source_requests':0,'route_executions':0,'source_admissions':0,'field_terminalizations':0,'matrix_updates':0,'row_state_mutations':0,'row_terminalizations':0,'outside_human_dependency':False}
print(json.dumps(receipt,sort_keys=True))
