#!/usr/bin/env python3
from __future__ import annotations
import copy,hashlib,json,os,pathlib,subprocess
ROOT=pathlib.Path.cwd(); VROOT=ROOT/os.environ['VALIDATION_ROOT']; MATRIX=ROOT/os.environ['MATRIX_PATH']
def load(p): return json.loads(p.read_text(encoding='utf-8'))
def canon(v): return json.dumps(v,sort_keys=True,separators=(',',':'),ensure_ascii=False).encode()
def sha(b): return hashlib.sha256(b).hexdigest()
def blob(b): return hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()
AUTH_KEYS=sorted(['source_requests', 'route_executions', 'source_admissions', 'field_terminalizations', 'matrix_updates', 'row_state_mutations', 'row_terminalizations', 'class_closed', 'cumulative_ledger_effect', 'publication_effect', 'adoption_effect', 'graph_effect', 'outside_human_dependency'])
def authority(v):
 assert sorted(v)==AUTH_KEYS
 assert v=={'source_requests': 0, 'route_executions': 0, 'source_admissions': 0, 'field_terminalizations': 0, 'matrix_updates': 0, 'row_state_mutations': 0, 'row_terminalizations': 0, 'class_closed': False, 'cumulative_ledger_effect': 'none', 'publication_effect': 'none', 'adoption_effect': 'none', 'graph_effect': 'none', 'outside_human_dependency': False}
raw=MATRIX.read_bytes(); assert len(raw)==495400 and sha(raw)=='1878270c1c34d1a96b28eb0ee26eff5b1b3b6c8d74a56026c293544c7925d824' and blob(raw)=='c25a1ad8fdfe82f70f1ff71e61da6796be94c737'
matrix=json.loads(raw); expected_before={'terminal_cells':228,'still_open_cells':222,'terminal_substantive_cells':118,'still_open_substantive_cells':182,'evidence_complete_cells':197,'observed_cells':17,'not_publicly_recovered_cells':14,'row_terminal_state_cells_terminal':10,'row_terminal_state_cells_open':40,'terminal_units':10,'class_closed':False}
for k,v in expected_before.items(): assert matrix['counts'][k]==v
assert sum(r['row_state']=='terminal_fixed_public_record_obligation_complete' for r in matrix['rows'])==10
nd=next(r for r in matrix['rows'] if r['unit_id']=='US-STATE-ND'); assert sha(canon(nd))=='0f3ba29ee5c7354249f89c96fc38c21b55341fc9fdad9b5919ecdb9243c4929e'; assert (nd['row_state'],nd['terminal_fields'],nd['open_fields'])==('still_open',8,1)
fields=['canonical_state_identity', 'operative_state_implementation_authority_and_version', 'implementation_effective_date_or_typed_gap', 'abawd_or_work_requirement_waiver_state_and_governing_period', 'discretionary_exemption_authority_and_reported_state_practice', 'fitness_for_work_or_eligibility_screening_rule', 'verification_evidence_and_staff_discretion_surface', 'source_identities_and_exact_custody']; assert [c['field_id'] for c in nd['cells'][:8]]==fields and all(c['terminal'] for c in nd['cells'][:8]); assert [c['state'] for c in nd['cells'][:8]].count('evidence_complete')==7 and [c['state'] for c in nd['cells'][:8]].count('not_publicly_recovered')==1
current=nd['cells'][8]; assert sha(canon(current))=='6a4c7d204c6c99a89f3c121065860806668c5da850f44c67fe42b4dc84b1b5c3'; assert current['field_id']=='field_and_row_terminal_state' and current['state']=='still_open' and current['terminal'] is False
custody=load(VROOT/'current-row-custody.json'); validation=load(VROOT/'row-state-validation.json'); protocol=load(VROOT/'validated-row-state-protocol.json'); summary=load(VROOT/'summary.json'); manifest=load(VROOT/'product-manifest.json')
for o in [custody,validation,protocol,summary,manifest]: authority(o['authority_boundary'])
assert custody['canonical_parent']=='bab9570ab043df7c5062e5a45a0717a82eed346b' and custody['canonical_parent_tree']=='cca6b16db286f00125b9375c3a3cc505e58b3525' and custody['matrix']['git_blob_sha']=='c25a1ad8fdfe82f70f1ff71e61da6796be94c737' and custody['north_dakota']['all_eight_substantive_fields_terminal'] is True
proposed=validation['proposed_row_state_cell']; assert sha(canon(proposed))=='f0c6fe75d1720c1a6cf8b90fd44b96bc96fcb0656fc70808c5439d514d30217c'; assert proposed=={'field_ordinal': 9, 'field_id': 'field_and_row_terminal_state', 'state': 'evidence_complete', 'terminal': True, 'value': {'terminal_classification': 'terminal_fixed_public_record_obligation_complete', 'row_scope': 'fixed_public_record_obligation_for_one_state', 'completed_evidence_fields': 8, 'terminal_evidence_field_ids': ['canonical_state_identity', 'operative_state_implementation_authority_and_version', 'implementation_effective_date_or_typed_gap', 'abawd_or_work_requirement_waiver_state_and_governing_period', 'discretionary_exemption_authority_and_reported_state_practice', 'fitness_for_work_or_eligibility_screening_rule', 'verification_evidence_and_staff_discretion_surface', 'source_identities_and_exact_custody'], 'terminal_evidence_state_counts': {'evidence_complete': 7, 'observed': 0, 'not_publicly_recovered': 1}, 'predecessor_row_canonical_sha256': '0f3ba29ee5c7354249f89c96fc38c21b55341fc9fdad9b5919ecdb9243c4929e', 'completion_rule': 'all_eight_declared_state_evidence_fields_are_terminal_under_exact_source_or_typed_gap_custody', 'class_effect': 'none', 'cumulative_ledger_effect': 'none', 'limitations': ['row completion closes only the declared fixed public-record obligation for this state', 'typed source gaps remain distinct from event, policy, practice, or implementation absence', 'row completion does not establish uniform frontline practice or person-level outcome', 'eleven terminal rows do not establish national prevalence or close RD-04-C02'], 'prohibited_inferences': ['do_not_infer_complete_state_implementation_truth_beyond_terminal_field_custody', 'do_not_convert_not_publicly_recovered_fields_into_event_or_policy_absence', 'do_not_infer_uniform_frontline_practice', 'do_not_infer_person_level_outcome', 'do_not_infer_national_prevalence', 'do_not_infer_discrimination_or_racial_order', 'do_not_infer_coordination_or_common_purpose', 'do_not_infer_complete_compact', 'do_not_close_rd04_c02_or_wave03_from_eleven_terminal_rows']}, 'evidence_source_ids': ['RD04-ND-ROW-STATE-RECONCILIATION-V1'], 'typed_gap': None, 'authority_effect': 'row_level_fixed_public_record_obligation_terminal_only'}
projected=copy.deepcopy(matrix); after=next(r for r in projected['rows'] if r['unit_id']=='US-STATE-ND'); after['row_state']='terminal_fixed_public_record_obligation_complete'; after['terminal_fields']=9; after['open_fields']=0; after['cells'][8]=copy.deepcopy(proposed); counts=projected['counts']; counts.update({'evidence_complete_cells':198,'still_open_cells':221,'terminal_cells':229,'row_terminal_state_cells_terminal':11,'row_terminal_state_cells_open':39,'terminal_units':11,'postpromotion_nd_current_public_record_gap_row_state_candidate_cells':1,'newly_terminalized_postpromotion_nd_current_public_record_gap_row_state_cells':1})
assert sum(r['row_state']=='terminal_fixed_public_record_obligation_complete' for r in projected['rows'])==11
raw2=(json.dumps(projected,indent=2,ensure_ascii=False)+'\n').encode(); assert len(raw2)==498047 and sha(raw2)=='9f85cbff7eba6d66f84508d262c408d580e1d55e95568d3265f10d1c1fa416ad' and blob(raw2)=='4911d717a072493f80a3631598799070f08f2a91'; assert sha(canon(after))=='f75ac04e5c8fc53304e897d918ee80057c580e2b8bbeeca979e9f92312f96f4b'
non=[r for r in matrix['rows'] if r['unit_id']!='US-STATE-ND']; assert sha(b''.join(canon(r)+b'\n' for r in non))=='e9507cce90ced2d303b6d464968c4eeed630f2f058ba4302980c34f32f3e1105'
assert validation['canonical_parent']=='bab9570ab043df7c5062e5a45a0717a82eed346b' and validation['projected_row']=={'row_sha256':'f75ac04e5c8fc53304e897d918ee80057c580e2b8bbeeca979e9f92312f96f4b','row_state':'terminal_fixed_public_record_obligation_complete','terminal_fields':9,'open_fields':0} and validation['projected_matrix']['sha256']=='9f85cbff7eba6d66f84508d262c408d580e1d55e95568d3265f10d1c1fa416ad' and validation['projected_matrix']['git_blob_sha']=='4911d717a072493f80a3631598799070f08f2a91'
assert validation['validation_result']['promotion_executed_here'] is False and validation['validation_result']['separate_promotion_product_authorized'] is True
assert protocol['canonical_parent']=='bab9570ab043df7c5062e5a45a0717a82eed346b' and protocol['required_row_state_after']=='terminal_fixed_public_record_obligation_complete' and protocol['validation_product_must_be_canonical_before_promotion'] is True and protocol['promotion_executed_here'] is False
assert summary['canonical_parent']=='bab9570ab043df7c5062e5a45a0717a82eed346b' and summary['projected']['north_dakota_row_state']=='terminal_fixed_public_record_obligation_complete' and summary['promotion_executed_here'] is False
expected=['.github/workflows/status-sovereignty-rd-wave03-rd04-nd-row-state-reconciliation-validation-v2.yml', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation-validation-v2/current-row-custody.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation-validation-v2/row-state-validation.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation-validation-v2/validated-row-state-protocol.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation-validation-v2/summary.json', 'data/intake/status-sovereignty-rd-wave03-rd04-postpromotion-nd-row-state-reconciliation-validation-v2/product-manifest.json', 'tools/validate-status-sovereignty-rd-wave03-rd04-nd-row-state-reconciliation-v2.py']; assert manifest['permanent_path_count']==7 and manifest['hashed_file_count']==6 and manifest['self_describing_manifest_excluded_from_combined_payload'] is True and manifest['permanent_paths']==expected
assert set(manifest)=={'schema_version','permanent_path_count','hashed_file_count','self_describing_manifest_excluded_from_combined_payload','permanent_paths','hashed_files','combined_sha256','authority_boundary'}
assert [r['path'] for r in manifest['hashed_files']]==[p for p in expected if not p.endswith('/product-manifest.json')]
rows=[]
for rec in manifest['hashed_files']:
 assert set(rec)=={'path','bytes','sha256','git_blob'}; data=(ROOT/rec['path']).read_bytes(); assert rec=={'path':rec['path'],'bytes':len(data),'sha256':sha(data),'git_blob':blob(data)}; rows.append(f"{rec['path']}\0{rec['sha256']}\0{rec['bytes']}\n")
assert sha(''.join(sorted(rows)).encode())==manifest['combined_sha256']
receipt={'schema_version':'ssc-rd04-nd-row-state-reconciliation-hosted-validation@2','state':'validated_exact_current_row_state_requires_separate_promotion','canonical_parent':'bab9570ab043df7c5062e5a45a0717a82eed346b','head':(os.environ.get('VALIDATION_HEAD') or subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()),'current_row_sha256':'0f3ba29ee5c7354249f89c96fc38c21b55341fc9fdad9b5919ecdb9243c4929e','current_row_state_cell_sha256':'6a4c7d204c6c99a89f3c121065860806668c5da850f44c67fe42b4dc84b1b5c3','proposed_row_state_cell_sha256':'f0c6fe75d1720c1a6cf8b90fd44b96bc96fcb0656fc70808c5439d514d30217c','projected_row_sha256':'f75ac04e5c8fc53304e897d918ee80057c580e2b8bbeeca979e9f92312f96f4b','projected_matrix_sha256':'9f85cbff7eba6d66f84508d262c408d580e1d55e95568d3265f10d1c1fa416ad','validated_candidates':1,'rejected_candidates':0,'promotion_executed_here':False,'projected_field_terminalizations':0,'projected_matrix_updates':1,'projected_row_state_mutations':1,'projected_row_terminalizations':1,'field_terminalizations':0,'matrix_updates':0,'row_state_mutations':0,'row_terminalizations':0,'class_closed':False,'outside_human_dependency':False}
print(json.dumps(receipt,indent=2,sort_keys=True))
